/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/mega/302.glb -o models/gltfjsx/mega/302.jsx 
Author: Gallery_of_anon (https://sketchfab.com/Gallery_of_anon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mega-sableye-38cf093e4b694a9aa6747c0cc47ff7a8
Title: Mega Sableye
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/302.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.261, 1.626, 0]} rotation={[0, 0, -0.369]} scale={0.318}>
        <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['Material.002']} />
      </group>
      <group position={[-1.006, 2.519, 0.848]} rotation={[0, -0.232, -0.296]} scale={[1.118, 0.714, 0.565]}>
        <mesh geometry={nodes.Object_11.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Object_12.geometry} material={materials['Material.010']} />
      </group>
      <group position={[-0.449, 2.461, 0.392]} rotation={[-3.12, 0.005, -2.495]} scale={0.052}>
        <mesh geometry={nodes.Object_14.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Object_15.geometry} material={materials['Material.007']} />
      </group>
    </group>
  )
}

useGLTF.preload('/302.glb')
