/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/shiny/201.glb -o models/gltfjsx/shiny/201.jsx 
Author: jersonseling (https://sketchfab.com/jersonseling)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/unown-shiny-73f751b8f58d4d40b2d47e681b460533
Title: Unown Shiny
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/201.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Body} />
      </group>
    </group>
  )
}

useGLTF.preload('/201.glb')
