/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/shiny/361.glb -o models/gltfjsx/shiny/361.jsx 
Author: Squirmy Worm (https://sketchfab.com/squirmyworm064)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/snorunt-c555d523f02c4882879294612cb481da
Title: Snorunt
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/shiny/361.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.color_10615807} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.color_13957119} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.color_14541540} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.color_16104991} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.color_16368730} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.color_16373882} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.color_16448250} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.color_16749947} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.color_16755781} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.color_16769669} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.color_16777215} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.color_2829873} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.color_6383466} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.color_8122623} />
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/shiny/361.glb')
