/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/shiny/38.glb -o models/gltfjsx/shiny/38.jsx 
Author: animalSS (https://sketchfab.com/animalSS)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shiny-ninetales-20f1b0bb8a9a4a5eb6736c9ec4df9937
Title: Shiny Ninetales
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/shiny/38.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.025}>
          <group position={[0, 57.508, -11.404]} rotation={[1.564, 0, Math.PI / 2]}>
            <primitive object={nodes._03_Waist_rootJoint} />
            <group position={[10.998, 0.002, 57.587]} rotation={[0, 1.564, -Math.PI / 2]}>
              <mesh geometry={nodes.Ninetales_0.geometry} material={materials.material} />
              <mesh geometry={nodes.Ninetales_1.geometry} material={materials.BodyA00} />
              <mesh geometry={nodes.Ninetales_2.geometry} material={materials.BodyB} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/shiny/38.glb')
