/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/shiny/726.glb -o models/gltfjsx/shiny/726.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/shiny/726.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.25, 0, 0]}>
        <mesh geometry={nodes.Object_13.geometry} material={materials.material_3} position={[0.25, 0, 0]} />
      </group>
      <group position={[-0.25, 0, 0]}>
        <mesh geometry={nodes.Object_17.geometry} material={materials.material_1} position={[0.25, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/shiny/726.glb')
