/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/shiny/788.glb -o models/gltfjsx/shiny/788.jsx 
Author: ⚙️-Gadget’s Model Workshop-⚙️ (https://sketchfab.com/GMS4396784)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/3ds-pokemon-sun-moon-789-shiny-tapu-fini-567c2be9b5e54fd3a6492fede4d7d9d7
Title: 3DS - Pokemon Sun Moon - 789 Shiny Tapu Fini
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/788.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <primitive object={nodes._rootJoint} />
        <skinnedMesh geometry={nodes.Object_6.geometry} material={materials['pm0833_00_Body1_tga-material']} skeleton={nodes.Object_6.skeleton} />
        <skinnedMesh geometry={nodes.Object_8.geometry} material={materials['pm0833_00_Eye1_tga-material']} skeleton={nodes.Object_8.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/788.glb')
