/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/1006.glb -o models/gltfjsx/regular/1006.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/1006.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[3.013, 0, 0]}>
        <mesh geometry={nodes.pm1097_00_00_blade_mesh_shape_1.geometry} material={materials.body_b_01} />
        <mesh geometry={nodes.pm1097_00_00_blade_mesh_shape_2.geometry} material={materials.body_b_02} />
        <mesh geometry={nodes.pm1097_00_00_blade_mesh_shape_3.geometry} material={materials.body_b_00} />
      </group>
      <group rotation={[3.013, 0, 0]}>
        <mesh geometry={nodes.pm1097_00_00_body_mesh_shape_1.geometry} material={materials.body_a_00} />
        <mesh geometry={nodes.pm1097_00_00_body_mesh_shape_2.geometry} material={materials.body_b_01} />
        <mesh geometry={nodes.pm1097_00_00_body_mesh_shape_3.geometry} material={materials.body_b_02} />
      </group>
      <group rotation={[3.013, 0, 0]}>
        <mesh geometry={nodes.pm1097_00_00_eye_mesh_shape_1.geometry} material={materials.r_eye} />
        <mesh geometry={nodes.pm1097_00_00_eye_mesh_shape_2.geometry} material={materials.l_eye} />
      </group>
      <group rotation={[3.013, 0, 0]}>
        <mesh geometry={nodes.pm1097_00_00_left_blade_mesh_shape_1.geometry} material={materials.body_b_01} />
        <mesh geometry={nodes.pm1097_00_00_left_blade_mesh_shape_2.geometry} material={materials.body_b_00} />
      </group>
      <group rotation={[3.013, 0, 0]}>
        <mesh geometry={nodes.pm1097_00_00_left_leg_mesh_shape_1.geometry} material={materials.body_a_00} />
        <mesh geometry={nodes.pm1097_00_00_left_leg_mesh_shape_2.geometry} material={materials.body_b_01} />
      </group>
      <group rotation={[3.013, 0, 0]}>
        <mesh geometry={nodes.pm1097_00_00_right_blade_mesh_shape_1.geometry} material={materials.body_b_01} />
        <mesh geometry={nodes.pm1097_00_00_right_blade_mesh_shape_2.geometry} material={materials.body_b_00} />
      </group>
      <group rotation={[3.013, 0, 0]}>
        <mesh geometry={nodes.pm1097_00_00_right_leg_mesh_shape_1.geometry} material={materials.body_a_00} />
        <mesh geometry={nodes.pm1097_00_00_right_leg_mesh_shape_2.geometry} material={materials.body_b_01} />
      </group>
      <group rotation={[3.013, 0, 0]}>
        <mesh geometry={nodes.pm1097_00_00_skirt_a_mesh_shape_1.geometry} material={materials.body_b_01} />
        <mesh geometry={nodes.pm1097_00_00_skirt_a_mesh_shape_2.geometry} material={materials.body_b_00} />
      </group>
      <group rotation={[3.013, 0, 0]}>
        <mesh geometry={nodes.pm1097_00_00_skirt_b_mesh_shape_1.geometry} material={materials.body_b_01} />
        <mesh geometry={nodes.pm1097_00_00_skirt_b_mesh_shape_2.geometry} material={materials.body_b_00} />
      </group>
    </group>
  )
}

useGLTF.preload('/1006.glb')
