/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/1007.glb -o models/gltfjsx/regular/1007.jsx 
Author: ijackprovostjr (https://sketchfab.com/ijackprovostjr)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pokemon-koraidon-battle-form-98124f61669c431b94c1e235967ab087
Title: Pokemon koraidon battle form
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/1007.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={1.508}>
        <primitive object={nodes.GLTF_created_0_rootJoint} />
        <skinnedMesh geometry={nodes.Object_7.geometry} material={materials.body_01} skeleton={nodes.Object_7.skeleton} />
        <skinnedMesh geometry={nodes.Object_9.geometry} material={materials.eye_l} skeleton={nodes.Object_9.skeleton} />
        <skinnedMesh geometry={nodes.Object_10.geometry} material={materials.eye_r} skeleton={nodes.Object_10.skeleton} />
        <skinnedMesh geometry={nodes.Object_12.geometry} material={materials.body_01} skeleton={nodes.Object_12.skeleton} />
        <skinnedMesh geometry={nodes.Object_14.geometry} material={materials.body_01} skeleton={nodes.Object_14.skeleton} />
        <skinnedMesh geometry={nodes.Object_16.geometry} material={materials.hair} skeleton={nodes.Object_16.skeleton} />
        <skinnedMesh geometry={nodes.Object_18.geometry} material={materials.hair} skeleton={nodes.Object_18.skeleton} />
        <skinnedMesh geometry={nodes.Object_20.geometry} material={materials.body_01} skeleton={nodes.Object_20.skeleton} />
        <skinnedMesh geometry={nodes.Object_22.geometry} material={materials.body_02} skeleton={nodes.Object_22.skeleton} />
        <skinnedMesh geometry={nodes.Object_24.geometry} material={materials.body_02} skeleton={nodes.Object_24.skeleton} />
        <skinnedMesh geometry={nodes.Object_26.geometry} material={materials.hair} skeleton={nodes.Object_26.skeleton} />
        <skinnedMesh geometry={nodes.Object_28.geometry} material={materials.body_02} skeleton={nodes.Object_28.skeleton} />
        <skinnedMesh geometry={nodes.Object_30.geometry} material={materials.body_01} skeleton={nodes.Object_30.skeleton} />
        <skinnedMesh geometry={nodes.Object_32.geometry} material={materials.body_01} skeleton={nodes.Object_32.skeleton} />
        <skinnedMesh geometry={nodes.Object_34.geometry} material={materials.wing} skeleton={nodes.Object_34.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/1007.glb')
