/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/1019.glb -o models/gltfjsx/regular/1019.jsx 
Author: Squirmy Worm (https://sketchfab.com/squirmyworm064)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hydrapple-f8fcd5bebe3b4dd185d47b7fcc7282de
Title: Hydrapple
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/1019.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.color_11830884} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.color_15539200} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.color_16663595} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.color_16766853} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.color_16771435} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.color_2829873} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.color_5028875} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.color_8512056} />
      </group>
    </group>
  )
}

useGLTF.preload('/1019.glb')
