/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/102.glb -o models/gltfjsx/regular/102.jsx 
Author: nguyenlouis32 (https://sketchfab.com/nguyenlouis32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/exeggcute-a8aec7a26dc941dfb88087918c0800ed
Title: Exeggcute
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/102.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_4.geometry} material={materials.CMouth_mat} />
          <mesh geometry={nodes.Object_5.geometry} material={materials.CEye_mat} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.BEye_mat} />
          <mesh geometry={nodes.Object_7.geometry} material={materials.AEye_mat} />
          <mesh geometry={nodes.Object_8.geometry} material={materials.BMouth_mat} />
          <mesh geometry={nodes.Object_9.geometry} material={materials.AMouth_mat} />
          <mesh geometry={nodes.Object_10.geometry} material={materials.BodySpc_mat} />
          <mesh geometry={nodes.Object_11.geometry} material={materials.CMouth_mat} />
          <mesh geometry={nodes.Object_12.geometry} material={materials.CEye_mat} />
          <mesh geometry={nodes.Object_13.geometry} material={materials.BEye_mat} />
          <mesh geometry={nodes.Object_14.geometry} material={materials.AEye_mat} />
          <mesh geometry={nodes.Object_15.geometry} material={materials.BMouth_mat} />
          <mesh geometry={nodes.Object_16.geometry} material={materials.AMouth_mat} />
          <mesh geometry={nodes.Object_17.geometry} material={materials.BodySpc_mat} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/102.glb')
