/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/1025.glb -o models/gltfjsx/regular/1025.jsx 
Author: Squirmy Worm (https://sketchfab.com/squirmyworm064)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pecharunt-8107b1f76c7f4ae89dbd24a8433944e2
Title: Pecharunt
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/regular/1025.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.color_10371447} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.color_10373256} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.color_10373271} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.color_11222396} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.color_12075654} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.color_12858247} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.color_12860811} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.color_13566105} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.color_16448250} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.color_16754913} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.color_2829873} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.color_3024197} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.color_4732536} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.color_5979269} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.color_7357073} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.color_8997022} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.color_9914526} />
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/regular/1025.glb')
