/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/118.glb -o models/gltfjsx/regular/118.jsx 
Author: nguyenlouis32 (https://sketchfab.com/nguyenlouis32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/goldeen-02d409c494c34ca9afe5bade3fd0f8d6
Title: Goldeen
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/118.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_4.geometry} material={materials.BodyTosakinto_Fin_mat_001} />
          <mesh geometry={nodes.Object_5.geometry} material={materials.BodyA_mat_001} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.Eye_mat_001} />
          <mesh geometry={nodes.Object_7.geometry} material={materials.BodyTosakinto_Fin_mat_001} />
          <mesh geometry={nodes.Object_8.geometry} material={materials.BodyA_mat_001} />
          <mesh geometry={nodes.Object_9.geometry} material={materials.Eye_mat_001} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/118.glb')
