/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/119.glb -o models/gltfjsx/regular/119.jsx 
Author: nguyenlouis32 (https://sketchfab.com/nguyenlouis32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/seaking-dc474909906e4b709e13da053f77322b
Title: Seaking
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/119.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_4.geometry} material={materials.Body_mat} />
          <mesh geometry={nodes.Object_5.geometry} material={materials.Eye_mat} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.Body_mat} />
          <mesh geometry={nodes.Object_7.geometry} material={materials.Eye_mat} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/119.glb')
