/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/120.glb -o models/gltfjsx/regular/120.jsx 
Author: nguyenlouis32 (https://sketchfab.com/nguyenlouis32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/staryu-6df9cd8835a34cd7be1ef445525740a4
Title: Staryu
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const { scene } = useGLTF('/120.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group rotation={[-3.139, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes._rootJoint} />
          <skinnedMesh geometry={nodes.Object_6.geometry} material={materials['Body_004-material']} skeleton={nodes.Object_6.skeleton} />
          <skinnedMesh geometry={nodes.Object_8.geometry} material={materials['BodyNutreyVco-material']} skeleton={nodes.Object_8.skeleton} />
          <skinnedMesh geometry={nodes.Object_10.geometry} material={materials['BodyNutrey-material']} skeleton={nodes.Object_10.skeleton} />
          <skinnedMesh geometry={nodes.Object_12.geometry} material={materials['BodyHitodeman-material']} skeleton={nodes.Object_12.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/120.glb')
