/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/121.glb -o models/gltfjsx/regular/121.jsx 
Author: nguyenlouis32 (https://sketchfab.com/nguyenlouis32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/starmie-cb3cce8385934fa79373a3a5dd7854bd
Title: Starmie
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/regular/121.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes._rootJoint} />
          <skinnedMesh geometry={nodes.Object_6.geometry} material={materials['BodyA01_003-material']} skeleton={nodes.Object_6.skeleton} />
          <skinnedMesh geometry={nodes.Object_8.geometry} material={materials['BodyB00_003-material']} skeleton={nodes.Object_8.skeleton} />
          <skinnedMesh geometry={nodes.Object_10.geometry} material={materials['BodyBHitodeman_003-material']} skeleton={nodes.Object_10.skeleton} />
          <skinnedMesh geometry={nodes.Object_12.geometry} material={materials['BodyANutreyVco_003-material']} skeleton={nodes.Object_12.skeleton} />
          <skinnedMesh geometry={nodes.Object_14.geometry} material={materials['BodyBNutreyVco_003-material']} skeleton={nodes.Object_14.skeleton} />
          <skinnedMesh geometry={nodes.Object_16.geometry} material={materials['BodyB01_003-material']} skeleton={nodes.Object_16.skeleton} />
          <skinnedMesh geometry={nodes.Object_18.geometry} material={materials['BodyA00_003-material']} skeleton={nodes.Object_18.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/regular/121.glb')
