/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/126.glb -o models/gltfjsx/regular/126.jsx 
Author: nguyenlouis32 (https://sketchfab.com/nguyenlouis32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/magmar-b721b3fa34e64d4c98b0a0f0792c4308
Title: Magmar
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/126.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_4.geometry} material={materials.FireCoreA_mat} />
          <mesh geometry={nodes.Object_5.geometry} material={materials.BodyA} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.BodyB} />
          <mesh geometry={nodes.Object_7.geometry} material={materials.BodyD} />
          <mesh geometry={nodes.Object_8.geometry} material={materials.Eye_mat} />
          <mesh geometry={nodes.Object_9.geometry} material={materials.FireStenA_mat} />
          <mesh geometry={nodes.Object_10.geometry} material={materials.FireCoreA_mat} />
          <mesh geometry={nodes.Object_11.geometry} material={materials.BodyA} />
          <mesh geometry={nodes.Object_12.geometry} material={materials.BodyB} />
          <mesh geometry={nodes.Object_13.geometry} material={materials.BodyD} />
          <mesh geometry={nodes.Object_14.geometry} material={materials.Eye_mat} />
          <mesh geometry={nodes.Object_15.geometry} material={materials.FireStenA_mat} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/126.glb')
