/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/130.glb -o models/gltfjsx/regular/130.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/130.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={2.54}>
        <group position={[0, 0.423, -0.236]} rotation={[1.134, 0, Math.PI / 2]}>
          <primitive object={nodes.Hips} />
          <primitive object={nodes.Spine1} />
        </group>
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
        <skinnedMesh geometry={nodes.GyaradosF_1.geometry} material={materials['Material #140']} skeleton={nodes.GyaradosF_1.skeleton} />
        <skinnedMesh geometry={nodes.GyaradosF_2.geometry} material={materials['Material #141']} skeleton={nodes.GyaradosF_2.skeleton} />
        <skinnedMesh geometry={nodes.GyaradosF_3.geometry} material={materials['Material #142']} skeleton={nodes.GyaradosF_3.skeleton} />
        <skinnedMesh geometry={nodes.GyaradosF_4.geometry} material={materials['Material #143']} skeleton={nodes.GyaradosF_4.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/130.glb')
