/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/137.glb -o models/gltfjsx/regular/137.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/137.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={2.54}>
        <primitive object={nodes.Waist} />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
        <skinnedMesh geometry={nodes.Porygon_1.geometry} material={materials['Material #114']} skeleton={nodes.Porygon_1.skeleton} />
        <skinnedMesh geometry={nodes.Porygon_2.geometry} material={materials['Material #115']} skeleton={nodes.Porygon_2.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/137.glb')
