/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/139.glb -o models/gltfjsx/regular/139.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const { scene } = useGLTF('/139.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={2.54}>
        <primitive object={nodes.Waist} />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
        <skinnedMesh geometry={nodes.Omastar_1.geometry} material={materials['Material #112']} skeleton={nodes.Omastar_1.skeleton} />
        <skinnedMesh geometry={nodes.Omastar_2.geometry} material={materials['Material #113']} skeleton={nodes.Omastar_2.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/139.glb')
