/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/154.glb -o models/gltfjsx/regular/154.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const { scene } = useGLTF('/154.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={2.54}>
        <group position={[0, 0.573, -0.056]} rotation={[1.522, 0, Math.PI / 2]}>
          <primitive object={nodes.Hips} />
          <primitive object={nodes.Spine1} />
        </group>
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
        <skinnedMesh geometry={nodes.MeganiumF_1.geometry} material={materials['Material #77']} skeleton={nodes.MeganiumF_1.skeleton} />
        <skinnedMesh geometry={nodes.MeganiumF_2.geometry} material={materials['Material #78']} skeleton={nodes.MeganiumF_2.skeleton} />
        <skinnedMesh geometry={nodes.MeganiumF_3.geometry} material={materials['Material #79']} skeleton={nodes.MeganiumF_3.skeleton} />
        <skinnedMesh geometry={nodes.MeganiumF_4.geometry} material={materials['Material #80']} skeleton={nodes.MeganiumF_4.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/154.glb')
