/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/158.glb -o models/gltfjsx/regular/158.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const { scene } = useGLTF('/158.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={2.54}>
        <group position={[0, 0.222, 0.005]} rotation={[0.153, 0, Math.PI / 2]}>
          <primitive object={nodes.Hips} />
          <primitive object={nodes.Spine} />
        </group>
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
        <skinnedMesh geometry={nodes.Totodile_1.geometry} material={materials['Material #128']} skeleton={nodes.Totodile_1.skeleton} />
        <skinnedMesh geometry={nodes.Totodile_2.geometry} material={materials['Material #129']} skeleton={nodes.Totodile_2.skeleton} />
        <skinnedMesh geometry={nodes.Totodile_3.geometry} material={materials['Material #130']} skeleton={nodes.Totodile_3.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/158.glb')
