/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/161.glb -o models/gltfjsx/regular/161.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/regular/161.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.Cube_Ears_0.geometry} material={materials.Ears} position={[2.271, 892.081, -7.705]} rotation={[-1.606, 0.283, 0.009]} scale={86.751} />
        <mesh geometry={nodes.Cube001_Feet_0.geometry} material={materials.Feet} position={[2.271, 381.108, -10.305]} rotation={[-1.302, -0.288, 0.786]} scale={86.751} />
        <mesh geometry={nodes.Cube002_Tail_0.geometry} material={materials.Tail} position={[2.271, 304.504, -33.182]} rotation={[-Math.PI / 2, 0, 0]} scale={86.751} />
        <mesh geometry={nodes.Sphere_Bod_0.geometry} material={materials.material} position={[2.271, 634.213, 1.604]} rotation={[-Math.PI / 2, 0, 0]} scale={86.751} />
        <mesh geometry={nodes.Sphere001_EyEs_0.geometry} material={materials.EyEs} position={[2.271, 777.819, 103.04]} rotation={[-0.763, 0.206, 0.017]} scale={86.751} />
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/regular/161.glb')
