/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/162.glb -o models/gltfjsx/regular/162.jsx 
Author: nguyenlouis32 (https://sketchfab.com/nguyenlouis32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/furret-449cef6e5a1e43f798a5977493e2e6a6
Title: Furret
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/162.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_5.geometry} material={materials.Material__186} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.Material__187} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.Material__188} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.Material__186} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.Material__187} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.Material__188} />
    </group>
  )
}

useGLTF.preload('/162.glb')
