/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/164.glb -o models/gltfjsx/regular/164.jsx 
Author: nguyenlouis32 (https://sketchfab.com/nguyenlouis32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/noctowl-d061d2b1e7ab4ad38e3fb9f681769bf3
Title: Noctowl
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const { scene } = useGLTF('/164.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes._rootJoint} />
          <skinnedMesh geometry={nodes.Object_6.geometry} material={materials['BodyBVco-material']} skeleton={nodes.Object_6.skeleton} />
          <skinnedMesh geometry={nodes.Object_8.geometry} material={materials['BodyA-material']} skeleton={nodes.Object_8.skeleton} />
          <skinnedMesh geometry={nodes.Object_10.geometry} material={materials['BodyAVco00-material']} skeleton={nodes.Object_10.skeleton} />
          <skinnedMesh geometry={nodes.Object_12.geometry} material={materials['Eye_004-material']} skeleton={nodes.Object_12.skeleton} />
          <skinnedMesh geometry={nodes.Object_14.geometry} material={materials['BodyAVco01-material']} skeleton={nodes.Object_14.skeleton} />
          <skinnedMesh geometry={nodes.Object_16.geometry} material={materials['BodyB-material']} skeleton={nodes.Object_16.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/164.glb')
