/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/167.glb -o models/gltfjsx/regular/167.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/167.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={2.54}>
        <primitive object={nodes.Waist} />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
        <skinnedMesh geometry={nodes.Spinarak_1.geometry} material={materials.Body} skeleton={nodes.Spinarak_1.skeleton} />
        <skinnedMesh geometry={nodes.Spinarak_2.geometry} material={materials.Eye} skeleton={nodes.Spinarak_2.skeleton} />
      </group>
      <skinnedMesh geometry={nodes.Spinarak_BodyA.geometry} material={materials.Body} skeleton={nodes.Spinarak_BodyA.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={2.54} />
      <skinnedMesh geometry={nodes.Spinarak_BodyB.geometry} material={materials.Body} skeleton={nodes.Spinarak_BodyB.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={2.54} />
    </group>
  )
}

useGLTF.preload('/167.glb')
