/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/177.glb -o models/gltfjsx/regular/177.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const { scene } = useGLTF('/177.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group position={[2.753, -0.183, -0.118]} rotation={[Math.PI / 2, 0, 0]}>
        <primitive object={nodes.naty} />
      </group>
      <mesh geometry={nodes.body_0.geometry} material={materials.default3} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.body_1.geometry} material={materials.mat45} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.body_2.geometry} material={materials.mat46} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.leg_l_0.geometry} material={materials._mat57} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.leg_l_1.geometry} material={materials._mat58} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.leg_r_0.geometry} material={materials._mat47} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.leg_r_1.geometry} material={materials._mat48} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.tail_a_0.geometry} material={materials._mat54} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.tail_b_0.geometry} material={materials._mat55} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.tail_c_0.geometry} material={materials._mat56} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.tosaka_0.geometry} material={materials._mat51} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.wing_l_0.geometry} material={materials._mat52} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.wing_l_1.geometry} material={materials._mat53} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.wing_r_0.geometry} material={materials._mat49} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.wing_r_1.geometry} material={materials._mat50} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/177.glb')
