/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/180.glb -o models/gltfjsx/regular/180.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/180.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pm0180_00_00_body_mesh_shape_body_00.geometry} material={materials.body_00} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.pm0180_00_00_body_mesh_shape_body_02.geometry} material={materials.body_02} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.pm0180_00_00_eye_mesh_shape_l_eye.geometry} material={materials['l_eye.009']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.pm0180_00_00_eye_mesh_shape_r_eye.geometry} material={materials['r_eye.009']} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/180.glb')
