/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/183.glb -o models/gltfjsx/regular/183.jsx 
Author: nguyenlouis32 (https://sketchfab.com/nguyenlouis32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/marill-503025b73f774098aa8b42a316e4b4b4
Title: Marill
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/183.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_3.geometry} material={materials.pm0183_00_fi_eye_001} />
          <mesh geometry={nodes.Object_4.geometry} material={materials.pm0183_00_fi_body_001} />
          <mesh geometry={nodes.Object_5.geometry} material={materials.pm0183_00_fi_body_001} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.pm0183_00_fi_eye_001} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/183.glb')
