/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/188.glb -o models/gltfjsx/regular/188.jsx 
Author: nguyenlouis32 (https://sketchfab.com/nguyenlouis32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/skiploom-80bd84594bdc4f5aa86b6289887e9337
Title: Skiploom
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/188.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.PopoccoDh} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.PopoccoEyeDh} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.PopoccoMouthDh} />
      </group>
    </group>
  )
}

useGLTF.preload('/188.glb')
