/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/197.glb -o models/gltfjsx/regular/197.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/197.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={2.54}>
        <group position={[0, 0.382, -0.053]} rotation={[1.623, 0, Math.PI / 2]}>
          <primitive object={nodes.Hips} />
          <primitive object={nodes.Spine1} />
        </group>
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
        <skinnedMesh geometry={nodes.Umbreon_1.geometry} material={materials['Material #92']} skeleton={nodes.Umbreon_1.skeleton} />
        <skinnedMesh geometry={nodes.Umbreon_2.geometry} material={materials['Material #93']} skeleton={nodes.Umbreon_2.skeleton} />
        <skinnedMesh geometry={nodes.Umbreon_3.geometry} material={materials['Material #94']} skeleton={nodes.Umbreon_3.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/197.glb')
