/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/2.glb -o models/gltfjsx/regular/2.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const { scene } = useGLTF('/2.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={2.54}>
        <group position={[0, 0.378, -0.159]} rotation={[1.391, 0, Math.PI / 2]}>
          <primitive object={nodes.Hips} />
          <primitive object={nodes.Spine1} />
        </group>
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
        <skinnedMesh geometry={nodes.Ivysaur_1.geometry} material={materials['Material #46']} skeleton={nodes.Ivysaur_1.skeleton} />
        <skinnedMesh geometry={nodes.Ivysaur_2.geometry} material={materials['Material #47']} skeleton={nodes.Ivysaur_2.skeleton} />
        <skinnedMesh geometry={nodes.Ivysaur_3.geometry} material={materials['Material #48']} skeleton={nodes.Ivysaur_3.skeleton} />
        <skinnedMesh geometry={nodes.Ivysaur_4.geometry} material={materials['Material #49']} skeleton={nodes.Ivysaur_4.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/2.glb')
