/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/201.glb -o models/gltfjsx/regular/201.jsx 
Author: ndalrymp (https://sketchfab.com/ndalrymp)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/unown-f589449bdca6473e901ad868df59e74a
Title: unown
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/shiny/201.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-0.205, 4.601, 0.067]} scale={[0.25, 0.25, 0.5]}>
          <mesh geometry={nodes.pasted__pCylinder3_lambert1_0.geometry} material={materials.lambert1} position={[-0.201, 6.047, 0.02]} rotation={[Math.PI / 2, 0, 0]} scale={[0.2, 0.1, 0.2]} />
        </group>
        <group position={[-0.047, 0, 0]} rotation={[-Math.PI, 0, -Math.PI]}>
          <group position={[-2.391, 0.114, 0]} rotation={[0, 0, -0.564]} scale={[0.8, 1, 1]}>
            <mesh geometry={nodes.pasted__pasted__pasted__pasted__pasted__pCylinder4_lambert1_0.geometry} material={materials.lambert1} position={[0.311, 4.308, 0]} rotation={[0, 0, Math.PI / 2]} scale={[0.2, 0.3, 0.1]} />
          </group>
        </group>
        <mesh geometry={nodes.pCylinder1_lambert1_0.geometry} material={materials.lambert1} position={[0, 5.907, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 0.1, 1]} />
        <mesh geometry={nodes.pCylinder2_lambert1_0.geometry} material={materials.lambert1} position={[0, 5.907, 0.01]} rotation={[Math.PI / 2, 0, 0]} scale={[0.7, 0.1, 0.7]} />
        <mesh geometry={nodes.pCylinder3_lambert1_0.geometry} material={materials.lambert1} position={[-0.201, 6.047, 0.02]} rotation={[Math.PI / 2, 0, 0]} scale={[0.2, 0.1, 0.2]} />
        <mesh geometry={nodes.pCylinder4_lambert1_0.geometry} material={materials.lambert1} position={[0, 4.742, 0]} scale={[0.2, 1, 0.1]} />
        <mesh geometry={nodes.pasted__pCylinder4_lambert1_0.geometry} material={materials.lambert1} position={[0.315, 4.424, 0]} rotation={[0, 0, Math.PI / 2]} scale={[0.2, 0.3, 0.1]} />
        <group position={[-2.391, 0.114, 0]} rotation={[0, 0, -0.564]} scale={[0.8, 1, 1]}>
          <mesh geometry={nodes.pasted__pasted__pasted__pasted__pCylinder4_lambert1_0.geometry} material={materials.lambert1} position={[0.345, 4.326, 0]} rotation={[0, 0, Math.PI / 2]} scale={[0.2, 0.3, 0.1]} />
        </group>
        <mesh geometry={nodes.polySurface1_lambert2_0.geometry} material={materials.lambert2} position={[0.434, 1.348, -0.003]} scale={[0.7, 0.8, 1]} />
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/shiny/201.glb')
