/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/215.glb -o models/gltfjsx/regular/215.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/215.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={2.54}>
        <group position={[0, 0.254, -0.001]} rotation={[-0.098, 0, Math.PI / 2]}>
          <primitive object={nodes.Hips} />
          <primitive object={nodes.Spine1} />
        </group>
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
        <skinnedMesh geometry={nodes.SneaselF_1.geometry} material={materials['Material #35']} skeleton={nodes.SneaselF_1.skeleton} />
        <skinnedMesh geometry={nodes.SneaselF_2.geometry} material={materials['Material #36']} skeleton={nodes.SneaselF_2.skeleton} />
        <skinnedMesh geometry={nodes.SneaselF_3.geometry} material={materials['Material #37']} skeleton={nodes.SneaselF_3.skeleton} />
        <skinnedMesh geometry={nodes.SneaselF_4.geometry} material={materials['Material #38']} skeleton={nodes.SneaselF_4.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/215.glb')
