/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/224.glb -o models/gltfjsx/regular/224.jsx 
Author: nguyenlouis32 (https://sketchfab.com/nguyenlouis32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/octillery-e3236ad2c26b4156b867469dc29e892d
Title: Octillery
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/224.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.OkutankDh} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.OkutankEyeDh} />
      </group>
    </group>
  )
}

useGLTF.preload('/224.glb')
