/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/225.glb -o models/gltfjsx/regular/225.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const { scene } = useGLTF('/225.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={2.54}>
        <group position={[0, 0.281, 0.016]} rotation={[-0.035, 0, Math.PI / 2]}>
          <primitive object={nodes.Hips} />
          <primitive object={nodes.Spine1} />
        </group>
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
        <skinnedMesh geometry={nodes.Delibird_1.geometry} material={materials['Material #10']} skeleton={nodes.Delibird_1.skeleton} />
        <skinnedMesh geometry={nodes.Delibird_2.geometry} material={materials['Material #11']} skeleton={nodes.Delibird_2.skeleton} />
        <skinnedMesh geometry={nodes.Delibird_3.geometry} material={materials['Material #12']} skeleton={nodes.Delibird_3.skeleton} />
        <skinnedMesh geometry={nodes.Delibird_4.geometry} material={materials['Material #13']} skeleton={nodes.Delibird_4.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/225.glb')
