/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/24.glb -o models/gltfjsx/regular/24.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/24.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={2.54}>
        <group position={[0, -0.274, 0.002]} rotation={[0, 0, Math.PI / 2]}>
          <primitive object={nodes.Spine1} />
          <primitive object={nodes.Tail1} />
        </group>
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
        <skinnedMesh geometry={nodes.Arbok_1.geometry} material={materials.Eye} skeleton={nodes.Arbok_1.skeleton} />
        <skinnedMesh geometry={nodes.Arbok_2.geometry} material={materials.BodyA} skeleton={nodes.Arbok_2.skeleton} />
        <skinnedMesh geometry={nodes.Arbok_3.geometry} material={materials.BodyB} skeleton={nodes.Arbok_3.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/24.glb')
