/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/241.glb -o models/gltfjsx/regular/241.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/241.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={2.54}>
        <group position={[0, 0.385, -0.001]} rotation={[0.004, 0, Math.PI / 2]}>
          <primitive object={nodes.Hips} />
          <primitive object={nodes.FeelerA} />
          <primitive object={nodes.Spine2} />
        </group>
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
        <skinnedMesh geometry={nodes.Miltank_1.geometry} material={materials['Material #35']} skeleton={nodes.Miltank_1.skeleton} />
        <skinnedMesh geometry={nodes.Miltank_2.geometry} material={materials['Material #36']} skeleton={nodes.Miltank_2.skeleton} />
        <skinnedMesh geometry={nodes.Miltank_3.geometry} material={materials['Material #37']} skeleton={nodes.Miltank_3.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/241.glb')
