/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/246.glb -o models/gltfjsx/regular/246.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/246.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={2.54}>
        <group position={[0, 0.184, 0]} rotation={[0.052, 0, Math.PI / 2]}>
          <primitive object={nodes.Hips} />
          <primitive object={nodes.Spine} />
        </group>
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
        <skinnedMesh geometry={nodes.Larvitar_1.geometry} material={materials['Material #191']} skeleton={nodes.Larvitar_1.skeleton} />
        <skinnedMesh geometry={nodes.Larvitar_2.geometry} material={materials['Material #192']} skeleton={nodes.Larvitar_2.skeleton} />
        <skinnedMesh geometry={nodes.Larvitar_3.geometry} material={materials['Material #193']} skeleton={nodes.Larvitar_3.skeleton} />
        <skinnedMesh geometry={nodes.Larvitar_4.geometry} material={materials['Material #194']} skeleton={nodes.Larvitar_4.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/246.glb')
