/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/262.glb -o models/gltfjsx/regular/262.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/262.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={2.54}>
        <group position={[0, 0.535, -0.153]} rotation={[1.605, 0, Math.PI / 2]}>
          <primitive object={nodes.Hips} />
          <primitive object={nodes.Spine1} />
        </group>
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
        <skinnedMesh geometry={nodes.Mightyena_1.geometry} material={materials['Material #23']} skeleton={nodes.Mightyena_1.skeleton} />
        <skinnedMesh geometry={nodes.Mightyena_2.geometry} material={materials['Material #24']} skeleton={nodes.Mightyena_2.skeleton} />
        <skinnedMesh geometry={nodes.Mightyena_3.geometry} material={materials['Material #25']} skeleton={nodes.Mightyena_3.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/262.glb')
