/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/270.glb -o models/gltfjsx/regular/270.jsx 
Author: nguyenlouis32 (https://sketchfab.com/nguyenlouis32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lotad-01bd1ad668224adb9c1bcff1addc3e9b
Title: Lotad
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/270.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.HassbohDh} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.HassbohEyeDh} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.HassbohMouthDh} />
      </group>
    </group>
  )
}

useGLTF.preload('/270.glb')
