/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/278.glb -o models/gltfjsx/regular/278.jsx 
Author: nguyenlouis32 (https://sketchfab.com/nguyenlouis32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wingull-329298244fb045a2804a9bdbcee038a6
Title: Wingull
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/278.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.CamomeDh} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.CamomeEyeDh} />
      </group>
    </group>
  )
}

useGLTF.preload('/278.glb')
