/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/280.glb -o models/gltfjsx/regular/280.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const { scene } = useGLTF('/280.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={2.54}>
        <group position={[0, 0.127, 0.011]} rotation={[0, 0, Math.PI / 2]}>
          <primitive object={nodes.Hips} />
          <primitive object={nodes.Spine} />
        </group>
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
        <skinnedMesh geometry={nodes.Ralts_1.geometry} material={materials['Material #35']} skeleton={nodes.Ralts_1.skeleton} />
        <skinnedMesh geometry={nodes.Ralts_2.geometry} material={materials['Material #36']} skeleton={nodes.Ralts_2.skeleton} />
        <skinnedMesh geometry={nodes.Ralts_3.geometry} material={materials['Material #37']} skeleton={nodes.Ralts_3.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/280.glb')
