/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/283.glb -o models/gltfjsx/regular/283.jsx 
Author: nguyenlouis32 (https://sketchfab.com/nguyenlouis32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/surskit-fed3d6ce26034a5692e0d3f07aeeabb6
Title: Surskit
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/283.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI, 1.569, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.AmetamaBodyNl} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.AmetamaEyeNl} />
      </group>
    </group>
  )
}

useGLTF.preload('/283.glb')
