/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/286.glb -o models/gltfjsx/regular/286.jsx 
Author: Nardeol (https://sketchfab.com/Nardeol)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chapignon-fan-art-97c08332304041e6ac198cb7460926f0
Title: Chapignon fan art
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/regular/286.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-1877.482, -155.259, 7846.542]} rotation={[-Math.PI / 2, 0, -3.138]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[390.144, -3458.68, 2801.656]} rotation={[-1.682, 0.025, 2.352]} scale={[1467.516, 1467.516, 1467.517]}>
            <mesh geometry={nodes.Sphere_Material014_0.geometry} material={materials['Material.014']} />
            <mesh geometry={nodes.Sphere_Material003_0.geometry} material={materials['Material.003']} />
            <mesh geometry={nodes.Sphere_Material001_0.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Sphere_Material004_0.geometry} material={materials['Material.004']} />
            <mesh geometry={nodes.Sphere_Material005_0.geometry} material={materials['Material.005']} />
            <mesh geometry={nodes.Sphere_Material_0.geometry} material={materials.Material} />
            <mesh geometry={nodes.Sphere_Material002_0.geometry} material={materials['Material.002']} />
            <mesh geometry={nodes.Sphere_Material007_0.geometry} material={materials['Material.007']} />
            <mesh geometry={nodes.Sphere_Material008_0.geometry} material={materials['Material.008']} />
            <mesh geometry={nodes.Sphere_Material006_0.geometry} material={materials['Material.006']} />
            <mesh geometry={nodes.Sphere_Material010_0.geometry} material={materials['Material.010']} />
            <mesh geometry={nodes.Sphere_Material011_0.geometry} material={materials['Material.011']} />
            <mesh geometry={nodes.Sphere_Material012_0.geometry} material={materials['Material.012']} />
            <mesh geometry={nodes.Sphere_Material013_0.geometry} material={materials['Material.013']} />
            <mesh geometry={nodes.Sphere_Material015_0.geometry} material={materials['Material.015']} />
            <mesh geometry={nodes.Sphere_Material016_0.geometry} material={materials['Material.016']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/regular/286.glb')
