/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/288.glb -o models/gltfjsx/regular/288.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/shiny/288.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <primitive object={nodes.pm0288_00_00} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <primitive object={nodes.pm0288_00_00_1} />
      </group>
      <mesh geometry={nodes.pm0288_00_00_body_mesh_shape_lod2_body_a_00.geometry} material={materials['body_a_00.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.pm0288_00_00_body_mesh_shape_lod2_body_b.geometry} material={materials['body_b.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.pm0288_00_00_eye_mesh_shape_lod2_l_eye.geometry} material={materials['l_eye.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.pm0288_00_00_eye_mesh_shape_lod2_r_eye.geometry} material={materials['r_eye.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Sphere.geometry} material={materials.Black} position={[0.094, 1.199, 0.44]} rotation={[-0.199, 0.48, -0.795]} scale={[-0.02, -0.02, -0.004]} />
      <mesh geometry={nodes.Sphere001.geometry} material={materials.Black} position={[-0.088, 1.199, 0.446]} rotation={[-0.208, -0.554, -0.998]} scale={[-0.02, -0.02, -0.004]} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/shiny/288.glb')
