/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/302.glb -o models/gltfjsx/regular/302.jsx 
Author: JIStone (https://sketchfab.com/JIStone)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sableye-hand-painted-character-42476c16fe3a4036a994424f1912b0ba
Title: Sableye - Hand-painted Character
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/302.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="63796cc275a742dab0abcaed589e6addfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="SableyeMerge001" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="metarig" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="rig" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="Object_7">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_9" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <skinnedMesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials['backup_Material.007']} skeleton={nodes.Object_10.skeleton} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/302.glb')
