/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/303.glb -o models/gltfjsx/regular/303.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const { scene } = useGLTF('/303.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={2.54}>
        <group position={[0, 0.191, -0.002]} rotation={[0, 0, Math.PI / 2]}>
          <primitive object={nodes.Hips} />
          <primitive object={nodes.Spine} />
        </group>
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
        <skinnedMesh geometry={nodes.Mawile_1.geometry} material={materials['Material #229']} skeleton={nodes.Mawile_1.skeleton} />
        <skinnedMesh geometry={nodes.Mawile_2.geometry} material={materials['Material #230']} skeleton={nodes.Mawile_2.skeleton} />
        <skinnedMesh geometry={nodes.Mawile_3.geometry} material={materials['Material #231']} skeleton={nodes.Mawile_3.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/303.glb')
