/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/318.glb -o models/gltfjsx/regular/318.jsx 
Author: nguyenlouis32 (https://sketchfab.com/nguyenlouis32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/carvanha-54aa675a07144da683002dee3ad39eb5
Title: Carvanha
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/318.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.KibanhaDh} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.KibanhaEyeDh} />
      </group>
    </group>
  )
}

useGLTF.preload('/318.glb')
