/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/32.glb -o models/gltfjsx/regular/32.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/32.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={2.54}>
        <group position={[0, 0.209, -0.034]} rotation={[-1.715, 0, -Math.PI / 2]}>
          <primitive object={nodes.Hips} />
          <primitive object={nodes.Spine1} />
        </group>
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
        <skinnedMesh geometry={nodes.NidoranM_1.geometry} material={materials['Material #139']} skeleton={nodes.NidoranM_1.skeleton} />
        <skinnedMesh geometry={nodes.NidoranM_2.geometry} material={materials['Material #140']} skeleton={nodes.NidoranM_2.skeleton} />
        <skinnedMesh geometry={nodes.NidoranM_3.geometry} material={materials['Material #141']} skeleton={nodes.NidoranM_3.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/32.glb')
