/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/328.glb -o models/gltfjsx/regular/328.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/328.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.001}>
        <group scale={1000}>
          <group position={[0, -0.17, 0]}>
            <group position={[-0.081, 0.318, 0.07]} rotation={[0.003, -0.022, -0.048]} scale={0.064}>
              <mesh geometry={nodes.s0413_Thicken_Cartoon_EF9B76_0.geometry} material={materials.Cartoon_EF9B76} position={[-0.01, 0.025, 0.158]} />
            </group>
            <mesh geometry={nodes.s0407_Thicken_Cartoon_FFDECE_0.geometry} material={materials.Cartoon_FFDECE} position={[-0.1, 0.258, 0.019]} rotation={[-1.694, -1.391, -1.499]} scale={0.109} />
            <mesh geometry={nodes.s0408_Cartoon_EF9B76_0.geometry} material={materials.Cartoon_EF9B76} position={[-0.1, 0.258, 0.019]} rotation={[-1.694, -1.391, -1.499]} scale={0.109} />
            <mesh geometry={nodes.s0409_Flat_000000_0.geometry} material={materials.Flat_000000} position={[0, 0.231, 0.089]} rotation={[-0.06, 0.643, -0.225]} scale={0.095} />
            <mesh geometry={nodes.s0410_Thicken_Cartoon_000000_0.geometry} material={materials.Cartoon_000000} position={[0.052, 0.245, 0.128]} rotation={[0.387, 0.216, -1.133]} scale={0.106} />
            <mesh geometry={nodes.s0411_Flat_000000_0.geometry} material={materials.Flat_000000} position={[-0.004, 0.236, 0.089]} rotation={[-0.058, 0.649, -0.226]} scale={0.094} />
            <mesh geometry={nodes.s0412_Thicken_Cartoon_EF9B76_0.geometry} material={materials.Cartoon_EF9B76} position={[-0.001, 0.307, 0.091]} rotation={[0.021, 0.331, -0.051]} scale={0.162} />
            <mesh geometry={nodes.s0415_Thicken_Flat_FFFFFF_0.geometry} material={materials.Flat_FFFFFF} position={[0.059, 0.287, 0.126]} rotation={[0.089, 0.834, -0.061]} scale={0.104} />
            <mesh geometry={nodes.s0416_Cartoon_EF9B76_0.geometry} material={materials.Cartoon_EF9B76} position={[-0.001, 0.228, 0.031]} rotation={[-2.982, -1.276, -2.762]} scale={0.098} />
            <mesh geometry={nodes.s0417_Flat_000000_0.geometry} material={materials.Flat_000000} position={[-0.025, 0.231, 0.023]} rotation={[-3, -1.027, -2.803]} scale={0.109} />
            <mesh geometry={nodes.s0418_Flat_000000_0.geometry} material={materials.Flat_000000} position={[-0.033, 0.239, 0.06]} rotation={[-2.988, -1.045, -2.792]} scale={0.103} />
            <mesh geometry={nodes.s0419_Thicken_Cartoon_000000_0.geometry} material={materials.Cartoon_000000} position={[-0.057, 0.253, 0.088]} rotation={[1.089, -0.464, 1.375]} scale={0.106} />
            <mesh geometry={nodes.s0420_Thicken_Flat_FFFFFF_0.geometry} material={materials.Flat_FFFFFF} position={[-0.068, 0.293, 0.113]} rotation={[0.011, -1.053, -0.059]} scale={0.104} />
            <mesh geometry={nodes.s0421_Cartoon_EF9B76_0.geometry} material={materials.Cartoon_EF9B76} position={[-0.009, 0.235, 0.055]} rotation={[-0.518, -1.25, -0.37]} scale={0.098} />
            <mesh geometry={nodes.s0422_Cartoon_EF9B76_0.geometry} material={materials.Cartoon_EF9B76} position={[0.015, 0.226, 0.036]} rotation={[0.695, 1.251, -0.891]} scale={0.098} />
            <mesh geometry={nodes.s0423_Flat_000000_0.geometry} material={materials.Flat_000000} position={[0.04, 0.223, 0.041]} rotation={[1.578, 1.404, -1.73]} scale={0.109} />
            <mesh geometry={nodes.s0424_Cartoon_EF9B76_0.geometry} material={materials.Cartoon_EF9B76} position={[0.011, 0.232, 0.061]} rotation={[0.077, 0.753, -0.307]} scale={0.098} />
            <mesh geometry={nodes.s0425_Flat_000000_0.geometry} material={materials.Flat_000000} position={[0.03, 0.231, 0.078]} rotation={[1.467, 1.406, -1.62]} scale={0.103} />
            <mesh geometry={nodes.s0426_Thicken_Cartoon_000000_0.geometry} material={materials.Cartoon_000000} position={[0.051, 0.247, 0.101]} rotation={[1.032, 0.272, -1.218]} scale={0.106} />
            <mesh geometry={nodes.s0427_Thicken_Flat_FFFFFF_0.geometry} material={materials.Flat_FFFFFF} position={[0.06, 0.287, 0.127]} rotation={[0.123, 0.825, -0.078]} scale={0.104} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/328.glb')
