/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/329.glb -o models/gltfjsx/regular/329.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/329.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.001}>
        <group scale={1000}>
          <mesh geometry={nodes.s0206_Thicken_Cartoon_2F2F2F_0.geometry} material={materials.Cartoon_2F2F2F} position={[-0.211, 0.211, 0.019]} rotation={[-2.946, 0.018, 2.916]} scale={0.022} />
          <mesh geometry={nodes.s0207_Thicken_Glossy_5EBB6C_0.geometry} material={materials.Glossy_5EBB6C} position={[-0.21, 0.215, 0.017]} rotation={[-2.946, 0.018, 2.916]} scale={0.019} />
          <mesh geometry={nodes.s0208_Cartoon_F7F7F7_0.geometry} material={materials.Cartoon_F7F7F7} position={[-0.258, 0.203, 0.057]} rotation={[2.521, 1.146, 2.904]} scale={0.01} />
          <mesh geometry={nodes.s0209_Flat_000000_0.geometry} material={materials.Flat_000000} position={[-0.272, 0.198, 0.036]} rotation={[-0.621, 1.376, 0.448]} scale={0.351} />
          <mesh geometry={nodes.s0210_Thicken_Glossy_5EBB6C_0.geometry} material={materials.Glossy_5EBB6C} position={[-0.197, 0.214, 0.057]} rotation={[2.985, 1.03, 2.687]} scale={0.019} />
          <mesh geometry={nodes.s0211_Cartoon_EDEDA3_0.geometry} material={materials.Cartoon_EDEDA3} position={[-0.328, 0.19, 0.091]} rotation={[0.028, -1.183, 0.224]} scale={0.016} />
          <mesh geometry={nodes.s0212_Cartoon_F7F7F7_0.geometry} material={materials.Cartoon_F7F7F7} position={[-0.275, 0.202, 0.062]} rotation={[0.814, -1.166, 1.585]} scale={0.01} />
          <mesh geometry={nodes.s0213_Cartoon_EDEDA3_0.geometry} material={materials.Cartoon_EDEDA3} position={[-0.225, 0.198, 0.115]} rotation={[-0.14, 0.134, 0.088]} scale={0.03} />
          <mesh geometry={nodes.s0214_Flat_000000_0.geometry} material={materials.Flat_000000} position={[-0.253, 0.172, 0.015]} rotation={[-0.227, 0.508, 0.096]} scale={0.401} />
          <mesh geometry={nodes.s0215_Thicken_Cartoon_2F2F2F_0.geometry} material={materials.Cartoon_2F2F2F} position={[-0.2, 0.21, 0.059]} rotation={[2.985, 1.03, 2.687]} scale={0.022} />
          <mesh geometry={nodes.s0216_Flat_000000_0.geometry} material={materials.Flat_000000} position={[-0.26, 0.201, 0.052]} rotation={[-0.256, 0.731, 0.113]} scale={0.17} />
          <mesh geometry={nodes.s0217_Thicken_Glossy_5EBB6C_0.geometry} material={materials.Glossy_5EBB6C} position={[-0.345, 0.212, 0.061]} rotation={[-2.916, -0.654, -2.827]} scale={0.019} />
          <mesh geometry={nodes.s0218_Cartoon_2F2F2F_0.geometry} material={materials.Cartoon_2F2F2F} position={[-0.245, 0.166, 0.059]} rotation={[-0.086, -0.843, 0.098]} scale={0.333} />
          <mesh geometry={nodes.s0219_Cartoon_2F2F2F_0.geometry} material={materials.Cartoon_2F2F2F} position={[-0.226, 0.116, 0.074]} rotation={[0.232, -0.764, 0.124]} scale={0.23} />
          <mesh geometry={nodes.s0220_Thicken_Cartoon_2F2F2F_0.geometry} material={materials.Cartoon_2F2F2F} position={[-0.342, 0.207, 0.062]} rotation={[-2.916, -0.654, -2.827]} scale={0.022} />
          <mesh geometry={nodes.s0221_Cartoon_2F2F2F_0.geometry} material={materials.Cartoon_2F2F2F} position={[-0.289, 0.165, 0.073]} rotation={[-0.859, 1.436, 0.712]} scale={0.333} />
          <mesh geometry={nodes.s0222_Thicken_Cartoon_2F2F2F_0.geometry} material={materials.Cartoon_2F2F2F} position={[-0.345, 0.177, -0.105]} rotation={[-2.454, -0.678, -2.648]} scale={0.009} />
          <mesh geometry={nodes.s0223_Flat_000000_0.geometry} material={materials.Flat_000000} position={[-0.244, 0.189, 0.051]} rotation={[-0.189, 0.11, 0.085]} scale={0.189} />
          <mesh geometry={nodes.s0224_Thicken_Glossy_5EBB6C_0.geometry} material={materials.Glossy_5EBB6C} position={[-0.346, 0.179, -0.105]} rotation={[-2.454, -0.678, -2.648]} scale={0.008} />
          <mesh geometry={nodes.s0225_Thicken_Cartoon_2F2F2F_0.geometry} material={materials.Cartoon_2F2F2F} position={[-0.327, 0.207, 0.101]} rotation={[0.897, -1.407, 1.469]} scale={0.022} />
          <mesh geometry={nodes.s0226_Cartoon_2F2F2F_0.geometry} material={materials.Cartoon_2F2F2F} position={[-0.254, 0.16, 0.029]} rotation={[-0.054, -0.172, 0.121]} scale={0.333} />
          <mesh geometry={nodes.s0227_Cartoon_2F2F2F_0.geometry} material={materials.Cartoon_2F2F2F} position={[-0.293, 0.114, 0.096]} rotation={[0.69, 1.376, -0.621]} scale={0.23} />
          <mesh geometry={nodes.s0228_Thicken_Glossy_5EBB6C_0.geometry} material={materials.Glossy_5EBB6C} position={[-0.331, 0.211, 0.102]} rotation={[0.897, -1.407, 1.469]} scale={0.019} />
          <mesh geometry={nodes.s0229_Cartoon_2F2F2F_0.geometry} material={materials.Cartoon_2F2F2F} position={[-0.231, 0.109, 0.028]} rotation={[0.175, -0.11, -0.051]} scale={0.23} />
          <mesh geometry={nodes.s0230_Cartoon_2F2F2F_0.geometry} material={materials.Cartoon_2F2F2F} position={[-0.316, 0.107, 0.056]} rotation={[0.21, 0.747, -0.029]} scale={0.23} />
          <mesh geometry={nodes.s0231_Cartoon_2F2F2F_0.geometry} material={materials.Cartoon_2F2F2F} position={[-0.299, 0.159, 0.044]} rotation={[-0.109, 0.806, -0.009]} scale={0.333} />
          <mesh geometry={nodes.s0232_Thicken_Glossy_5EBB6C_0.geometry} material={materials.Glossy_5EBB6C} position={[-0.306, 0.18, -0.118]} rotation={[-2.598, 0.122, 3]} scale={0.008} />
          <mesh geometry={nodes.s0233_Thicken_Cartoon_2F2F2F_0.geometry} material={materials.Cartoon_2F2F2F} position={[-0.307, 0.178, -0.118]} rotation={[-2.598, 0.122, 3]} scale={0.009} />
          <mesh geometry={nodes.s0234_Thicken_Cartoon_EDEDA3_0.geometry} material={materials.Cartoon_EDEDA3} position={[-0.275, 0.194, 0.138]} rotation={[0.56, -1.274, 0.904]} scale={0.017} />
          <mesh geometry={nodes.s0235_Thicken_Glossy_7CFF6A73_0.geometry} material={materials.Glossy_7CFF6A73} position={[-0.272, 0.193, 0.135]} rotation={[1.419, -0.062, 2.283]} scale={0.02} />
          <mesh geometry={nodes.s0236_Cartoon_FFF4C7_0.geometry} material={materials.Cartoon_FFF4C7} position={[-0.272, 0.176, 0.13]} rotation={[1.204, -0.669, 0.189]} scale={0.009} />
          <mesh geometry={nodes.s0237_Cartoon_000000_0.geometry} material={materials.Cartoon_000000} position={[-0.275, 0.193, 0.138]} rotation={[0.56, -1.274, 0.904]} scale={0.017} />
          <mesh geometry={nodes.s0238_Cartoon_F8C1FF_0.geometry} material={materials.Cartoon_F8C1FF} position={[-0.239, 0.168, 0.109]} rotation={[-2.978, 1.325, 2.789]} scale={0.03} />
          <mesh geometry={nodes.s0239_Thicken_Glossy_7CFF6A73_0.geometry} material={materials.Glossy_7CFF6A73} position={[-0.224, 0.194, 0.119]} rotation={[1.5, 0.186, -2.917]} scale={0.02} />
          <mesh geometry={nodes.s0240_Cartoon_FFF4C7_0.geometry} material={materials.Cartoon_FFF4C7} position={[-0.226, 0.177, 0.115]} rotation={[1.789, 0.774, -1.045]} scale={0.009} />
          <mesh geometry={nodes.s0241_Thicken_Cartoon_EDEDA3_0.geometry} material={materials.Cartoon_EDEDA3} position={[-0.22, 0.195, 0.119]} rotation={[2.861, 1.172, 3.035]} scale={0.017} />
          <mesh geometry={nodes.s0242_Cartoon_000000_0.geometry} material={materials.Cartoon_000000} position={[-0.22, 0.195, 0.12]} rotation={[2.861, 1.172, 3.035]} scale={0.017} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/329.glb')
