/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/334.glb -o models/gltfjsx/regular/334.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const { scene } = useGLTF('/334.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <primitive object={nodes.root} />
        <skinnedMesh geometry={nodes.chirutarisu_00_0_0_node.geometry} material={materials.body_mat} skeleton={nodes.chirutarisu_00_0_0_node.skeleton} />
        <skinnedMesh geometry={nodes.chirutarisu_00_1_0_node.geometry} material={materials.eye_mat} skeleton={nodes.chirutarisu_00_1_0_node.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/334.glb')
