/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/347.glb -o models/gltfjsx/regular/347.jsx 
Author: nguyenlouis32 (https://sketchfab.com/nguyenlouis32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/anorith-29fbdd7c35da4d288ef4eca8ad1dc724
Title: Anorith
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/347.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_3.geometry} material={materials.eye_mat} />
          <mesh geometry={nodes.Object_4.geometry} material={materials.eye_mat_0} />
          <mesh geometry={nodes.Object_5.geometry} material={materials.body_mat} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.body_mat_0} />
          <mesh geometry={nodes.Object_7.geometry} material={materials.mouth_mat} />
          <mesh geometry={nodes.Object_8.geometry} material={materials.mouth_mat} />
          <mesh geometry={nodes.Object_9.geometry} material={materials.body_mat_0} />
          <mesh geometry={nodes.Object_10.geometry} material={materials.body_mat} />
          <mesh geometry={nodes.Object_11.geometry} material={materials.eye_mat_0} />
          <mesh geometry={nodes.Object_12.geometry} material={materials.eye_mat} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/347.glb')
