/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/354.glb -o models/gltfjsx/regular/354.jsx 
Author: nguyenlouis32 (https://sketchfab.com/nguyenlouis32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/banette-63189a12fa124202b31a62f003db8166
Title: Banette
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/354.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, -0.001, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_4.geometry} material={materials.assets_textures_pm0354_00_Body1_png} />
          <mesh geometry={nodes.Object_5.geometry} material={materials.assets_textures_pm0354_00_Eye1_png} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.assets_textures_pm0354_00_Eye1_png} />
          <mesh geometry={nodes.Object_7.geometry} material={materials.assets_textures_pm0354_00_Body1_png} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/354.glb')
