/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/360.glb -o models/gltfjsx/regular/360.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/360.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_6__BodyVco01_.geometry} material={materials.BodyVco01} />
      <mesh geometry={nodes.Mesh_5__Body01_.geometry} material={materials.Body01} />
      <mesh geometry={nodes.Mesh_4__Body02_.geometry} material={materials.Body02} />
      <mesh geometry={nodes.Mesh_3__BodyVco00_.geometry} material={materials.BodyVco00} />
      <mesh geometry={nodes.Mesh_2__Eye_.geometry} material={materials.Eye} />
      <mesh geometry={nodes.Mesh_1__Body00_.geometry} material={materials.Body00} />
    </group>
  )
}

useGLTF.preload('/360.glb')
