/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/369.glb -o models/gltfjsx/regular/369.jsx 
Author: juliocesar012 (https://sketchfab.com/jsuliocesar012)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/relicanth-3168412740ce4b38877a31a82ea92b6e
Title: Relicanth
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/369.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI, -Math.PI / 2, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes._rootJoint} />
          <skinnedMesh geometry={nodes.Object_6.geometry} material={materials['assets_textures_pm0369_00_Body1-material']} skeleton={nodes.Object_6.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/369.glb')
