/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/379.glb -o models/gltfjsx/regular/379.jsx 
Author: Ulrik_Selvik (https://sketchfab.com/Nemi66)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/registeel-47c889ccde5f4d6da071baffbd327859
Title: Registeel
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/379.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[46.415, 212.116, -4.097]} rotation={[-1.906, -0.798, -1.537]} scale={[9.79, 9.78, 9.514]}>
          <mesh geometry={nodes.Registeel_Material002_0.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.Registeel_Material001_0.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Registeel_Material003_0.geometry} material={materials['Material.003']} />
          <mesh geometry={nodes.Registeel_Material009_0.geometry} material={materials['Material.009']} />
        </group>
        <mesh geometry={nodes.Cylinder002_Material013_0.geometry} material={materials['Material.013']} position={[0, 19.33, -3.751]} rotation={[-Math.PI / 2, 0, 0]} scale={[160.172, 160.172, 24.316]} />
      </group>
    </group>
  )
}

useGLTF.preload('/379.glb')
