/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/387.glb -o models/gltfjsx/regular/387.jsx 
Author: nguyenlouis32 (https://sketchfab.com/nguyenlouis32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/turtwig-3dfd41152275450c923438e8e783ad91
Title: Turtwig
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/387.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.NaetleDh} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.NaetleEyeDh} />
      </group>
    </group>
  )
}

useGLTF.preload('/387.glb')
