/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/389.glb -o models/gltfjsx/regular/389.jsx 
Author: nguyenlouis32 (https://sketchfab.com/nguyenlouis32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/torterra-7af77f999bc5406e82068fd3eb9b4836
Title: Torterra
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/389.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.DodaitoseDh} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.DodaitoseEyeDh} />
      </group>
    </group>
  )
}

useGLTF.preload('/389.glb')
