/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/390.glb -o models/gltfjsx/regular/390.jsx 
Author: nguyenlouis32 (https://sketchfab.com/nguyenlouis32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chimchar-2c65fbaec12344d687a2cbe47f04a351
Title: Chimchar
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/390.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.HikozaruDh} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.HikozaruEyeDh} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.HikozaruMouthDh} />
      </group>
    </group>
  )
}

useGLTF.preload('/390.glb')
