/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/396.glb -o models/gltfjsx/regular/396.jsx 
Author: nguyenlouis32 (https://sketchfab.com/nguyenlouis32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/starly-e87f1f1754644ecea5ab52e015e93b83
Title: Starly
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/396.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.MukkuruDh} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.MukkuruEyeDh} />
      </group>
    </group>
  )
}

useGLTF.preload('/396.glb')
