/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/398.glb -o models/gltfjsx/regular/398.jsx 
Author: nguyenlouis32 (https://sketchfab.com/nguyenlouis32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/staraptor-3b75c76157aa41b4abcda00beba9d6c6
Title: Staraptor
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/398.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 1.57, Math.PI / 2]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.MukuhawkDh} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.MukuhawkEyeDh} />
      </group>
    </group>
  )
}

useGLTF.preload('/398.glb')
