/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/40.glb -o models/gltfjsx/regular/40.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/40.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={2.54}>
        <group position={[0, 0.445, -0.021]} rotation={[0, 0, Math.PI / 2]}>
          <primitive object={nodes['004_Hips']} />
          <primitive object={nodes['016_Spine']} />
        </group>
      </group>
      <group scale={2.54}>
        <skinnedMesh geometry={nodes.Wigglytuff_1.geometry} material={materials.Mouth} skeleton={nodes.Wigglytuff_1.skeleton} />
        <skinnedMesh geometry={nodes.Wigglytuff_2.geometry} material={materials.Body} skeleton={nodes.Wigglytuff_2.skeleton} />
        <skinnedMesh geometry={nodes.Wigglytuff_3.geometry} material={materials.Eye} skeleton={nodes.Wigglytuff_3.skeleton} />
        <skinnedMesh geometry={nodes.Wigglytuff_4.geometry} material={materials.BodyVco} skeleton={nodes.Wigglytuff_4.skeleton} />
        <skinnedMesh geometry={nodes.Wigglytuff_5.geometry} material={materials.LIris} skeleton={nodes.Wigglytuff_5.skeleton} />
        <skinnedMesh geometry={nodes.Wigglytuff_6.geometry} material={materials.RIris} skeleton={nodes.Wigglytuff_6.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/40.glb')
