/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/409.glb -o models/gltfjsx/regular/409.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/409.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={2.54}>
        <group position={[0, 0.691, -0.023]} rotation={[0.734, 0, Math.PI / 2]}>
          <primitive object={nodes.Hips} />
          <primitive object={nodes.Spine} />
        </group>
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
        <skinnedMesh geometry={nodes.Rampardos_1.geometry} material={materials['Material #49']} skeleton={nodes.Rampardos_1.skeleton} />
        <skinnedMesh geometry={nodes.Rampardos_2.geometry} material={materials['Material #50']} skeleton={nodes.Rampardos_2.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/409.glb')
