/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/416.glb -o models/gltfjsx/regular/416.jsx 
Author: nguyenlouis32 (https://sketchfab.com/nguyenlouis32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/vespiquen-ebbba289bcec471baff91a421e1a55cc
Title: Vespiquen
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const { scene } = useGLTF('/416.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes._rootJoint} />
          <skinnedMesh geometry={nodes.Object_6.geometry} material={materials['assets_textures_pm0416_00_BodyA1-material_001-material']} skeleton={nodes.Object_6.skeleton} />
          <skinnedMesh geometry={nodes.Object_8.geometry} material={materials['assets_textures_pm0416_00_BodyC1-material_001-material']} skeleton={nodes.Object_8.skeleton} />
          <skinnedMesh geometry={nodes.Object_10.geometry} material={materials['assets_textures_pm0416_00_BodyB1-material_001-material']} skeleton={nodes.Object_10.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/416.glb')
