/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/419.glb -o models/gltfjsx/regular/419.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/419.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={2.54}>
        <group position={[0, 0.348, -0.037]} rotation={[-0.015, 0, Math.PI / 2]}>
          <primitive object={nodes.Hips} />
          <primitive object={nodes.Spine1} />
        </group>
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
        <skinnedMesh geometry={nodes.FloatzelF_1.geometry} material={materials['Material #164']} skeleton={nodes.FloatzelF_1.skeleton} />
        <skinnedMesh geometry={nodes.FloatzelF_2.geometry} material={materials['Material #165']} skeleton={nodes.FloatzelF_2.skeleton} />
        <skinnedMesh geometry={nodes.FloatzelF_3.geometry} material={materials['Material #166']} skeleton={nodes.FloatzelF_3.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/419.glb')
