/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/42.glb -o models/gltfjsx/regular/42.jsx 
Author: nguyenlouis32 (https://sketchfab.com/nguyenlouis32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/golbat-5e04c38c79dd4b85a88fe997b70abc8d
Title: Golbat
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/42.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.GolbatDh} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.GolbatEyeDh} />
      </group>
    </group>
  )
}

useGLTF.preload('/42.glb')
