/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/426.glb -o models/gltfjsx/regular/426.jsx 
Author: nguyenlouis32 (https://sketchfab.com/nguyenlouis32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/drifblim-0090bfa910964e348ab651d012d7e60c
Title: Drifblim
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/426.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.FuwarideDh} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.FuwarideEyeDh} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.FuwarideMouthDh} />
      </group>
    </group>
  )
}

useGLTF.preload('/426.glb')
