/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/44.glb -o models/gltfjsx/regular/44.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/44.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={2.54}>
        <primitive object={nodes['003_Waist']} />
      </group>
      <group scale={2.54}>
        <skinnedMesh geometry={nodes.Gloom_1.geometry} material={materials.BodyA_00} skeleton={nodes.Gloom_1.skeleton} />
        <skinnedMesh geometry={nodes.Gloom_2.geometry} material={materials.Eye} skeleton={nodes.Gloom_2.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/44.glb')
