/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/442.glb -o models/gltfjsx/regular/442.jsx 
Author: Forsaken AR Official (https://sketchfab.com/FNAF_AR_Official)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/nintendo-switch-pokemon-scarlet-violet-0442-fa5c0143b30c4d1b838dbfe90dfb1479
Title: Nintendo Switch - Pokemon Scarlet Violet - 0442
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/442.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.body_a_00} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.body_a_01} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.body_b_00} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.body_b_01} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.body_b_02} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.body_b_03} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.body_a_02} />
      </group>
    </group>
  )
}

useGLTF.preload('/442.glb')
