/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/443.glb -o models/gltfjsx/regular/443.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const { scene } = useGLTF('/443.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={2.54}>
        <group position={[0, 0.267, -0.087]} rotation={[0.147, 0, Math.PI / 2]}>
          <primitive object={nodes.Hips} />
          <primitive object={nodes.Spine} />
        </group>
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
        <skinnedMesh geometry={nodes.GibleF_1.geometry} material={materials['Material #35']} skeleton={nodes.GibleF_1.skeleton} />
        <skinnedMesh geometry={nodes.GibleF_2.geometry} material={materials['Material #36']} skeleton={nodes.GibleF_2.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/443.glb')
