/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/453.glb -o models/gltfjsx/regular/453.jsx 
Author: nguyenlouis32 (https://sketchfab.com/nguyenlouis32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/croagunk-6206cad6234e4a5f82d16496e1bd7d64
Title: Croagunk
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/453.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.GureggruDh} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.GureggruEyeDh} />
      </group>
    </group>
  )
}

useGLTF.preload('/453.glb')
