/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/458.glb -o models/gltfjsx/regular/458.jsx 
Author: nguyenlouis32 (https://sketchfab.com/nguyenlouis32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mantyke-90f4b1db0337412bbe40b4bdbf957a08
Title: Mantyke
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/458.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_3.geometry} material={materials.body_mat} />
          <mesh geometry={nodes.Object_4.geometry} material={materials.mouth_mat} />
          <mesh geometry={nodes.Object_5.geometry} material={materials.eye_mat} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.eye_mat} />
          <mesh geometry={nodes.Object_7.geometry} material={materials.mouth_mat} />
          <mesh geometry={nodes.Object_8.geometry} material={materials.body_mat} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/458.glb')
