/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/46.glb -o models/gltfjsx/regular/46.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const { scene } = useGLTF('/46.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={2.54}>
        <primitive object={nodes['005_Spine']} />
      </group>
      <group scale={2.54}>
        <skinnedMesh geometry={nodes.Paras_1.geometry} material={materials.BodyASpc00} skeleton={nodes.Paras_1.skeleton} />
        <skinnedMesh geometry={nodes.Paras_2.geometry} material={materials.BodyB} skeleton={nodes.Paras_2.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/46.glb')
