/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/462.glb -o models/gltfjsx/regular/462.jsx 
Author: ijackprovostjr (https://sketchfab.com/ijackprovostjr)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pokemon-sv-magnezone-f51f083f49124f3994be3482faeccf64
Title: Pokemon S&V Magnezone
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/462.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={2.508}>
        <primitive object={nodes.GLTF_created_0_rootJoint} />
        <skinnedMesh geometry={nodes.Object_7.geometry} material={materials.body_a} skeleton={nodes.Object_7.skeleton} />
        <skinnedMesh geometry={nodes.Object_9.geometry} material={materials.body_b_00} skeleton={nodes.Object_9.skeleton} />
        <skinnedMesh geometry={nodes.Object_11.geometry} material={materials.body_b_01} skeleton={nodes.Object_11.skeleton} />
        <skinnedMesh geometry={nodes.Object_13.geometry} material={materials.eye_00} skeleton={nodes.Object_13.skeleton} />
        <skinnedMesh geometry={nodes.Object_15.geometry} material={materials.l_eye} skeleton={nodes.Object_15.skeleton} />
        <skinnedMesh geometry={nodes.Object_17.geometry} material={materials.r_eye} skeleton={nodes.Object_17.skeleton} />
        <skinnedMesh geometry={nodes.Object_19.geometry} material={materials.eye_01} skeleton={nodes.Object_19.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/462.glb')
