/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/467.glb -o models/gltfjsx/regular/467.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/467.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, 1.57, -Math.PI]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.BooburnCDh} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.BooburnDh} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.BooburnEyeDh} />
      </group>
    </group>
  )
}

useGLTF.preload('/467.glb')
