/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/475.glb -o models/gltfjsx/regular/475.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/mega/475.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={2.54}>
        <group position={[0, 0.91, 0.001]} rotation={[0.017, 0, Math.PI / 2]}>
          <group rotation={[0, 0, -Math.PI]}>
            <primitive object={nodes.Feeler} />
            <primitive object={nodes.LThigh} />
            <primitive object={nodes.RThigh} />
          </group>
          <primitive object={nodes.Spine1} />
        </group>
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
        <skinnedMesh geometry={nodes.Gallade_1.geometry} material={materials['Material #110']} skeleton={nodes.Gallade_1.skeleton} />
        <skinnedMesh geometry={nodes.Gallade_2.geometry} material={materials['Material #111']} skeleton={nodes.Gallade_2.skeleton} />
        <skinnedMesh geometry={nodes.Gallade_3.geometry} material={materials['Material #112']} skeleton={nodes.Gallade_3.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/mega/475.glb')
