/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/48.glb -o models/gltfjsx/regular/48.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const { scene } = useGLTF('/48.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={2.54}>
        <group position={[0, 0.446, -0.03]} rotation={[0, 0, Math.PI / 2]}>
          <primitive object={nodes['004_Head']} />
          <primitive object={nodes['059_Hips']} />
        </group>
      </group>
      <group scale={2.54}>
        <skinnedMesh geometry={nodes.Venonat_1.geometry} material={materials.BodyABuffron_HairVco} skeleton={nodes.Venonat_1.skeleton} />
        <skinnedMesh geometry={nodes.Venonat_2.geometry} material={materials.Bug} skeleton={nodes.Venonat_2.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/48.glb')
