/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/49.glb -o models/gltfjsx/regular/49.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/49.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={2.54}>
        <primitive object={nodes['003_Waist']} />
      </group>
      <group scale={2.54}>
        <skinnedMesh geometry={nodes.Venomoth_1.geometry} material={materials.BodyA02} skeleton={nodes.Venomoth_1.skeleton} />
        <skinnedMesh geometry={nodes.Venomoth_2.geometry} material={materials.BodyBKurumiruVco} skeleton={nodes.Venomoth_2.skeleton} />
        <skinnedMesh geometry={nodes.Venomoth_3.geometry} material={materials.BodyCNon} skeleton={nodes.Venomoth_3.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/49.glb')
