/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/492.glb -o models/gltfjsx/regular/492.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/492.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.body_skin_2800_0.geometry} material={materials.miishie_eye} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.body_skin_2800_1.geometry} material={materials.miishie_kuti} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.body_skin_2800_2.geometry} material={materials.miishie_bright1} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.body_skin_2800_3.geometry} material={materials.miishie_mat1} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.flower_a_2800_0.geometry} material={materials.miishie_bright} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.flower_a_2800_1.geometry} material={materials.miishie_mat} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.flower_b_2800_0.geometry} material={materials.miishie_bright0} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.flower_b_2800_1.geometry} material={materials.miishie_mat0} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.flower_c_2800_0.geometry} material={materials.miishie_bright1} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.flower_c_2800_1.geometry} material={materials.miishie_mat1} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.flower_d_2800_0.geometry} material={materials.miishie_bright1} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.flower_d_2800_1.geometry} material={materials.miishie_mat1} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.flower_e_2800_0.geometry} material={materials.miishie_bright1} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.flower_e_2800_1.geometry} material={materials.miishie_mat1} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/492.glb')
