/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/501.glb -o models/gltfjsx/regular/501.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/501.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.589, -2.646, 2.694]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.397, 1.458, 2.002]}>
        <mesh geometry={nodes['Box002_Material_#116_0'].geometry} material={materials.Material_116} />
        <mesh geometry={nodes['Box002_Material_#140_0'].geometry} material={materials.Material_140} />
        <mesh geometry={nodes['Box002_Material_#186_0'].geometry} material={materials.Material_186} />
        <mesh geometry={nodes['Box002_Material_#210_0'].geometry} material={materials.Material_210} />
        <mesh geometry={nodes['Box002_Material_#223_0'].geometry} material={materials.Material_223} />
        <mesh geometry={nodes['Box002_Material_#26_0'].geometry} material={materials.Material_26} />
        <mesh geometry={nodes['Box002_Material_#27_0'].geometry} material={materials.Material_27} />
      </group>
    </group>
  )
}

useGLTF.preload('/501.glb')
