/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/502.glb -o models/gltfjsx/regular/502.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/regular/502.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.046, 0]} rotation={[-0.008, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
            <primitive object={nodes._rootJoint} />
            <skinnedMesh geometry={nodes.Object_54.geometry} material={materials.Material__180} skeleton={nodes.Object_54.skeleton} />
            <skinnedMesh geometry={nodes.Object_56.geometry} material={materials.Material__180} skeleton={nodes.Object_56.skeleton} />
            <skinnedMesh geometry={nodes.Object_60.geometry} material={materials.Material__167} skeleton={nodes.Object_60.skeleton} />
            <skinnedMesh geometry={nodes.Object_61.geometry} material={materials.Material__168} skeleton={nodes.Object_61.skeleton} />
            <skinnedMesh geometry={nodes.Object_62.geometry} material={materials.Material__169} skeleton={nodes.Object_62.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/regular/502.glb')
