/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/503.glb -o models/gltfjsx/regular/503.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/503.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group position={[0.454, 1.199, 0.02]} rotation={[-0.101, 0, 3.01]}>
        <group scale={2.54}>
          <group position={[0, 0.535, -0.078]} rotation={[1.465, 0, Math.PI / 2]}>
            <primitive object={nodes.Hips} />
            <primitive object={nodes.Spine1} />
            <skinnedMesh geometry={nodes.Samurott_LSwordSheathed.geometry} material={materials.BodyB} skeleton={nodes.Samurott_LSwordSheathed.skeleton} />
            <skinnedMesh geometry={nodes.Samurott_RSwordSheathed.geometry} material={materials.BodyB} skeleton={nodes.Samurott_RSwordSheathed.skeleton} />
            <skinnedMesh geometry={nodes.Samurott_1.geometry} material={materials.Eye} skeleton={nodes.Samurott_1.skeleton} />
            <skinnedMesh geometry={nodes.Samurott_2.geometry} material={materials.BodyA} skeleton={nodes.Samurott_2.skeleton} />
            <skinnedMesh geometry={nodes.Samurott_3.geometry} material={materials.BodyB} skeleton={nodes.Samurott_3.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/503.glb')
