/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/505.glb -o models/gltfjsx/regular/505.jsx 
Author: nguyenlouis32 (https://sketchfab.com/nguyenlouis32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/watchog-7727e46ab3c043549fa7930c8518cbe4
Title: Watchog
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/505.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.MiruhogBodyNl} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.MiruhogEyeNl} />
      </group>
    </group>
  )
}

useGLTF.preload('/505.glb')
