/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/507.glb -o models/gltfjsx/regular/507.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const { scene } = useGLTF('/507.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={2.54}>
        <group position={[0, 0.379, -0.116]} rotation={[1.55, 0, Math.PI / 2]}>
          <primitive object={nodes.Hips} />
          <primitive object={nodes.Spine1} />
        </group>
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
        <skinnedMesh geometry={nodes.Herdier_1.geometry} material={materials['Material #118']} skeleton={nodes.Herdier_1.skeleton} />
        <skinnedMesh geometry={nodes.Herdier_2.geometry} material={materials['Material #119']} skeleton={nodes.Herdier_2.skeleton} />
        <skinnedMesh geometry={nodes.Herdier_3.geometry} material={materials['Material #120']} skeleton={nodes.Herdier_3.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/507.glb')
