/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/509.glb -o models/gltfjsx/regular/509.jsx 
Author: seth the yutyrannus (https://sketchfab.com/slang107123456789)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/purrloin-9f3e020ee81b4925b3d26d43d88ed16b
Title: Purrloin
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const { scene } = useGLTF('/509.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <group rotation={[-Math.PI, 0, 0]} scale={0.01}>
          <group scale={100}>
            <primitive object={nodes._rootJoint} />
            <skinnedMesh geometry={nodes.Object_112.geometry} material={materials.material} skeleton={nodes.Object_112.skeleton} />
            <skinnedMesh geometry={nodes.Object_113.geometry} material={materials.material_1} skeleton={nodes.Object_113.skeleton} />
            <skinnedMesh geometry={nodes.Object_114.geometry} material={materials.material_2} skeleton={nodes.Object_114.skeleton} />
            <skinnedMesh geometry={nodes.Object_115.geometry} material={materials.material_3} skeleton={nodes.Object_115.skeleton} />
            <skinnedMesh geometry={nodes.Object_116.geometry} material={materials.material_4} skeleton={nodes.Object_116.skeleton} />
            <skinnedMesh geometry={nodes.Object_117.geometry} material={materials.material_5} skeleton={nodes.Object_117.skeleton} />
            <skinnedMesh geometry={nodes.Object_118.geometry} material={materials.material_6} skeleton={nodes.Object_118.skeleton} />
            <skinnedMesh geometry={nodes.Object_119.geometry} material={materials.material_7} skeleton={nodes.Object_119.skeleton} />
            <skinnedMesh geometry={nodes.Object_120.geometry} material={materials.material_8} skeleton={nodes.Object_120.skeleton} />
            <skinnedMesh geometry={nodes.Object_121.geometry} material={materials.material_9} skeleton={nodes.Object_121.skeleton} />
            <skinnedMesh geometry={nodes.Object_122.geometry} material={materials.material_10} skeleton={nodes.Object_122.skeleton} />
            <skinnedMesh geometry={nodes.Object_123.geometry} material={materials.material_11} skeleton={nodes.Object_123.skeleton} />
            <skinnedMesh geometry={nodes.Object_124.geometry} material={materials.material_12} skeleton={nodes.Object_124.skeleton} />
            <skinnedMesh geometry={nodes.Object_125.geometry} material={materials.material_13} skeleton={nodes.Object_125.skeleton} />
            <skinnedMesh geometry={nodes.Object_126.geometry} material={materials.material_14} skeleton={nodes.Object_126.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/509.glb')
