/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/516.glb -o models/gltfjsx/regular/516.jsx 
Author: Cubone0711 (https://sketchfab.com/Cubone0711)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/3ds-pokemon-x-y-516-simipour-de8a23bce42c4e3693883efdaa273e9d
Title: 3DS - Pokemon X Y - 516 Simipour
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/516.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.BodyA00} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.BodyB00} />
      </group>
    </group>
  )
}

useGLTF.preload('/516.glb')
