/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/518.glb -o models/gltfjsx/regular/518.jsx 
Author: nguyenlouis32 (https://sketchfab.com/nguyenlouis32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/musharna-c25f717330e740a5a269a929b0706d26
Title: Musharna
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/518.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-0.617, 0.923, -1.632]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.MusharnaEyeNl} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.MusharnaNl} />
      </group>
    </group>
  )
}

useGLTF.preload('/518.glb')
