/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/522.glb -o models/gltfjsx/regular/522.jsx 
Author: nguyenlouis32 (https://sketchfab.com/nguyenlouis32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/blitzle-0874ab71b54c4d40b32ce993e1106919
Title: Blitzle
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/522.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, 1.569, Math.PI]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.ShimamaBodyNl} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.ShimamaEyeNl} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.ShimamaMouthNl} />
      </group>
    </group>
  )
}

useGLTF.preload('/522.glb')
