/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/53.glb -o models/gltfjsx/regular/53.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/53.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={2.54}>
        <group position={[0, 0.744, -0.101]} rotation={[1.753, 0, Math.PI / 2]}>
          <primitive object={nodes['004_Hips']} />
          <primitive object={nodes['029_Spine1']} />
        </group>
      </group>
      <group scale={2.54}>
        <skinnedMesh geometry={nodes.Persian_1.geometry} material={materials.Eye} skeleton={nodes.Persian_1.skeleton} />
        <skinnedMesh geometry={nodes.Persian_2.geometry} material={materials.Body} skeleton={nodes.Persian_2.skeleton} />
        <skinnedMesh geometry={nodes.Persian_3.geometry} material={materials.LIris} skeleton={nodes.Persian_3.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/53.glb')
