/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/530.glb -o models/gltfjsx/regular/530.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/530.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[1.571, 1.563, 1.571]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['DoryuzuBodyNl.001']} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['DoryuzuEyeNl.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/530.glb')
