/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/535.glb -o models/gltfjsx/regular/535.jsx 
Author: nguyenlouis32 (https://sketchfab.com/nguyenlouis32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tympole-dff604d5e00f422086a7fa6638fcf1ae
Title: Tympole
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/535.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.OtamaroBodyNl} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.OtamaroEyeNl} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.OtamaroMouthNl} />
      </group>
    </group>
  )
}

useGLTF.preload('/535.glb')
