/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/543.glb -o models/gltfjsx/regular/543.jsx 
Author: nguyenlouis32 (https://sketchfab.com/nguyenlouis32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/venipede-32ccab61d42e47f98cb5372c65125819
Title: Venipede
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/543.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, 1.564, 3.141]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.FushideBodyNl} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.FushideEyeNl} />
      </group>
    </group>
  )
}

useGLTF.preload('/543.glb')
