/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/55.glb -o models/gltfjsx/regular/55.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/55.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={2.54}>
        <group position={[0, 0.7, 0.017]} rotation={[0.125, 0, Math.PI / 2]}>
          <primitive object={nodes['004_Hips']} />
          <primitive object={nodes['040_Spine1']} />
        </group>
      </group>
      <group scale={2.54}>
        <skinnedMesh geometry={nodes.Golduck_1.geometry} material={materials.Eye} skeleton={nodes.Golduck_1.skeleton} />
        <skinnedMesh geometry={nodes.Golduck_2.geometry} material={materials.BodySpc01} skeleton={nodes.Golduck_2.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/55.glb')
