/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/554.glb -o models/gltfjsx/regular/554.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/554.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_0.geometry} material={materials.Body} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_1.geometry} material={materials.Mouth} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_2.geometry} material={materials.Eye} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/554.glb')
