/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/555.glb -o models/gltfjsx/regular/555.jsx 
Author: nguyenlouis32 (https://sketchfab.com/nguyenlouis32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/darmanitan-1abaf4917eaa4b0e9653eeb8bfc91038
Title: Darmanitan
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/555.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.HihidarumaBodyNl} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.HihidarumaEyeNl} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.HihidarumaFireNl} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.HihidarumaStandbyNl} />
      </group>
    </group>
  )
}

useGLTF.preload('/555.glb')
