/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/561.glb -o models/gltfjsx/regular/561.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/561.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_0.geometry} material={materials.Body} rotation={[Math.PI / 2, 0, 0]} scale={2.171} />
    </group>
  )
}

useGLTF.preload('/561.glb')
