/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/576.glb -o models/gltfjsx/regular/576.jsx 
Author: nguyenlouis32 (https://sketchfab.com/nguyenlouis32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gothitelle-7347a7cbd2334b2dbe05767c2389db52
Title: Gothitelle
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/576.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 1.57, -1.562]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.GothiruselleBodyNl} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.GothiruselleEyeNl} />
      </group>
    </group>
  )
}

useGLTF.preload('/576.glb')
