/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/579.glb -o models/gltfjsx/regular/579.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/regular/579.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[21.082, 3.138, 0.432]} rotation={[-1.571, 1.566, -0.91]}>
        <group position={[1.06, 1.396, -21.054]} rotation={[-0.003, -0.002, -0.751]}>
          <mesh geometry={nodes.Object_0002.geometry} material={materials.LanculusEyeNl} />
          <mesh geometry={nodes.Object_0002_1.geometry} material={materials.LanculusNl} />
        </group>
        <mesh geometry={nodes.Object_3001.geometry} material={materials['Material.001']} position={[0.351, 2.376, 7.702]} rotation={[-0.003, -0.002, -0.751]} />
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/regular/579.glb')
