/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/587.glb -o models/gltfjsx/regular/587.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/587.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={2.54}>
        <group position={[0, 0.077, 0.009]} rotation={[0.031, 0, Math.PI / 2]}>
          <primitive object={nodes.Hips} />
          <primitive object={nodes.Spine1} />
        </group>
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
        <skinnedMesh geometry={nodes.Emolga_1.geometry} material={materials['Material #118']} skeleton={nodes.Emolga_1.skeleton} />
        <skinnedMesh geometry={nodes.Emolga_2.geometry} material={materials['Material #119']} skeleton={nodes.Emolga_2.skeleton} />
        <skinnedMesh geometry={nodes.Emolga_3.geometry} material={materials['Material #120']} skeleton={nodes.Emolga_3.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/587.glb')
