/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/592.glb -o models/gltfjsx/regular/592.jsx 
Author: nguyenlouis32 (https://sketchfab.com/nguyenlouis32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/frillish-ad768369641544acae7fee5959e59252
Title: Frillish
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/592.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.Eye_mat_002} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.BodyA_mat_002} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.BodyC_mat} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.BodyB_mat_002} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.BodyB_mat_002} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.BodyC_mat} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.BodyA_mat_002} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.Eye_mat_002} />
      </group>
    </group>
  )
}

useGLTF.preload('/592.glb')
