/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/596.glb -o models/gltfjsx/regular/596.jsx 
Author: nguyenlouis32 (https://sketchfab.com/nguyenlouis32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/galvantula-a420108f574a44afb67e5c91b5aabeb7
Title: Galvantula
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/596.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.DentulaBodyNl} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.DentulaEyeNl} />
      </group>
    </group>
  )
}

useGLTF.preload('/596.glb')
