/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/612.glb -o models/gltfjsx/regular/612.jsx 
Author: nguyenlouis32 (https://sketchfab.com/nguyenlouis32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/haxorus-0f540c11c8704a8898c3ed08c504172a
Title: Haxorus
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/612.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.OnonokusBodyNl} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.OnonokusEyeNl} />
      </group>
    </group>
  )
}

useGLTF.preload('/612.glb')
