/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/613.glb -o models/gltfjsx/regular/613.jsx 
Author: nguyenlouis32 (https://sketchfab.com/nguyenlouis32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cubchoo-a38476530668484b9cc902c12e8adce1
Title: Cubchoo
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/613.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.KumasyunBodyNl} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.KumasyunEyeNl} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.KumasyunMouthNl} />
      </group>
    </group>
  )
}

useGLTF.preload('/613.glb')
