/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/630.glb -o models/gltfjsx/regular/630.jsx 
Author: nguyenlouis32 (https://sketchfab.com/nguyenlouis32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mandibuzz-4847b0393bdf4098a02c042ed38a106b
Title: Mandibuzz
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/630.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI, 1.564, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.VulginaEyeNl} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.VulginaNl} />
      </group>
    </group>
  )
}

useGLTF.preload('/630.glb')
