/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/640.glb -o models/gltfjsx/regular/640.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const { scene } = useGLTF('/640.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={2.54}>
        <group position={[0, 1.034, -0.085]} rotation={[1.692, 0, Math.PI / 2]}>
          <primitive object={nodes.Hips} />
          <primitive object={nodes.Spine1} />
        </group>
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
        <skinnedMesh geometry={nodes.Virizion_1.geometry} material={materials['Material #38']} skeleton={nodes.Virizion_1.skeleton} />
        <skinnedMesh geometry={nodes.Virizion_2.geometry} material={materials['Material #39']} skeleton={nodes.Virizion_2.skeleton} />
        <skinnedMesh geometry={nodes.Virizion_3.geometry} material={materials['Material #40']} skeleton={nodes.Virizion_3.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/640.glb')
