/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/642.glb -o models/gltfjsx/regular/642.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/642.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={2.54}>
        <primitive object={nodes.Waist} />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
        <skinnedMesh geometry={nodes.Thundurus_1.geometry} material={materials['Material #149']} skeleton={nodes.Thundurus_1.skeleton} />
        <skinnedMesh geometry={nodes.Thundurus_2.geometry} material={materials['Material #150']} skeleton={nodes.Thundurus_2.skeleton} />
        <skinnedMesh geometry={nodes.Thundurus_3.geometry} material={materials['Material #151']} skeleton={nodes.Thundurus_3.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/642.glb')
