/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/643.glb -o models/gltfjsx/regular/643.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/643.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={2.54}>
        <group position={[0, 1.244, 0.381]} rotation={[0.92, 0, Math.PI / 2]}>
          <primitive object={nodes.Hips} />
          <group rotation={[0, 0.313, 0]}>
            <primitive object={nodes.Spine2} />
          </group>
        </group>
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
        <skinnedMesh geometry={nodes.Reshiram_1.geometry} material={materials['Material #12']} skeleton={nodes.Reshiram_1.skeleton} />
        <skinnedMesh geometry={nodes.Reshiram_2.geometry} material={materials['Material #13']} skeleton={nodes.Reshiram_2.skeleton} />
        <skinnedMesh geometry={nodes.Reshiram_3.geometry} material={materials['Material #14']} skeleton={nodes.Reshiram_3.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/643.glb')
