/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/647.glb -o models/gltfjsx/regular/647.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const { scene } = useGLTF('/647.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={2.54}>
        <group position={[0, 0.559, -0.058]} rotation={[1.568, 0, Math.PI / 2]}>
          <primitive object={nodes.Hips} />
          <primitive object={nodes.Spine1} />
        </group>
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
        <skinnedMesh geometry={nodes.Keldeo_1.geometry} material={materials['Material #288']} skeleton={nodes.Keldeo_1.skeleton} />
        <skinnedMesh geometry={nodes.Keldeo_2.geometry} material={materials['Material #289']} skeleton={nodes.Keldeo_2.skeleton} />
        <skinnedMesh geometry={nodes.Keldeo_3.geometry} material={materials['Material #290']} skeleton={nodes.Keldeo_3.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/647.glb')
