/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/65.glb -o models/gltfjsx/regular/65.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/regular/65.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={2.54}>
        <group position={[0, 0.733, -0.063]} rotation={[0, 0, Math.PI / 2]}>
          <primitive object={nodes.Hips} />
          <primitive object={nodes.LFeelerA} />
          <primitive object={nodes.RFeelerA} />
          <primitive object={nodes.Spine} />
        </group>
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
        <skinnedMesh geometry={nodes.AlakazamF_1.geometry} material={materials['Material #91']} skeleton={nodes.AlakazamF_1.skeleton} />
        <skinnedMesh geometry={nodes.AlakazamF_2.geometry} material={materials['Material #92']} skeleton={nodes.AlakazamF_2.skeleton} />
        <skinnedMesh geometry={nodes.AlakazamF_3.geometry} material={materials['Material #93']} skeleton={nodes.AlakazamF_3.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/regular/65.glb')
