/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/654.glb -o models/gltfjsx/regular/654.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/654.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_22.geometry} material={materials.Material_146_0} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.Material_147} />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_10.geometry} material={materials.Material_80} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Material_76} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Material_77} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Material_78} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Material_79} />
      </group>
      <primitive object={nodes._rootJoint} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.Material_77_0} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.Material_77_1} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.Material_78_0} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.Material_78_1} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/654.glb')
