/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/662.glb -o models/gltfjsx/regular/662.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const { scene } = useGLTF('/662.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={2.54}>
        <primitive object={nodes.Waist} />
      </group>
      <skinnedMesh geometry={nodes.Fletchinder_BeakA.geometry} material={materials['Material #279']} skeleton={nodes.Fletchinder_BeakA.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={2.54} />
      <skinnedMesh geometry={nodes.Fletchinder_BeakB.geometry} material={materials['Material #279']} skeleton={nodes.Fletchinder_BeakB.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={2.54} />
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
        <skinnedMesh geometry={nodes.Fletchinder_1.geometry} material={materials['Material #281']} skeleton={nodes.Fletchinder_1.skeleton} />
        <skinnedMesh geometry={nodes.Fletchinder_2.geometry} material={materials['Material #279']} skeleton={nodes.Fletchinder_2.skeleton} />
      </group>
      <skinnedMesh geometry={nodes.Fletchinder_WingsOpen.geometry} material={materials['Material #280']} skeleton={nodes.Fletchinder_WingsOpen.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={2.54} />
      <skinnedMesh geometry={nodes.Fletchinder_WingsClosed.geometry} material={materials['Material #280']} skeleton={nodes.Fletchinder_WingsClosed.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={2.54} />
    </group>
  )
}

useGLTF.preload('/662.glb')
