/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/674.glb -o models/gltfjsx/regular/674.jsx 
Author: herogamer0108 (https://sketchfab.com/herogamer0108)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pancham-bcfab6717d304f6db9d5ae97aee24032
Title: pancham
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/674.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-12.225, 85.938, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={161.324}>
          <mesh geometry={nodes.Cube_Material_0.geometry} material={materials.Material} />
          <mesh geometry={nodes.Cube_Material001_0.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Cube_Material002_0.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.Cube_Material005_0.geometry} material={materials['Material.005']} />
          <mesh geometry={nodes.Cube_Material004_0.geometry} material={materials['Material.004']} />
          <mesh geometry={nodes.Cube_Material003_0.geometry} material={materials['Material.003']} />
          <mesh geometry={nodes.Cube_Material003_0_1.geometry} material={materials['Material.003']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/674.glb')
