/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/679.glb -o models/gltfjsx/regular/679.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/regular/679.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={2.54}>
        <group position={[0, 0.4, 0]} rotation={[0, 0, Math.PI / 2]}>
          <primitive object={nodes.FeelerA2} />
          <primitive object={nodes.FeelerB2} />
        </group>
      </group>
      <skinnedMesh geometry={nodes.HonedgeSheath.geometry} material={materials['Material #59']} skeleton={nodes.HonedgeSheath.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={2.54} />
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
        <skinnedMesh geometry={nodes.Honedge_1.geometry} material={materials['Material #59']} skeleton={nodes.Honedge_1.skeleton} />
        <skinnedMesh geometry={nodes.Honedge_2.geometry} material={materials['Material #60']} skeleton={nodes.Honedge_2.skeleton} />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
        <skinnedMesh geometry={nodes.HonedgeSword_1.geometry} material={materials['Material #59']} skeleton={nodes.HonedgeSword_1.skeleton} />
        <skinnedMesh geometry={nodes.HonedgeSword_2.geometry} material={materials['Material #60']} skeleton={nodes.HonedgeSword_2.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/regular/679.glb')
