/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/69.glb -o models/gltfjsx/regular/69.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/regular/69.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={2.54}>
        <group position={[0, 0.256, -0.012]} rotation={[0.137, 0, Math.PI / 2]}>
          <primitive object={nodes['004_Hips']} />
          <primitive object={nodes['042_Spine1']} />
        </group>
      </group>
      <group scale={2.54}>
        <skinnedMesh geometry={nodes.Bellsprout_1.geometry} material={materials.Body00} skeleton={nodes.Bellsprout_1.skeleton} />
        <skinnedMesh geometry={nodes.Bellsprout_2.geometry} material={materials.Eye} skeleton={nodes.Bellsprout_2.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/regular/69.glb')
