/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/693.glb -o models/gltfjsx/regular/693.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/693.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={2.54}>
        <group position={[0, 0.3, 0.007]} rotation={[1.64, 0, Math.PI / 2]}>
          <primitive object={nodes.Hips} />
          <primitive object={nodes.Spine} />
        </group>
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
        <skinnedMesh geometry={nodes.Clawitzer_1.geometry} material={materials.BodyA} skeleton={nodes.Clawitzer_1.skeleton} />
        <skinnedMesh geometry={nodes.Clawitzer_2.geometry} material={materials.Eye} skeleton={nodes.Clawitzer_2.skeleton} />
        <skinnedMesh geometry={nodes.Clawitzer_3.geometry} material={materials.BodyB} skeleton={nodes.Clawitzer_3.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/693.glb')
