/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/702.glb -o models/gltfjsx/regular/702.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const { scene } = useGLTF('/702.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={2.54}>
        <group position={[0, 0.061, 0.004]} rotation={[-0.091, 0, Math.PI / 2]}>
          <primitive object={nodes.Hips} />
          <primitive object={nodes.Spine1} />
        </group>
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
        <skinnedMesh geometry={nodes.Dedenne_1.geometry} material={materials['Material #246']} skeleton={nodes.Dedenne_1.skeleton} />
        <skinnedMesh geometry={nodes.Dedenne_2.geometry} material={materials['Material #247']} skeleton={nodes.Dedenne_2.skeleton} />
        <skinnedMesh geometry={nodes.Dedenne_3.geometry} material={materials['Material #248']} skeleton={nodes.Dedenne_3.skeleton} />
        <skinnedMesh geometry={nodes.Dedenne_4.geometry} material={materials['Material #249']} skeleton={nodes.Dedenne_4.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/702.glb')
