/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/713.glb -o models/gltfjsx/regular/713.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/713.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={2.54}>
        <group position={[0, 1.466, -0.545]} rotation={[Math.PI / 2, 0, Math.PI / 2]}>
          <primitive object={nodes.Hips} />
          <primitive object={nodes.Spine1} />
        </group>
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
        <skinnedMesh geometry={nodes.Avalugg_1.geometry} material={materials.BodyB} skeleton={nodes.Avalugg_1.skeleton} />
        <skinnedMesh geometry={nodes.Avalugg_2.geometry} material={materials.Eye} skeleton={nodes.Avalugg_2.skeleton} />
        <skinnedMesh geometry={nodes.Avalugg_3.geometry} material={materials.BodyA} skeleton={nodes.Avalugg_3.skeleton} />
        <skinnedMesh geometry={nodes.Avalugg_4.geometry} material={materials.BodyATrans} skeleton={nodes.Avalugg_4.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/713.glb')
