/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/725.glb -o models/gltfjsx/regular/725.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/725.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.025}>
        <primitive object={nodes.pm0844_00} />
        <skinnedMesh geometry={nodes.Litten_BackFur.geometry} material={materials.Body} skeleton={nodes.Litten_BackFur.skeleton} />
        <skinnedMesh geometry={nodes.Litten_Claws.geometry} material={materials.Body} skeleton={nodes.Litten_Claws.skeleton} />
        <skinnedMesh geometry={nodes.Mesh.geometry} material={materials.Body} skeleton={nodes.Mesh.skeleton} />
        <skinnedMesh geometry={nodes.Mesh_1.geometry} material={materials.Eye} skeleton={nodes.Mesh_1.skeleton} />
        <skinnedMesh geometry={nodes.Mesh_2.geometry} material={materials.Mouth} skeleton={nodes.Mesh_2.skeleton} />
        <skinnedMesh geometry={nodes.Mesh_3.geometry} material={materials.LIris} skeleton={nodes.Mesh_3.skeleton} />
        <skinnedMesh geometry={nodes.Mesh_4.geometry} material={materials.RIris} skeleton={nodes.Mesh_4.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/725.glb')
