/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/730.glb -o models/gltfjsx/regular/730.jsx 
Author: nguyenlouis32 (https://sketchfab.com/nguyenlouis32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/primarina-6a1c86762d58480098af4969915ceb96
Title: Primarina
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const { scene } = useGLTF('/730.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={0.025}>
        <primitive object={nodes._rootJoint} />
        <skinnedMesh geometry={nodes.Object_6.geometry} material={materials.Body} skeleton={nodes.Object_6.skeleton} />
        <skinnedMesh geometry={nodes.Object_7.geometry} material={materials.material} skeleton={nodes.Object_7.skeleton} />
        <skinnedMesh geometry={nodes.Object_8.geometry} material={materials.Mouth} skeleton={nodes.Object_8.skeleton} />
        <skinnedMesh geometry={nodes.Object_10.geometry} material={materials.Hair} skeleton={nodes.Object_10.skeleton} />
        <skinnedMesh geometry={nodes.Object_12.geometry} material={materials.Hair} skeleton={nodes.Object_12.skeleton} />
        <skinnedMesh geometry={nodes.Object_14.geometry} material={materials.Pearls} skeleton={nodes.Object_14.skeleton} />
        <skinnedMesh geometry={nodes.Object_16.geometry} material={materials.Body} skeleton={nodes.Object_16.skeleton} />
        <skinnedMesh geometry={nodes.Object_18.geometry} material={materials.Body} skeleton={nodes.Object_18.skeleton} />
        <skinnedMesh geometry={nodes.Object_20.geometry} material={materials.Body} skeleton={nodes.Object_20.skeleton} />
        <skinnedMesh geometry={nodes.Object_22.geometry} material={materials.Body} skeleton={nodes.Object_22.skeleton} />
        <skinnedMesh geometry={nodes.Object_24.geometry} material={materials.Body} skeleton={nodes.Object_24.skeleton} />
        <skinnedMesh geometry={nodes.Object_26.geometry} material={materials.Body} skeleton={nodes.Object_26.skeleton} />
        <skinnedMesh geometry={nodes.Object_28.geometry} material={materials.Body} skeleton={nodes.Object_28.skeleton} />
        <skinnedMesh geometry={nodes.Object_30.geometry} material={materials.Body} skeleton={nodes.Object_30.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/730.glb')
