/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/733.glb -o models/gltfjsx/regular/733.jsx 
Author: nguyenlouis32 (https://sketchfab.com/nguyenlouis32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/toucannon-86b0a503cc5d44668eea1215a8dd6cb1
Title: Toucannon
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const { scene } = useGLTF('/733.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <primitive object={nodes._rootJoint} />
        <skinnedMesh geometry={nodes.Object_6.geometry} material={materials.VisualMaterial0} skeleton={nodes.Object_6.skeleton} />
        <skinnedMesh geometry={nodes.Object_8.geometry} material={materials.VisualMaterial0_0} skeleton={nodes.Object_8.skeleton} />
        <skinnedMesh geometry={nodes.Object_10.geometry} material={materials.VisualMaterial0_1} skeleton={nodes.Object_10.skeleton} />
        <skinnedMesh geometry={nodes.Object_12.geometry} material={materials.VisualMaterial10} skeleton={nodes.Object_12.skeleton} />
        <skinnedMesh geometry={nodes.Object_14.geometry} material={materials.VisualMaterial20} skeleton={nodes.Object_14.skeleton} />
        <skinnedMesh geometry={nodes.Object_16.geometry} material={materials.VisualMaterial30} skeleton={nodes.Object_16.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/733.glb')
