/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/74.glb -o models/gltfjsx/regular/74.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const { scene } = useGLTF('/74.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={2.54}>
        <primitive object={nodes['003_Waist']} />
      </group>
      <group scale={2.54}>
        <skinnedMesh geometry={nodes.Geodude_1.geometry} material={materials.Eye} skeleton={nodes.Geodude_1.skeleton} />
        <skinnedMesh geometry={nodes.Geodude_2.geometry} material={materials.Body} skeleton={nodes.Geodude_2.skeleton} />
        <skinnedMesh geometry={nodes.Geodude_3.geometry} material={materials.LIris} skeleton={nodes.Geodude_3.skeleton} />
        <skinnedMesh geometry={nodes.Geodude_4.geometry} material={materials.RIris} skeleton={nodes.Geodude_4.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/74.glb')
