/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/746.glb -o models/gltfjsx/regular/746.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/746.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.025}>
        <group position={[0, 5.304, -7.674]} rotation={[Math.PI / 2, 0, 0]} scale={0.787}>
          <mesh geometry={nodes.instance_0.geometry} material={materials.pm0820_11_Eye1_tga} />
          <mesh geometry={nodes.instance_0001.geometry} material={materials.pm0820_11_Eye1_tga} />
          <mesh geometry={nodes.instance_0002.geometry} material={materials.pm0820_11_Body1_tga} />
          <mesh geometry={nodes.instance_0003.geometry} material={materials.pm0820_11_Body1_tga} />
          <mesh geometry={nodes.instance_0004.geometry} material={materials.pm0820_11_Body1_tga} />
          <mesh geometry={nodes.instance_0005.geometry} material={materials.pm0820_11_Body1_tga} />
          <mesh geometry={nodes.instance_0006.geometry} material={materials.pm0820_11_Body1_tga} />
          <mesh geometry={nodes.instance_0007.geometry} material={materials.pm0820_11_Body1_tga} />
          <mesh geometry={nodes.instance_0008.geometry} material={materials.pm0820_11_Body1_tga} />
          <mesh geometry={nodes.instance_0009.geometry} material={materials.pm0820_11_Body1_tga} />
          <mesh geometry={nodes.instance_0010.geometry} material={materials.pm0820_11_Body1_tga} />
          <mesh geometry={nodes.instance_0011.geometry} material={materials.pm0820_11_Body1_tga} />
          <mesh geometry={nodes.instance_0012.geometry} material={materials.pm0820_11_Body1_tga} />
          <mesh geometry={nodes.instance_0013.geometry} material={materials.pm0820_11_Body1_tga} />
          <mesh geometry={nodes.instance_0014.geometry} material={materials.pm0820_11_Body1_tga} />
          <mesh geometry={nodes.instance_0015.geometry} material={materials.pm0820_11_Body1_tga} />
          <mesh geometry={nodes.instance_0016.geometry} material={materials.pm0820_11_Body1_tga} />
          <mesh geometry={nodes.instance_0017.geometry} material={materials.pm0820_11_Body1_tga} />
          <mesh geometry={nodes.instance_0018.geometry} material={materials.pm0820_11_Body1_tga} />
          <mesh geometry={nodes.instance_0019.geometry} material={materials.pm0820_11_Body1_tga} />
          <mesh geometry={nodes.instance_0020.geometry} material={materials.pm0820_11_Body1_tga} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/746.glb')
