/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/748.glb -o models/gltfjsx/regular/748.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/748.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pm0802_00_00_body_mesh_shape_lod1_body_a.geometry} material={materials['body_a.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.pm0802_00_00_body_mesh_shape_lod1_body_b.geometry} material={materials['body_b.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.pm0802_00_00_eye_mesh_shape_lod1_l_eye.geometry} material={materials['l_eye.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.pm0802_00_00_eye_mesh_shape_lod1_r_eye.geometry} material={materials['r_eye.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.pm0802_00_00_feeler_mesh_shape_lod1_body_b.geometry} material={materials['body_b.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.pm0802_00_00_head_mesh_shape_lod1_body_b.geometry} material={materials['body_b.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.pm0802_00_00_skirt_mesh_shape_lod1_body_a.geometry} material={materials['body_a.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.pm0802_00_00_toge_mesh_shape_lod1_body_a.geometry} material={materials['body_a.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.pm0802_00_00_toge_mesh_shape_lod1_body_b.geometry} material={materials['body_b.001']} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/748.glb')
