/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/758.glb -o models/gltfjsx/regular/758.jsx 
Author: LunaEagle (https://sketchfab.com/LunaEagle)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/salazzle-e74eeffb38b445fc8fc141af3198bb2e
Title: Salazzle
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/758.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.body_00} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.fire_a} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.fire_b} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.l_eye} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.r_eye} />
      </group>
    </group>
  )
}

useGLTF.preload('/758.glb')
