/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/761.glb -o models/gltfjsx/regular/761.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/761.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <directionalLight intensity={1} decay={2} position={[14.924, 20.958, 15.363]} target={nodes.DirectionalLight.target}>
        <primitive object={nodes.DirectionalLight.target} position={[0, 0, -1]} />
      </directionalLight>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.364}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial_8.geometry} material={materials.M_Bounsweet} />
          <mesh geometry={nodes.defaultMaterial_9.geometry} material={materials.M_Bounsweet} />
          <mesh geometry={nodes.defaultMaterial_10.geometry} material={materials.M_Bounsweet} />
          <mesh geometry={nodes.defaultMaterial_11.geometry} material={materials.M_Bounsweet} />
          <mesh geometry={nodes.defaultMaterial_12.geometry} material={materials.M_Bounsweet} />
          <mesh geometry={nodes.defaultMaterial_13.geometry} material={materials.M_Bounsweet} />
          <mesh geometry={nodes.defaultMaterial_14.geometry} material={materials.M_Bounsweet} />
          <mesh geometry={nodes.defaultMaterial_15.geometry} material={materials.M_Bounsweet} />
          <mesh geometry={nodes.defaultMaterial_16.geometry} material={materials.M_Bounsweet} />
          <mesh geometry={nodes.defaultMaterial_17.geometry} material={materials.M_Bounsweet} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/761.glb')
