/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/77.glb -o models/gltfjsx/regular/77.jsx 
Author: 31schrci (https://sketchfab.com/31schrci)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ponyta-pokemon-b8c7ba29095448b8a95dcbc940721d43
Title: Ponyta - Pokemon
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/77.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group scale={1.506}>
          <group rotation={[-Math.PI / 2, 0, 1.576]} scale={9.057}>
            <mesh geometry={nodes.cuerpo_Body_0_1.geometry} material={materials.Body} />
            <mesh geometry={nodes.cuerpo_Hair_0_1.geometry} material={materials.Hair} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/77.glb')
