/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/774.glb -o models/gltfjsx/regular/774.jsx 
Author: nguyenlouis32 (https://sketchfab.com/nguyenlouis32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/minior-5a740b2ef2db42548bdad4c1ddb5f6a2
Title: Minior
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/774.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={0.025}>
        <primitive object={nodes._rootJoint} />
        <skinnedMesh geometry={nodes.Object_6.geometry} material={materials.Body} skeleton={nodes.Object_6.skeleton} />
        <skinnedMesh geometry={nodes.Object_7.geometry} material={materials.Rock} skeleton={nodes.Object_7.skeleton} />
        <skinnedMesh geometry={nodes.Object_9.geometry} material={materials.Body} skeleton={nodes.Object_9.skeleton} />
        <skinnedMesh geometry={nodes.Object_11.geometry} material={materials.Body} skeleton={nodes.Object_11.skeleton} />
        <skinnedMesh geometry={nodes.Object_13.geometry} material={materials.Body} skeleton={nodes.Object_13.skeleton} />
        <skinnedMesh geometry={nodes.Object_15.geometry} material={materials.Body} skeleton={nodes.Object_15.skeleton} />
        <skinnedMesh geometry={nodes.Object_17.geometry} material={materials.Body} skeleton={nodes.Object_17.skeleton} />
        <skinnedMesh geometry={nodes.Object_19.geometry} material={materials.Body} skeleton={nodes.Object_19.skeleton} />
        <skinnedMesh geometry={nodes.Object_21.geometry} material={materials.Body} skeleton={nodes.Object_21.skeleton} />
        <skinnedMesh geometry={nodes.Object_23.geometry} material={materials.Rock} skeleton={nodes.Object_23.skeleton} />
        <skinnedMesh geometry={nodes.Object_25.geometry} material={materials.Rock} skeleton={nodes.Object_25.skeleton} />
        <skinnedMesh geometry={nodes.Object_27.geometry} material={materials.Rock} skeleton={nodes.Object_27.skeleton} />
        <skinnedMesh geometry={nodes.Object_29.geometry} material={materials.Rock} skeleton={nodes.Object_29.skeleton} />
        <skinnedMesh geometry={nodes.Object_31.geometry} material={materials.Rock} skeleton={nodes.Object_31.skeleton} />
        <skinnedMesh geometry={nodes.Object_33.geometry} material={materials.Rock} skeleton={nodes.Object_33.skeleton} />
        <skinnedMesh geometry={nodes.Object_35.geometry} material={materials.Rock} skeleton={nodes.Object_35.skeleton} />
        <skinnedMesh geometry={nodes.Object_37.geometry} material={materials.Rock} skeleton={nodes.Object_37.skeleton} />
        <skinnedMesh geometry={nodes.Object_39.geometry} material={materials.Rock} skeleton={nodes.Object_39.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/774.glb')
