/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/776.glb -o models/gltfjsx/regular/776.jsx 
Author: nguyenlouis32 (https://sketchfab.com/nguyenlouis32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/turtonator-af89b5e189c34340a9503999341ccea6
Title: Turtonator
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/776.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['00451_bakugames_dif.png']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['00451_bakugames_ground01_dif.png']} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['00451_bakugames_ground02_dif.png']} />
      </group>
    </group>
  )
}

useGLTF.preload('/776.glb')
