/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/777.glb -o models/gltfjsx/regular/777.jsx 
Author: nguyenlouis32 (https://sketchfab.com/nguyenlouis32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/togedemaru-6dd71b89a3894e389748b307e0369eb8
Title: Togedemaru
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/777.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.BodyA_mat_003} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.BodyB_mat_003} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.BodyC_mat_002} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.BodyC_mat_002} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.BodyB_mat_003} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.BodyA_mat_003} />
      </group>
    </group>
  )
}

useGLTF.preload('/777.glb')
