/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/778.glb -o models/gltfjsx/regular/778.jsx 
Author: Minecraft_Master (https://sketchfab.com/porterjett13)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pokemon-pikachu-4949a0c1c03a47c6892a585c3ed39cf6
Title: pokemon pikachu
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/778.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Sketchfab_model_0" rotation={[-Math.PI / 2, 0, 0]} scale={0.062}>
                <group name="Root_1">
                  <group name="Armature_2">
                    <group name="GLTF_created_0">
                      <primitive object={nodes.GLTF_created_0_rootJoint} />
                      <group name="mimikyu_0_15_correction">
                        <group name="mimikyu_0_15" />
                      </group>
                      <group name="mimikyu_1_16_correction">
                        <group name="mimikyu_1_16" />
                      </group>
                      <skinnedMesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials.body} skeleton={nodes.Object_21.skeleton} />
                      <skinnedMesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials.eyes} skeleton={nodes.Object_24.skeleton} />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/778.glb')
