/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/781.glb -o models/gltfjsx/regular/781.jsx 
Author: Holly_Climpson (https://sketchfab.com/Holly_Climpson)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/admiral-the-dhelmise-441d0f2b8b9a46aab6107ae44f4172b1
Title: Admiral the Dhelmise.
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/regular/781.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.pCube25_Brown_0.geometry} material={materials.Brown} />
        <mesh geometry={nodes.pCube25_Gold2_0.geometry} material={materials.Gold2} />
        <mesh geometry={nodes.pCube25_Black_0.geometry} material={materials.Black} />
        <mesh geometry={nodes.pCube25_lambert1_0.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.pCube25_Gold_0.geometry} material={materials.Gold} />
        <mesh geometry={nodes.pCube25_Eye_0.geometry} material={materials.material} />
        <mesh geometry={nodes.pCube25_EyeGlass_0.geometry} material={materials.EyeGlass} />
        <mesh geometry={nodes.pCube25_White_0.geometry} material={materials.White} />
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/regular/781.glb')
