/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/785.glb -o models/gltfjsx/regular/785.jsx 
Author: Alchemypotion (https://sketchfab.com/Alchemypotion)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/3ds-pokemon-sun-moon-785-tapu-koko-7f26aef6dbe8463db43ef9a81b0d0579
Title: 3DS - Pokemon Sun Moon - 785 Tapu Koko
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/785.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group position={[0, -105.939, -74.037]}>
        <primitive object={nodes._rootJoint} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.pm0830_00_Eye1_tga} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.pm0830_00_Body1_tga} />
      </group>
    </group>
  )
}

useGLTF.preload('/785.glb')
