/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/797.glb -o models/gltfjsx/regular/797.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/797.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.008}>
        <primitive object={nodes.pm0881_00_fi_1} />
        <skinnedMesh geometry={nodes.pm0881_00_fi.geometry} material={materials['pm0881_00_Body_tga_png-material']} skeleton={nodes.pm0881_00_fi.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/797.glb')
