/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/800.glb -o models/gltfjsx/regular/800.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/800.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group rotation={[-1.597, 0, 0]} scale={-0.025}>
        <primitive object={nodes.pm0865_00_fi_1} />
        <skinnedMesh geometry={nodes.pm0865_00_fi.geometry} material={materials['pm0865_00_Body_tga_png-material']} skeleton={nodes.pm0865_00_fi.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/800.glb')
