/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/809.glb -o models/gltfjsx/regular/809.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const { scene } = useGLTF('/809.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group position={[0, 1.451, 0]}>
        <group position={[-1.785, -1.164, -45.889]} rotation={[-Math.PI / 2, 0, 0]}>
          <group position={[1.785, -4.766, 0.892]}>
            <group position={[-1.046, 18.038, -1.193]} rotation={[Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes.Object_10.geometry} material={materials['Material.030']} position={[0, 5.866, 53.787]} scale={[1, 1, 0.807]} />
              <mesh geometry={nodes.Object_12.geometry} material={materials['Material.030']} position={[-0.113, 5.866, 64.083]} rotation={[-Math.PI, 0, -Math.PI]} scale={[1, 1, 0.807]} />
              <mesh geometry={nodes.Object_14.geometry} material={materials['Material.030']} position={[0, 3.163, 58.924]} scale={[1.223, 1, 1.277]} />
              <mesh geometry={nodes.Object_42.geometry} material={materials['Material.026']} position={[0, 5.393, 58.958]} rotation={[0, Math.PI / 6, 0]} />
              <mesh geometry={nodes.Object_44.geometry} material={materials['Material.029']} position={[0.797, 0.314, 60.404]} rotation={[0, Math.PI / 6, 0]} scale={[1.148, 0.273, 1.148]} />
              <mesh geometry={nodes.Object_46.geometry} material={materials['Material.029']} position={[0.797, 0.314, 57.449]} rotation={[0, Math.PI / 6, 0]} scale={[1.148, 0.273, 1.148]} />
              <mesh geometry={nodes.Object_48.geometry} material={materials['Material.029']} position={[0, 5.784, 55.414]} rotation={[Math.PI / 2, Math.PI / 6, 0]} scale={[2.43, 0.705, 2.43]} />
              <mesh geometry={nodes.Object_50.geometry} material={materials['metal.002']} position={[0.763, 3.444, 58.915]} rotation={[Math.PI / 6, 0, -Math.PI / 2]} scale={[0.508, 0.121, 0.508]} />
              <mesh geometry={nodes.Object_52.geometry} material={materials['Material.030']} position={[0, 5.875, 58.958]} scale={1.068} />
              <mesh geometry={nodes.Object_54.geometry} material={materials['Material.026']} position={[0, 6.296, 58.958]} rotation={[0, 0, -Math.PI / 2]} scale={[1.317, 0.451, 1.317]} />
              <mesh geometry={nodes.Object_56.geometry} material={materials['Material.029']} position={[0, 5.841, 52.674]} rotation={[Math.PI / 2, Math.PI / 6, 0]} scale={[1.113, 0.213, 1.113]} />
              <mesh geometry={nodes.Object_58.geometry} material={materials['Material.029']} position={[-0.01, 5.886, 50.049]} rotation={[2.07, 0, -Math.PI / 2]} scale={[2.148, 0.72, 2.043]} />
              <mesh geometry={nodes.Object_60.geometry} material={materials['Material.032']} position={[-1.416, 2.549, 58.958]} rotation={[0, 0, 1.189]} scale={0.085} />
              <mesh geometry={nodes.Object_62.geometry} material={materials['Material.029']} position={[-0.103, 5.886, 67.821]} rotation={[1.072, 0, Math.PI / 2]} scale={[2.148, 0.72, 2.043]} />
              <mesh geometry={nodes.Object_64.geometry} material={materials['Material.029']} position={[-0.113, 5.829, 65.196]} rotation={[Math.PI / 2, -Math.PI / 6, Math.PI]} scale={[1.113, 0.213, 1.113]} />
              <mesh geometry={nodes.Object_66.geometry} material={materials['Material.029']} position={[-0.113, 5.784, 62.456]} rotation={[Math.PI / 2, -Math.PI / 6, Math.PI]} scale={[2.315, 0.671, 2.315]} />
              <mesh geometry={nodes.Object_76.geometry} material={materials['Material.030']} position={[0.503, 5.784, 50.056]} rotation={[0, 0, -Math.PI / 2]} scale={[1.116, 1.103, 0.75]} />
              <mesh geometry={nodes.Object_78.geometry} material={materials['Material.030']} position={[0.775, 5.784, 67.814]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[1.08, 1.068, 0.726]} />
              <mesh geometry={nodes.Object_80.geometry} material={materials['Material.030']} position={[-0.616, 5.784, 67.814]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[1.116, 1.103, 0.75]} />
              <mesh geometry={nodes.Object_82.geometry} material={materials['Material.030']} position={[-0.888, 5.784, 50.056]} rotation={[0, 0, -Math.PI / 2]} scale={[1.08, 1.068, 0.726]} />
              <mesh geometry={nodes.Object_90.geometry} material={materials['Material.029']} position={[0, 6.592, 58.957]} scale={0.21} />
              <mesh geometry={nodes.Object_92.geometry} material={materials['Material.029']} position={[-0.113, 5.79, 62.193]} rotation={[-Math.PI, 0, -Math.PI]} scale={[1.744, 1.744, 1.342]} />
              <mesh geometry={nodes.Object_94.geometry} material={materials['Material.029']} position={[-0.113, 5.79, 55.906]} scale={[1.744, 1.744, 1.342]} />
            </group>
          </group>
        </group>
      </group>
      <directionalLight intensity={1} decay={2} position={[6.48, 24.793, 20.624]} rotation={[0, 1.26, 0]} target={nodes.DirectionalLight.target}>
        <primitive object={nodes.DirectionalLight.target} position={[0, 0, -1]} />
      </directionalLight>
      <directionalLight intensity={1} decay={2} position={[-15.807, 26.409, -7.961]} target={nodes.DirectionalLight_2.target}>
        <primitive object={nodes.DirectionalLight_2.target} position={[0, 0, -1]} />
      </directionalLight>
    </group>
  )
}

useGLTF.preload('/809.glb')
