/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/811.glb -o models/gltfjsx/regular/811.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/regular/811.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.025}>
        <primitive object={nodes.pm0949_00_00} />
        <skinnedMesh geometry={nodes.pm0949_00_00_LStickASkin.geometry} material={materials['BodyA04.001']} skeleton={nodes.pm0949_00_00_LStickASkin.skeleton} />
        <skinnedMesh geometry={nodes.pm0949_00_00_LStickBSkin.geometry} material={materials['BodyA04.001']} skeleton={nodes.pm0949_00_00_LStickBSkin.skeleton} />
        <skinnedMesh geometry={nodes.pm0949_00_00_MuzzleASkin.geometry} material={materials['BodyA05.001']} skeleton={nodes.pm0949_00_00_MuzzleASkin.skeleton} />
        <skinnedMesh geometry={nodes.pm0949_00_00_MuzzleBSkin.geometry} material={materials['BodyA05.001']} skeleton={nodes.pm0949_00_00_MuzzleBSkin.skeleton} />
        <skinnedMesh geometry={nodes.pm0949_00_00_RStickASkin.geometry} material={materials['BodyA04.001']} skeleton={nodes.pm0949_00_00_RStickASkin.skeleton} />
        <skinnedMesh geometry={nodes.pm0949_00_00_RStickBSkin.geometry} material={materials['BodyA04.001']} skeleton={nodes.pm0949_00_00_RStickBSkin.skeleton} />
        <skinnedMesh geometry={nodes.Mesh001.geometry} material={materials['BodyA03.001']} skeleton={nodes.Mesh001.skeleton} />
        <skinnedMesh geometry={nodes.Mesh001_1.geometry} material={materials['BodyA01.001']} skeleton={nodes.Mesh001_1.skeleton} />
        <skinnedMesh geometry={nodes.Mesh001_2.geometry} material={materials['BodyA05.001']} skeleton={nodes.Mesh001_2.skeleton} />
        <skinnedMesh geometry={nodes.Mesh001_3.geometry} material={materials['REye.001']} skeleton={nodes.Mesh001_3.skeleton} />
        <skinnedMesh geometry={nodes.Mesh001_4.geometry} material={materials['LEye.001']} skeleton={nodes.Mesh001_4.skeleton} />
        <skinnedMesh geometry={nodes.Mesh001_5.geometry} material={materials['BodyA02.001']} skeleton={nodes.Mesh001_5.skeleton} />
        <skinnedMesh geometry={nodes.Mesh.geometry} material={materials['BodyA03.001']} skeleton={nodes.Mesh.skeleton} />
        <skinnedMesh geometry={nodes.Mesh_1.geometry} material={materials['BodyA01.001']} skeleton={nodes.Mesh_1.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/regular/811.glb')
