/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/828.glb -o models/gltfjsx/regular/828.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const { scene } = useGLTF('/828.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.025}>
        <primitive object={nodes.pm0902_00_00} />
        <skinnedMesh geometry={nodes.pm0902_00_00_LClawSkin.geometry} material={materials.Body} skeleton={nodes.pm0902_00_00_LClawSkin.skeleton} />
        <skinnedMesh geometry={nodes.pm0902_00_00_RClawSkin.geometry} material={materials.Body} skeleton={nodes.pm0902_00_00_RClawSkin.skeleton} />
        <skinnedMesh geometry={nodes.pm0902_00_00_TongueSkin.geometry} material={materials.Body} skeleton={nodes.pm0902_00_00_TongueSkin.skeleton} />
        <skinnedMesh geometry={nodes.Mesh.geometry} material={materials.Body} skeleton={nodes.Mesh.skeleton} />
        <skinnedMesh geometry={nodes.Mesh_1.geometry} material={materials.LEye} skeleton={nodes.Mesh_1.skeleton} />
        <skinnedMesh geometry={nodes.Mesh_2.geometry} material={materials.REye} skeleton={nodes.Mesh_2.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/828.glb')
