/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/831.glb -o models/gltfjsx/regular/831.jsx 
Author: Shiju (https://sketchfab.com/XenoFu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wooloo-6251869752b54edea1616104d58035ec
Title: Wooloo
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/831.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Woloo013_(null)_0'].geometry} material={materials['null']} position={[0, 4.402, 26.383]} scale={100} />
    </group>
  )
}

useGLTF.preload('/831.glb')
