/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/833.glb -o models/gltfjsx/regular/833.jsx 
Author: denisduljaj442 (https://sketchfab.com/denisduljaj442)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pokemon-sword-shield-833-chewtle-d98af6d4997647ce9081679ed5dfd548
Title: Pokemon Sword & Shield #833 Chewtle
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/833.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={0.025}>
        <primitive object={nodes._rootJoint} />
        <skinnedMesh geometry={nodes.Object_6.geometry} material={materials.BodyVco01} skeleton={nodes.Object_6.skeleton} />
        <skinnedMesh geometry={nodes.Object_7.geometry} material={materials.material} skeleton={nodes.Object_7.skeleton} />
        <skinnedMesh geometry={nodes.Object_8.geometry} material={materials.Body03} skeleton={nodes.Object_8.skeleton} />
        <skinnedMesh geometry={nodes.Object_9.geometry} material={materials.BodyVco02} skeleton={nodes.Object_9.skeleton} />
        <skinnedMesh geometry={nodes.Object_11.geometry} material={materials.Body04} skeleton={nodes.Object_11.skeleton} />
        <skinnedMesh geometry={nodes.Object_13.geometry} material={materials.BodyVco00} skeleton={nodes.Object_13.skeleton} />
        <skinnedMesh geometry={nodes.Object_15.geometry} material={materials.BodyVco00} skeleton={nodes.Object_15.skeleton} />
        <skinnedMesh geometry={nodes.Object_17.geometry} material={materials.Body00} skeleton={nodes.Object_17.skeleton} />
        <skinnedMesh geometry={nodes.Object_18.geometry} material={materials.Body01} skeleton={nodes.Object_18.skeleton} />
        <skinnedMesh geometry={nodes.Object_19.geometry} material={materials.Body02} skeleton={nodes.Object_19.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/833.glb')
