/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/834.glb -o models/gltfjsx/regular/834.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const { scene } = useGLTF('/834.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.025}>
        <primitive object={nodes.pm0904_00_00} />
        <skinnedMesh geometry={nodes.Mesh.geometry} material={materials.Eye} skeleton={nodes.Mesh.skeleton} />
        <skinnedMesh geometry={nodes.Mesh_1.geometry} material={materials.BodyA00} skeleton={nodes.Mesh_1.skeleton} />
        <skinnedMesh geometry={nodes.Mesh_2.geometry} material={materials.BodyA02} skeleton={nodes.Mesh_2.skeleton} />
        <skinnedMesh geometry={nodes.Mesh_3.geometry} material={materials.BodyAVco} skeleton={nodes.Mesh_3.skeleton} />
        <skinnedMesh geometry={nodes.Mesh_4.geometry} material={materials.BodyA01} skeleton={nodes.Mesh_4.skeleton} />
        <skinnedMesh geometry={nodes.Mesh001.geometry} material={materials.BodyB00} skeleton={nodes.Mesh001.skeleton} />
        <skinnedMesh geometry={nodes.Mesh001_1.geometry} material={materials.BodyB01} skeleton={nodes.Mesh001_1.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/834.glb')
