/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/843.glb -o models/gltfjsx/regular/843.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/843.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <primitive object={nodes.pm0936_00_00} />
        <skinnedMesh geometry={nodes.pm0936_00_00_BodySkin.geometry} material={materials.Body} skeleton={nodes.pm0936_00_00_BodySkin.skeleton} />
        <skinnedMesh geometry={nodes.pm0936_00_00_TongueSkin.geometry} material={materials.Body} skeleton={nodes.pm0936_00_00_TongueSkin.skeleton} />
        <skinnedMesh geometry={nodes.Mesh001.geometry} material={materials.Eye} skeleton={nodes.Mesh001.skeleton} />
        <skinnedMesh geometry={nodes.Mesh001_1.geometry} material={materials.BodyVco} skeleton={nodes.Mesh001_1.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/843.glb')
