/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/855.glb -o models/gltfjsx/regular/855.jsx 
Author: BlenderLager (https://sketchfab.com/blenderlager)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/polteageist-40ca3d26605c42529080f93cb7678376
Title: Polteageist
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/855.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[10, 0, 0]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials['Polteageist_Body.001']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Polteageist_Pot} />
      </group>
    </group>
  )
}

useGLTF.preload('/855.glb')
