/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/856.glb -o models/gltfjsx/regular/856.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/regular/856.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.664, -0.347, -0.303]} rotation={[-0.722, 0.261, -0.465]}>
        <mesh geometry={nodes.Sphere002_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Sphere002_2.geometry} material={materials.Pink} />
      </group>
      <group position={[-0.008, 0.911, 1.034]} rotation={[0.448, -0.024, -0.117]} scale={[1.358, 1.256, 1.122]}>
        <mesh geometry={nodes.Sphere003_1.geometry} material={materials['Pink.001']} />
        <mesh geometry={nodes.Sphere003_2.geometry} material={materials.red} />
      </group>
      <mesh geometry={nodes.Sphere001.geometry} material={materials['Material.004']} position={[0.087, 3.445, -0.826]} scale={[1.45, 2, 1.45]} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials['Light Blue.002']} position={[2.817, 0, 0]} />
      <mesh geometry={nodes.CurlyCurve.geometry} material={materials['Light Blue.001']} position={[0.009, -1.271, -0.042]} rotation={[0.049, 0.014, 0.018]} scale={[1.304, 1.406, 1.304]} />
      <mesh geometry={nodes.Sphere003.geometry} material={materials['Light Blue.003']} position={[0, 2.47, 0]} />
      <mesh geometry={nodes.Sphere004.geometry} material={materials['Light Blue']} position={[0, 1.784, 0.585]} rotation={[0, 0, 0.018]} scale={[1.051, 1.562, 1.633]} />
      <mesh geometry={nodes.Sphere005.geometry} material={materials['Material.002']} position={[0.235, 1.574, -0.334]} rotation={[-0.492, 0.261, -0.465]} />
      <mesh geometry={nodes.Sphere006.geometry} material={materials['Material.003']} position={[0.664, -0.178, -0.667]} rotation={[-0.492, 0.261, -0.465]} />
      <mesh geometry={nodes.Sphere008.geometry} material={materials.white} position={[-0.683, -0.131, -0.228]} rotation={[-2.729, -0.299, 2.698]} />
      <mesh geometry={nodes.Sphere007.geometry} material={materials.white} position={[0.751, 0.013, -0.911]} rotation={[-0.408, 0.264, -0.459]} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/regular/856.glb')
