/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/86.glb -o models/gltfjsx/regular/86.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/86.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={2.54}>
        <group position={[0, 0.185, 0.055]} rotation={[1.379, 0, Math.PI / 2]}>
          <primitive object={nodes.Hips} />
          <primitive object={nodes.Spine1} />
        </group>
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
        <skinnedMesh geometry={nodes.Seel_1.geometry} material={materials.Body} skeleton={nodes.Seel_1.skeleton} />
        <skinnedMesh geometry={nodes.Seel_2.geometry} material={materials.Eye} skeleton={nodes.Seel_2.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/86.glb')
