/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/871.glb -o models/gltfjsx/regular/871.jsx 
Author: Squirmy Worm (https://sketchfab.com/squirmyworm064)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pincurchin-f604e7686bc8475abf85af6721bd00e0
Title: Pincurchin
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/871.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.color_15055427} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.color_15490603} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.color_16104991} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.color_16373882} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.color_16448250} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.color_16768282} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.color_3225146} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.color_5588052} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.color_7565690} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.color_8219780} />
      </group>
    </group>
  )
}

useGLTF.preload('/871.glb')
