/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/880.glb -o models/gltfjsx/regular/880.jsx 
Author: LunaEagle (https://sketchfab.com/LunaEagle)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dracozolt-3d84369880cb46ef863ccb2871fd9afe
Title: Dracozolt
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/880.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={1.549}>
          <group name="dracozolt_with_animationfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Armature" scale={50}>
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_102" scale={50} />
                    <skinnedMesh name="Object_103" geometry={nodes.Object_103.geometry} material={materials['pm0880_00_00-Body']} skeleton={nodes.Object_103.skeleton} />
                    <skinnedMesh name="Object_104" geometry={nodes.Object_104.geometry} material={materials['pm0880_00_00-BodyVco']} skeleton={nodes.Object_104.skeleton} />
                    <skinnedMesh name="Object_105" geometry={nodes.Object_105.geometry} material={materials['pm0880_00_00-Eye']} skeleton={nodes.Object_105.skeleton} />
                  </group>
                </group>
                <group name="pm0880_00_00_BodySkin" scale={50} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/880.glb')
