/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/885.glb -o models/gltfjsx/regular/885.jsx 
Author: theyre (https://sketchfab.com/theyre)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/unovan-dreepy-02be31875a3e49ed8470f4171b476b53
Title: Unovan Dreepy
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/regular/885.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.color_16768282} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.color_1962531} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.color_2005754} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.color_244223} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.color_2829873} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.color_3104391} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.color_3140447} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.color_3168348} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.color_3716501} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.color_3899832} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.color_3964215} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.color_3968698} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.color_40919} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.color_4634487} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.color_4635360} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.color_4645050} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.color_4694410} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.color_5832479} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.color_6273633} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.color_6731590} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.color_7246923} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.color_7711705} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.color_7720667} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.color_8768998} />
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/regular/885.glb')
