/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/888.glb -o models/gltfjsx/regular/888.jsx 
Author: User 37564 (https://sketchfab.com/rhl89ryo)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/zacian-armor-pokemon-sword-2b1ce8a0b18540cb82d2b88eb6f00f79
Title: Zacian (Armor) [Pokemon Sword]
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/regular/888.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.031}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 32.131, 67.426]} rotation={[-2.675, 0, Math.PI / 2]} scale={8.932}>
            <primitive object={nodes.GLTF_created_0_rootJoint} />
            <skinnedMesh geometry={nodes.Object_7.geometry} material={materials.Gold_2} skeleton={nodes.Object_7.skeleton} />
            <skinnedMesh geometry={nodes.Object_8.geometry} material={materials.Sword_Orenge} skeleton={nodes.Object_8.skeleton} />
            <skinnedMesh geometry={nodes.Object_9.geometry} material={materials.Sword_Blue} skeleton={nodes.Object_9.skeleton} />
          </group>
          <group position={[0, 43.763, 0]} rotation={[Math.PI / 2, 0, 0]} scale={13.597}>
            <primitive object={nodes.GLTF_created_1_rootJoint} />
            <skinnedMesh geometry={nodes.Object_15.geometry} material={materials.Body} skeleton={nodes.Object_15.skeleton} />
            <skinnedMesh geometry={nodes.Object_16.geometry} material={materials.Body_Color} skeleton={nodes.Object_16.skeleton} />
            <skinnedMesh geometry={nodes.Object_17.geometry} material={materials.Nail} skeleton={nodes.Object_17.skeleton} />
            <skinnedMesh geometry={nodes.Object_18.geometry} material={materials.Body_White} skeleton={nodes.Object_18.skeleton} />
            <skinnedMesh geometry={nodes.Object_19.geometry} material={materials.Mouth} skeleton={nodes.Object_19.skeleton} />
            <skinnedMesh geometry={nodes.Object_20.geometry} material={materials.Tooth} skeleton={nodes.Object_20.skeleton} />
            <skinnedMesh geometry={nodes.Object_21.geometry} material={materials.Body_Black} skeleton={nodes.Object_21.skeleton} />
            <skinnedMesh geometry={nodes.Object_22.geometry} material={materials.Gold_2} skeleton={nodes.Object_22.skeleton} />
            <skinnedMesh geometry={nodes.Object_24.geometry} material={materials.Gold} skeleton={nodes.Object_24.skeleton} />
            <skinnedMesh geometry={nodes.Object_25.geometry} material={materials.Body_Black} skeleton={nodes.Object_25.skeleton} />
            <skinnedMesh geometry={nodes.Object_27.geometry} material={materials.Eye_Black} skeleton={nodes.Object_27.skeleton} />
            <skinnedMesh geometry={nodes.Object_28.geometry} material={materials.Eye_White} skeleton={nodes.Object_28.skeleton} />
            <skinnedMesh geometry={nodes.Object_29.geometry} material={materials.Eye_Yellow} skeleton={nodes.Object_29.skeleton} />
            <skinnedMesh geometry={nodes.Object_30.geometry} material={materials.Eye_Olange} skeleton={nodes.Object_30.skeleton} />
            <skinnedMesh geometry={nodes.Object_31.geometry} material={materials.Eye_Alpha} skeleton={nodes.Object_31.skeleton} />
            <skinnedMesh geometry={nodes.Object_33.geometry} material={materials.Body} skeleton={nodes.Object_33.skeleton} />
            <skinnedMesh geometry={nodes.Object_35.geometry} material={materials.Hair_Color} skeleton={nodes.Object_35.skeleton} />
            <skinnedMesh geometry={nodes.Object_36.geometry} material={materials.Hair_Yellow} skeleton={nodes.Object_36.skeleton} />
            <skinnedMesh geometry={nodes.Object_38.geometry} material={materials.Gold} skeleton={nodes.Object_38.skeleton} />
            <skinnedMesh geometry={nodes.Object_39.geometry} material={materials.Body} skeleton={nodes.Object_39.skeleton} />
            <skinnedMesh geometry={nodes.Object_40.geometry} material={materials.Helm_Color} skeleton={nodes.Object_40.skeleton} />
            <skinnedMesh geometry={nodes.Object_42.geometry} material={materials.Body_Color} skeleton={nodes.Object_42.skeleton} />
            <skinnedMesh geometry={nodes.Object_44.geometry} material={materials.Body_Color} skeleton={nodes.Object_44.skeleton} />
            <skinnedMesh geometry={nodes.Object_46.geometry} material={materials.Tongue} skeleton={nodes.Object_46.skeleton} />
            <skinnedMesh geometry={nodes.Object_48.geometry} material={materials.Tooth} skeleton={nodes.Object_48.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/regular/888.glb')
