/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/889.glb -o models/gltfjsx/regular/889.jsx 
Author: User 37564 (https://sketchfab.com/rhl89ryo)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/zamazenta-armor-pokemon-shield-c55cbc938f4a4a40868732bf910d2140
Title: Zamazenta (Armor) [Pokemon Shield]
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/889.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, 5.31, -2.018]} scale={1.708}>
          <primitive object={nodes.GLTF_created_0_rootJoint} />
          <skinnedMesh geometry={nodes.Object_7.geometry} material={materials.Gold} skeleton={nodes.Object_7.skeleton} />
          <skinnedMesh geometry={nodes.Object_8.geometry} material={materials.Body_Black} skeleton={nodes.Object_8.skeleton} />
          <skinnedMesh geometry={nodes.Object_9.geometry} material={materials.Helm} skeleton={nodes.Object_9.skeleton} />
          <skinnedMesh geometry={nodes.Object_10.geometry} material={materials.Metal_Blue} skeleton={nodes.Object_10.skeleton} />
          <skinnedMesh geometry={nodes.Object_12.geometry} material={materials.Body} skeleton={nodes.Object_12.skeleton} />
          <skinnedMesh geometry={nodes.Object_13.geometry} material={materials.Body_Color} skeleton={nodes.Object_13.skeleton} />
          <skinnedMesh geometry={nodes.Object_14.geometry} material={materials.Nail} skeleton={nodes.Object_14.skeleton} />
          <skinnedMesh geometry={nodes.Object_15.geometry} material={materials.Body_White} skeleton={nodes.Object_15.skeleton} />
          <skinnedMesh geometry={nodes.Object_16.geometry} material={materials.Mouth} skeleton={nodes.Object_16.skeleton} />
          <skinnedMesh geometry={nodes.Object_17.geometry} material={materials.Tooth} skeleton={nodes.Object_17.skeleton} />
          <skinnedMesh geometry={nodes.Object_18.geometry} material={materials.Body_Black} skeleton={nodes.Object_18.skeleton} />
          <skinnedMesh geometry={nodes.Object_20.geometry} material={materials.Eye_Black} skeleton={nodes.Object_20.skeleton} />
          <skinnedMesh geometry={nodes.Object_21.geometry} material={materials.Eye_White} skeleton={nodes.Object_21.skeleton} />
          <skinnedMesh geometry={nodes.Object_22.geometry} material={materials.Eye_Yellow} skeleton={nodes.Object_22.skeleton} />
          <skinnedMesh geometry={nodes.Object_23.geometry} material={materials.Eye_Olange} skeleton={nodes.Object_23.skeleton} />
          <skinnedMesh geometry={nodes.Object_24.geometry} material={materials.Eye_Alpha} skeleton={nodes.Object_24.skeleton} />
          <skinnedMesh geometry={nodes.Object_26.geometry} material={materials.Body_Black} skeleton={nodes.Object_26.skeleton} />
          <skinnedMesh geometry={nodes.Object_28.geometry} material={materials.Body} skeleton={nodes.Object_28.skeleton} />
          <skinnedMesh geometry={nodes.Object_30.geometry} material={materials.Body_Black} skeleton={nodes.Object_30.skeleton} />
          <skinnedMesh geometry={nodes.Object_32.geometry} material={materials.Body_Color} skeleton={nodes.Object_32.skeleton} />
          <skinnedMesh geometry={nodes.Object_34.geometry} material={materials.Body_Color} skeleton={nodes.Object_34.skeleton} />
          <skinnedMesh geometry={nodes.Object_35.geometry} material={materials['Eye_Yellow.001']} skeleton={nodes.Object_35.skeleton} />
          <skinnedMesh geometry={nodes.Object_37.geometry} material={materials.Body_Color} skeleton={nodes.Object_37.skeleton} />
          <skinnedMesh geometry={nodes.Object_39.geometry} material={materials.Body_Color} skeleton={nodes.Object_39.skeleton} />
          <skinnedMesh geometry={nodes.Object_41.geometry} material={materials.Tongue} skeleton={nodes.Object_41.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/889.glb')
