/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/90.glb -o models/gltfjsx/regular/90.jsx 
Author: nguyenlouis32 (https://sketchfab.com/nguyenlouis32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shellder-807f309936ed4f6988bf169175f2f83c
Title: Shellder
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/90.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-0.001, 0, 0]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.BodySpc_mat_002} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.BodySpcVco_mat_002} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Body_mat_002} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.BodyVco_mat_002} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Eye_mat_002} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Eye_mat_002} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.BodyVco_mat_002} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.Body_mat_002} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.BodySpcVco_mat_002} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.BodySpc_mat_002} />
      </group>
    </group>
  )
}

useGLTF.preload('/90.glb')
