/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/905.glb -o models/gltfjsx/regular/905.jsx 
Author: Forsaken AR Official (https://sketchfab.com/FNAF_AR_Official)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mobile-pokemon-home-905-enamorus-incarnate-f-e1bee4db658c4dde8212dce2375dd281
Title: Mobile - Pokemon HOME - 905 Enamorus Incarnate F
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/regular/905.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="enamorus_incarnate_with_animationfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Armature" scale={50}>
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_174" scale={50} />
                    <group name="Object_176" scale={50} />
                    <group name="Object_178" scale={50} />
                    <group name="Object_180" scale={50} />
                    <skinnedMesh name="Object_175" geometry={nodes.Object_175.geometry} material={materials['pm0905_11_00-BodyB']} skeleton={nodes.Object_175.skeleton} />
                    <skinnedMesh name="Object_177" geometry={nodes.Object_177.geometry} material={materials['pm0905_11_00-BodyBInc']} skeleton={nodes.Object_177.skeleton} />
                    <skinnedMesh name="Object_179" geometry={nodes.Object_179.geometry} material={materials['pm0905_11_00-BodyA']} skeleton={nodes.Object_179.skeleton} />
                    <skinnedMesh name="Object_181" geometry={nodes.Object_181.geometry} material={materials['pm0905_11_00-BodyA']} skeleton={nodes.Object_181.skeleton} />
                    <skinnedMesh name="Object_182" geometry={nodes.Object_182.geometry} material={materials['pm0905_11_00-LEye']} skeleton={nodes.Object_182.skeleton} />
                    <skinnedMesh name="Object_183" geometry={nodes.Object_183.geometry} material={materials['pm0905_11_00-REye']} skeleton={nodes.Object_183.skeleton} />
                  </group>
                </group>
                <group name="pm0905_11_00_CloudSkin" scale={50} />
                <group name="pm0905_11_00_TailSkin" scale={50} />
                <group name="pm0905_11_00_HairMesh" scale={50} />
                <group name="pm0905_11_00_BodySkin" scale={50} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/regular/905.glb')
