/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/906.glb -o models/gltfjsx/regular/906.jsx 
Author: Squirmy Worm (https://sketchfab.com/squirmyworm064)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sprigatito-f479fde14dee41678892cb192f7eecac
Title: Sprigatito
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/906.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.color_13762494} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.color_16448250} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.color_16751009} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.color_16755905} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.color_2829873} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.color_5630758} />
      </group>
    </group>
  )
}

useGLTF.preload('/906.glb')
