/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/917.glb -o models/gltfjsx/regular/917.jsx 
Author: Squirmy Worm (https://sketchfab.com/squirmyworm064)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tarountula-51350d7395e943c68b01fd593fefd09c
Title: Tarountula
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/regular/917.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.color_14541540} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.color_15724527} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.color_16448250} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.color_16645991} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.color_16777215} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.color_3173499} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.color_4700734} />
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/regular/917.glb')
