/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/920.glb -o models/gltfjsx/regular/920.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/920.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]}>
          <primitive object={nodes['pm920_(merge)']} />
          <skinnedMesh name="pm0920_00_CombinedOnExport" geometry={nodes.pm0920_00_CombinedOnExport.geometry} material={materials.Body} skeleton={nodes.pm0920_00_CombinedOnExport.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/920.glb')
