/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/925.glb -o models/gltfjsx/regular/925.jsx 
Author: JojoTZ (https://sketchfab.com/JojoTZ)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/maushold-from-pokemon-scarlet-violet-c9a689709c2c499bb784012c21499262
Title: Maushold from Pokémon Scarlet & Violet
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/regular/925.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.hands_f_maus_0.geometry} material={materials.f_maus} />
        <mesh geometry={nodes.body_f_maus_0.geometry} material={materials.f_maus} />
        <mesh geometry={nodes.tail_f_maus_0.geometry} material={materials.f_maus} />
        <mesh geometry={nodes.ball_f_maus_0.geometry} material={materials.f_maus} />
        <mesh geometry={nodes.head_f_maus_0.geometry} material={materials.f_maus} />
        <mesh geometry={nodes.ear2_f_maus_0.geometry} material={materials.f_maus} />
        <mesh geometry={nodes.ear1_f_maus_0.geometry} material={materials.f_maus} />
        <mesh geometry={nodes.eye1_f_maus_0.geometry} material={materials.f_maus} />
        <mesh geometry={nodes.eye2_f_maus_0.geometry} material={materials.f_maus} />
        <mesh geometry={nodes.nose_f_maus_0.geometry} material={materials.f_maus} />
        <mesh geometry={nodes.hands_m_maus_0.geometry} material={materials.m_maus} />
        <mesh geometry={nodes.body_m_maus_0.geometry} material={materials.m_maus} />
        <mesh geometry={nodes.tail_m_maus_0.geometry} material={materials.m_maus} />
        <mesh geometry={nodes.ball_m_maus_0.geometry} material={materials.m_maus} />
        <mesh geometry={nodes.head_m_maus_0.geometry} material={materials.m_maus} />
        <mesh geometry={nodes.ear1_m_maus_0.geometry} material={materials.m_maus} />
        <mesh geometry={nodes.ear2_m_maus_0.geometry} material={materials.m_maus} />
        <mesh geometry={nodes.eye1_m_maus_0.geometry} material={materials.m_maus} />
        <mesh geometry={nodes.eye2_m_maus_0.geometry} material={materials.m_maus} />
        <mesh geometry={nodes.nose_m_maus_0.geometry} material={materials.m_maus} />
        <mesh geometry={nodes.tail_bb_maus_0.geometry} material={materials.bb_maus} />
        <mesh geometry={nodes.body_bb_maus_0.geometry} material={materials.bb_maus} />
        <mesh geometry={nodes.head_bb_maus_0.geometry} material={materials.bb_maus} />
        <mesh geometry={nodes.eye3_bb_maus_0.geometry} material={materials.bb_maus} />
        <mesh geometry={nodes.nose_bb_maus_0.geometry} material={materials.bb_maus} />
        <mesh geometry={nodes.eye4_bb_maus_0.geometry} material={materials.bb_maus} />
        <mesh geometry={nodes.tail_bb_maus_0_1.geometry} material={materials.bb_maus} />
        <mesh geometry={nodes.body_bb_maus_0_1.geometry} material={materials.bb_maus} />
        <mesh geometry={nodes.head_bb_maus_0_1.geometry} material={materials.bb_maus} />
        <mesh geometry={nodes.eye3_bb_maus_0_1.geometry} material={materials.bb_maus} />
        <mesh geometry={nodes.eye4_bb_maus_0_1.geometry} material={materials.bb_maus} />
        <mesh geometry={nodes.nose_bb_maus_0_1.geometry} material={materials.bb_maus} />
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/regular/925.glb')
