/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/926.glb -o models/gltfjsx/regular/926.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const { scene } = useGLTF('/926.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.025}>
        <primitive object={nodes.pm1074_00_00} />
        <skinnedMesh geometry={nodes.pm1074_00_00_head_mesh_shape.geometry} material={materials.body_00} skeleton={nodes.pm1074_00_00_head_mesh_shape.skeleton} />
        <skinnedMesh geometry={nodes.pm1074_00_00_head_mesh_shape_lod1.geometry} material={materials.body_00} skeleton={nodes.pm1074_00_00_head_mesh_shape_lod1.skeleton} />
        <skinnedMesh geometry={nodes.pm1074_00_00_head_mesh_shape_lod2.geometry} material={materials.body_00} skeleton={nodes.pm1074_00_00_head_mesh_shape_lod2.skeleton} />
        <skinnedMesh geometry={nodes.Mesh001.geometry} material={materials.body_00} skeleton={nodes.Mesh001.skeleton} />
        <skinnedMesh geometry={nodes.Mesh001_1.geometry} material={materials.body_01} skeleton={nodes.Mesh001_1.skeleton} />
        <skinnedMesh geometry={nodes.Mesh004.geometry} material={materials.body_00} skeleton={nodes.Mesh004.skeleton} />
        <skinnedMesh geometry={nodes.Mesh004_1.geometry} material={materials.body_01} skeleton={nodes.Mesh004_1.skeleton} />
        <skinnedMesh geometry={nodes.Mesh007.geometry} material={materials.body_00} skeleton={nodes.Mesh007.skeleton} />
        <skinnedMesh geometry={nodes.Mesh007_1.geometry} material={materials.body_01} skeleton={nodes.Mesh007_1.skeleton} />
        <skinnedMesh geometry={nodes.Mesh002.geometry} material={materials.r_eye} skeleton={nodes.Mesh002.skeleton} />
        <skinnedMesh geometry={nodes.Mesh002_1.geometry} material={materials.l_eye} skeleton={nodes.Mesh002_1.skeleton} />
        <skinnedMesh geometry={nodes.Mesh005.geometry} material={materials.r_eye} skeleton={nodes.Mesh005.skeleton} />
        <skinnedMesh geometry={nodes.Mesh005_1.geometry} material={materials.l_eye} skeleton={nodes.Mesh005_1.skeleton} />
        <skinnedMesh geometry={nodes.Mesh008.geometry} material={materials.r_eye} skeleton={nodes.Mesh008.skeleton} />
        <skinnedMesh geometry={nodes.Mesh008_1.geometry} material={materials.l_eye} skeleton={nodes.Mesh008_1.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/926.glb')
