/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/927.glb -o models/gltfjsx/regular/927.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/regular/927.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.025}>
        <primitive object={nodes.pm1075_00_00} />
        <skinnedMesh geometry={nodes.pm1075_00_00_ear_mesh_shape.geometry} material={materials.body_b} skeleton={nodes.pm1075_00_00_ear_mesh_shape.skeleton} />
        <skinnedMesh geometry={nodes.pm1075_00_00_ear_mesh_shape_lod1.geometry} material={materials.body_b} skeleton={nodes.pm1075_00_00_ear_mesh_shape_lod1.skeleton} />
        <skinnedMesh geometry={nodes.pm1075_00_00_ear_mesh_shape_lod2.geometry} material={materials.body_b} skeleton={nodes.pm1075_00_00_ear_mesh_shape_lod2.skeleton} />
        <skinnedMesh geometry={nodes.Mesh.geometry} material={materials.body_a_01} skeleton={nodes.Mesh.skeleton} />
        <skinnedMesh geometry={nodes.Mesh_1.geometry} material={materials.body_a_02} skeleton={nodes.Mesh_1.skeleton} />
        <skinnedMesh geometry={nodes.Mesh005.geometry} material={materials.body_a_01} skeleton={nodes.Mesh005.skeleton} />
        <skinnedMesh geometry={nodes.Mesh005_1.geometry} material={materials.body_a_02} skeleton={nodes.Mesh005_1.skeleton} />
        <skinnedMesh geometry={nodes.Mesh010.geometry} material={materials.body_a_01} skeleton={nodes.Mesh010.skeleton} />
        <skinnedMesh geometry={nodes.Mesh010_1.geometry} material={materials.body_a_02} skeleton={nodes.Mesh010_1.skeleton} />
        <skinnedMesh geometry={nodes.Mesh001.geometry} material={materials.body_a_02} skeleton={nodes.Mesh001.skeleton} />
        <skinnedMesh geometry={nodes.Mesh001_1.geometry} material={materials.body_b} skeleton={nodes.Mesh001_1.skeleton} />
        <skinnedMesh geometry={nodes.Mesh006.geometry} material={materials.body_a_02} skeleton={nodes.Mesh006.skeleton} />
        <skinnedMesh geometry={nodes.Mesh006_1.geometry} material={materials.body_b} skeleton={nodes.Mesh006_1.skeleton} />
        <skinnedMesh geometry={nodes.Mesh011.geometry} material={materials.body_a_02} skeleton={nodes.Mesh011.skeleton} />
        <skinnedMesh geometry={nodes.Mesh011_1.geometry} material={materials.body_b} skeleton={nodes.Mesh011_1.skeleton} />
        <skinnedMesh geometry={nodes.Mesh004.geometry} material={materials.l_eye} skeleton={nodes.Mesh004.skeleton} />
        <skinnedMesh geometry={nodes.Mesh004_1.geometry} material={materials.r_eye} skeleton={nodes.Mesh004_1.skeleton} />
        <skinnedMesh geometry={nodes.Mesh009.geometry} material={materials.l_eye} skeleton={nodes.Mesh009.skeleton} />
        <skinnedMesh geometry={nodes.Mesh009_1.geometry} material={materials.r_eye} skeleton={nodes.Mesh009_1.skeleton} />
        <skinnedMesh geometry={nodes.Mesh014.geometry} material={materials.l_eye} skeleton={nodes.Mesh014.skeleton} />
        <skinnedMesh geometry={nodes.Mesh014_1.geometry} material={materials.r_eye} skeleton={nodes.Mesh014_1.skeleton} />
        <skinnedMesh geometry={nodes.Mesh003.geometry} material={materials.body_a_01} skeleton={nodes.Mesh003.skeleton} />
        <skinnedMesh geometry={nodes.Mesh003_1.geometry} material={materials.body_a_02} skeleton={nodes.Mesh003_1.skeleton} />
        <skinnedMesh geometry={nodes.Mesh008.geometry} material={materials.body_a_01} skeleton={nodes.Mesh008.skeleton} />
        <skinnedMesh geometry={nodes.Mesh008_1.geometry} material={materials.body_a_02} skeleton={nodes.Mesh008_1.skeleton} />
        <skinnedMesh geometry={nodes.Mesh012.geometry} material={materials.body_a_01} skeleton={nodes.Mesh012.skeleton} />
        <skinnedMesh geometry={nodes.Mesh012_1.geometry} material={materials.body_a_02} skeleton={nodes.Mesh012_1.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/regular/927.glb')
