/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/928.glb -o models/gltfjsx/regular/928.jsx 
Author: Squirmy Worm (https://sketchfab.com/squirmyworm064)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/smoliv-20-40175da5f79849c989035ac009acd4a3
Title: Smoliv 2.0
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/928.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.color_0} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.color_12123982} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.color_15335242} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.color_16448250} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.color_2829873} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.color_7592251} />
      </group>
    </group>
  )
}

useGLTF.preload('/928.glb')
