/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/930.glb -o models/gltfjsx/regular/930.jsx 
Author: Squirmy Worm (https://sketchfab.com/squirmyworm064)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/arboliva-046da14f103b4c78b0e70aeb4ba6c0d4
Title: Arboliva
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/regular/930.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.color_12163440} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.color_16711649} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.color_2829873} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.color_3200571} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.color_5516648} />
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/regular/930.glb')
