/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/94.glb -o models/gltfjsx/regular/94.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const { scene } = useGLTF('/94.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={2.54}>
        <group position={[0, 0.54, -0.239]} rotation={[0, 0, Math.PI / 2]}>
          <primitive object={nodes.Hips} />
          <primitive object={nodes.Head} />
        </group>
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
        <skinnedMesh geometry={nodes.Gengar_1.geometry} material={materials['Material #10']} skeleton={nodes.Gengar_1.skeleton} />
        <skinnedMesh geometry={nodes.Gengar_2.geometry} material={materials['Material #11']} skeleton={nodes.Gengar_2.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/94.glb')
