/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/945.glb -o models/gltfjsx/regular/945.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const { scene } = useGLTF('/945.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.025}>
        <primitive object={nodes.pm1073_00_00} />
        <skinnedMesh geometry={nodes.pm1073_00_00_hair_mesh_shape.geometry} material={materials.body_a_01} skeleton={nodes.pm1073_00_00_hair_mesh_shape.skeleton} />
        <skinnedMesh geometry={nodes.pm1073_00_00_hair_mesh_shape_lod1.geometry} material={materials.body_a_01} skeleton={nodes.pm1073_00_00_hair_mesh_shape_lod1.skeleton} />
        <skinnedMesh geometry={nodes.pm1073_00_00_hair_mesh_shape_lod2.geometry} material={materials.body_a_01} skeleton={nodes.pm1073_00_00_hair_mesh_shape_lod2.skeleton} />
        <skinnedMesh geometry={nodes.pm1073_00_00_head_mesh_shape.geometry} material={materials.body_a_00} skeleton={nodes.pm1073_00_00_head_mesh_shape.skeleton} />
        <skinnedMesh geometry={nodes.pm1073_00_00_head_mesh_shape_lod1.geometry} material={materials.body_a_00} skeleton={nodes.pm1073_00_00_head_mesh_shape_lod1.skeleton} />
        <skinnedMesh geometry={nodes.pm1073_00_00_head_mesh_shape_lod2.geometry} material={materials.body_a_00} skeleton={nodes.pm1073_00_00_head_mesh_shape_lod2.skeleton} />
        <skinnedMesh geometry={nodes.pm1073_00_00_teeth_mesh_shape.geometry} material={materials.body_a_02} skeleton={nodes.pm1073_00_00_teeth_mesh_shape.skeleton} />
        <skinnedMesh geometry={nodes.pm1073_00_00_teeth_mesh_shape_lod1.geometry} material={materials.body_a_02} skeleton={nodes.pm1073_00_00_teeth_mesh_shape_lod1.skeleton} />
        <skinnedMesh geometry={nodes.pm1073_00_00_teeth_mesh_shape_lod2.geometry} material={materials.body_a_02} skeleton={nodes.pm1073_00_00_teeth_mesh_shape_lod2.skeleton} />
        <skinnedMesh geometry={nodes.Mesh001.geometry} material={materials.body_a_01} skeleton={nodes.Mesh001.skeleton} />
        <skinnedMesh geometry={nodes.Mesh001_1.geometry} material={materials.body_b_00} skeleton={nodes.Mesh001_1.skeleton} />
        <skinnedMesh geometry={nodes.Mesh001_2.geometry} material={materials.body_b_01} skeleton={nodes.Mesh001_2.skeleton} />
        <skinnedMesh geometry={nodes.Mesh007.geometry} material={materials.body_a_01} skeleton={nodes.Mesh007.skeleton} />
        <skinnedMesh geometry={nodes.Mesh007_1.geometry} material={materials.body_b_00} skeleton={nodes.Mesh007_1.skeleton} />
        <skinnedMesh geometry={nodes.Mesh007_2.geometry} material={materials.body_b_01} skeleton={nodes.Mesh007_2.skeleton} />
        <skinnedMesh geometry={nodes.Mesh013.geometry} material={materials.body_a_01} skeleton={nodes.Mesh013.skeleton} />
        <skinnedMesh geometry={nodes.Mesh013_1.geometry} material={materials.body_b_00} skeleton={nodes.Mesh013_1.skeleton} />
        <skinnedMesh geometry={nodes.Mesh013_2.geometry} material={materials.body_b_01} skeleton={nodes.Mesh013_2.skeleton} />
        <skinnedMesh geometry={nodes.Mesh004.geometry} material={materials.r_eye} skeleton={nodes.Mesh004.skeleton} />
        <skinnedMesh geometry={nodes.Mesh004_1.geometry} material={materials.l_eye} skeleton={nodes.Mesh004_1.skeleton} />
        <skinnedMesh geometry={nodes.Mesh010.geometry} material={materials.r_eye} skeleton={nodes.Mesh010.skeleton} />
        <skinnedMesh geometry={nodes.Mesh010_1.geometry} material={materials.l_eye} skeleton={nodes.Mesh010_1.skeleton} />
        <skinnedMesh geometry={nodes.Mesh016.geometry} material={materials.r_eye} skeleton={nodes.Mesh016.skeleton} />
        <skinnedMesh geometry={nodes.Mesh016_1.geometry} material={materials.l_eye} skeleton={nodes.Mesh016_1.skeleton} />
        <skinnedMesh geometry={nodes.Mesh002.geometry} material={materials.body_a_00} skeleton={nodes.Mesh002.skeleton} />
        <skinnedMesh geometry={nodes.Mesh002_1.geometry} material={materials.body_a_02} skeleton={nodes.Mesh002_1.skeleton} />
        <skinnedMesh geometry={nodes.Mesh008.geometry} material={materials.body_a_00} skeleton={nodes.Mesh008.skeleton} />
        <skinnedMesh geometry={nodes.Mesh008_1.geometry} material={materials.body_a_02} skeleton={nodes.Mesh008_1.skeleton} />
        <skinnedMesh geometry={nodes.Mesh014.geometry} material={materials.body_a_00} skeleton={nodes.Mesh014.skeleton} />
        <skinnedMesh geometry={nodes.Mesh014_1.geometry} material={materials.body_a_02} skeleton={nodes.Mesh014_1.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/945.glb')
