/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/948.glb -o models/gltfjsx/regular/948.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/948.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={2.54}>
        <primitive object={nodes['003_Waist']} />
        <skinnedMesh geometry={nodes.Tentacool_1.geometry} material={materials.BodyTattu00} skeleton={nodes.Tentacool_1.skeleton} />
        <skinnedMesh geometry={nodes.Tentacool_2.geometry} material={materials.Eye} skeleton={nodes.Tentacool_2.skeleton} />
        <skinnedMesh geometry={nodes.Tentacool_3.geometry} material={materials.Yellow} skeleton={nodes.Tentacool_3.skeleton} />
        <skinnedMesh geometry={nodes.Tentacool_4.geometry} material={materials.Peach} skeleton={nodes.Tentacool_4.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/948.glb')
