/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/960.glb -o models/gltfjsx/regular/960.jsx 
Author: Squirmy Worm (https://sketchfab.com/squirmyworm064)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wiglett-734a840e6de04bea8ba4682af37782b1
Title: Wiglett
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/regular/960.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.color_16448250} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.color_16731754} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.color_2829873} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.color_6402985} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.color_9556176} />
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/regular/960.glb')
