/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/966.glb -o models/gltfjsx/regular/966.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/966.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pm1047_00_00_eyelid_mesh_shape.geometry} material={materials.body_a_01} rotation={[3.03, 0, 0]} />
      <group rotation={[3.03, 0, 0]}>
        <mesh geometry={nodes.pm1047_00_00_face_mesh_shape_1.geometry} material={materials.body_a_00} />
        <mesh geometry={nodes.pm1047_00_00_face_mesh_shape_2.geometry} material={materials.eye} />
      </group>
      <mesh geometry={nodes.pm1047_00_00_head_mesh_shape.geometry} material={materials.body_a_00} rotation={[3.03, 0, 0]} />
      <mesh geometry={nodes.pm1047_00_00_jaw_mesh_shape.geometry} material={materials.body_a_00} rotation={[3.03, 0, 0]} />
      <mesh geometry={nodes.pm1047_00_00_muffler_mesh_shape.geometry} material={materials.body_a_00} rotation={[3.03, 0, 0]} />
      <mesh geometry={nodes.pm1047_00_00_stone_a_mesh_shape.geometry} material={materials.body_b} rotation={[3.03, 0, 0]} />
      <mesh geometry={nodes.pm1047_00_00_stone_b_mesh_shape.geometry} material={materials.body_b} rotation={[3.03, 0, 0]} />
      <mesh geometry={nodes.pm1047_00_00_stone_c_mesh_shape.geometry} material={materials.body_b} rotation={[3.03, 0, 0]} />
      <mesh geometry={nodes.pm1047_00_00_stone_d_mesh_shape.geometry} material={materials.body_b} rotation={[3.03, 0, 0]} />
      <mesh geometry={nodes.pm1047_00_00_tongue_mesh_shape.geometry} material={materials.body_a_01} rotation={[3.03, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/966.glb')
