/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/990.glb -o models/gltfjsx/regular/990.jsx 
Author: Graveyart (https://sketchfab.com/GraveyArt)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/iron-treads-pokemon-d5e6f31fce1a47ac9f8eb8c8fd193ac5
Title: Iron Treads - Pokémon
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/990.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.pSphere4_blinn2_0.geometry} material={materials.blinn2} position={[0.764, -0.85, 0.291]} rotation={[-0.089, -0.112, 0.191]} scale={0.191} />
        <group position={[0.764, -0.85, 0.291]} rotation={[-0.089, -0.112, 0.191]} scale={0.191}>
          <mesh geometry={nodes.pSphere6_blinn2_0.geometry} material={materials.blinn2} position={[0.159, -0.031, -0.018]} />
        </group>
        <mesh geometry={nodes.pCube2_blinn3_0.geometry} material={materials.blinn3} position={[0.839, -1.003, 0.301]} rotation={[-0.016, -0.391, -0.059]} scale={[0.048, 0.709, 0.36]} />
        <mesh geometry={nodes.pCube5_blinn3_0.geometry} material={materials.blinn3} position={[0.839, -1.003, 0.301]} rotation={[-0.016, -0.391, -0.059]} scale={[0.048, 0.709, 0.36]} />
        <mesh geometry={nodes.pCone2_blinn2_0.geometry} material={materials.blinn2} position={[0.97, 0.126, 1.414]} rotation={[0.253, -0.926, -0.011]} scale={[0.007, 0.083, 0.007]} />
        <group position={[0, 0.931, 0]} scale={[1, 0.361, 1]}>
          <mesh geometry={nodes.pCube7_blinn2_0.geometry} material={materials.blinn2} />
          <mesh geometry={nodes.pCube7_blinn1_0.geometry} material={materials.blinn1} />
        </group>
        <mesh geometry={nodes.pCube9_blinn2_0.geometry} material={materials.blinn2} position={[1.569, 0.566, -0.232]} rotation={[0, 0, -0.086]} scale={[0.52, 0.05, 0.438]} />
        <mesh geometry={nodes.pCylinder2_blinn2_0.geometry} material={materials.blinn2} position={[0.773, 0.577, -0.226]} scale={[0.131, 0.131, 0.047]} />
        <mesh geometry={nodes.pSphere1_blinn3_0.geometry} material={materials.blinn3} />
        <mesh geometry={nodes.pSphere2_blinn3_0.geometry} material={materials.blinn3} position={[0, 0, 0.911]} scale={[0.399, 0.399, 0.346]} />
        <mesh geometry={nodes.pSphere8_blinn2_0.geometry} material={materials.blinn2} position={[0.764, -0.85, 0.291]} rotation={[-0.089, -0.112, 0.191]} scale={0.191} />
        <mesh geometry={nodes.pSphere9_blinn2_0.geometry} material={materials.blinn2} position={[0.764, -0.85, 0.291]} rotation={[-0.089, -0.112, 0.191]} scale={0.191} />
        <mesh geometry={nodes.pCube4_blinn3_0.geometry} material={materials.blinn3} position={[0.839, -1.003, 0.301]} rotation={[-0.016, -0.391, -0.059]} scale={[0.048, 0.709, 0.36]} />
        <mesh geometry={nodes.pCube6_blinn3_0.geometry} material={materials.blinn3} position={[0.839, -1.003, 0.301]} rotation={[-0.016, -0.391, -0.059]} scale={[0.048, 0.709, 0.36]} />
        <mesh geometry={nodes.pCone3_blinn2_0.geometry} material={materials.blinn2} position={[0.97, 0.126, 1.414]} rotation={[0.253, -0.926, -0.011]} scale={[0.007, 0.083, 0.007]} />
        <mesh geometry={nodes.pCube10_blinn2_0.geometry} material={materials.blinn2} position={[1.569, 0.566, -0.232]} rotation={[0, 0, -0.086]} scale={[0.52, 0.05, 0.438]} />
      </group>
    </group>
  )
}

useGLTF.preload('/990.glb')
