/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/regular/996.glb -o models/gltfjsx/regular/996.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/996.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]}>
          <primitive object={nodes['pm996_(merge)']} />
          <group name="pm0996_00_BodySkin">
            <skinnedMesh name="pm0996_00_BodySkin001" geometry={nodes.pm0996_00_BodySkin001.geometry} material={materials['Body.001']} skeleton={nodes.pm0996_00_BodySkin001.skeleton} />
            <skinnedMesh name="pm0996_00_BodySkin001_1" geometry={nodes.pm0996_00_BodySkin001_1.geometry} material={materials['Material.002']} skeleton={nodes.pm0996_00_BodySkin001_1.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/996.glb')
