/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/alolan/103.glb -o models/gltfjsx/alolan/103.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const { scene } = useGLTF('/103.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.036, 0]} rotation={[Math.PI, 0, 0]} scale={0.025}>
        <primitive object={nodes.Trans} />
        <skinnedMesh geometry={nodes.GamemodelShape.geometry} material={materials.nassya} skeleton={nodes.GamemodelShape.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/103.glb')
