/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 19.glb -o ../../gltfjsx/alolan/19.jsx 
Author: anak3d (https://sketchfab.com/anak3d1234)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/0019-rattata-alola-3d-0d0ddd2619624594841f9eaeba8077b0
Title: 0019 Rattata alola 3D
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/alolan/19.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={3.822}>
          <group name="7bcd9f66966f4aa98e37263fa1b282d9fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="rattata002" position={[6.404, -3.655, -8.848]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={61.154} />
                <group name="rattata003" position={[6.404, -3.655, -8.848]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={126.25}>
                  <group name="Object_6">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_8" position={[6.404, -3.655, -8.848]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={61.154} />
                    <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.rattata_alola} skeleton={nodes.Object_9.skeleton} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/alolan/19.glb')
