/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/alolan/37.glb -o models/gltfjsx/alolan/37.jsx 
Author: LunaEagle (https://sketchfab.com/LunaEagle)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/vulpix-alolan-f8daf750af174080b28901298e307fd8
Title: Vulpix Alolan
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/37.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.BodyB_mat_004} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.BodyA_mat_004} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Eye_mat_003} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.BodyC_mat_003} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.BodyC_mat_003} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Eye_mat_003} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.BodyA_mat_004} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.BodyB_mat_004} />
      </group>
    </group>
  )
}

useGLTF.preload('/37.glb')
