/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/alolan/50.glb -o models/gltfjsx/alolan/50.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const { scene } = useGLTF('/50.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group position={[-0.059, -0.056, -0.031]} rotation={[Math.PI / 2, 0, 0]} scale={0.185}>
        <primitive object={nodes.pm0050_61} />
        <skinnedMesh geometry={nodes.pm0050_61_StoneSkin.geometry} material={materials.BodyB} skeleton={nodes.pm0050_61_StoneSkin.skeleton} />
        <skinnedMesh geometry={nodes.pm0050_61_BodySkin_2.geometry} material={materials['Eye.001']} skeleton={nodes.pm0050_61_BodySkin_2.skeleton} />
        <skinnedMesh geometry={nodes.pm0050_61_BodySkin_3.geometry} material={materials.BodyA01} skeleton={nodes.pm0050_61_BodySkin_3.skeleton} />
        <skinnedMesh geometry={nodes.pm0050_61_BodySkin_4.geometry} material={materials.BodyA00} skeleton={nodes.pm0050_61_BodySkin_4.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/50.glb')
