/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/alolan/88.glb -o models/gltfjsx/alolan/88.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/regular/88.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pm0088_00_11_body_mesh_shape_body_00.geometry} material={materials.body_00} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.pm0088_00_11_body_mesh_shape_body_01.geometry} material={materials.body_01} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.pm0088_00_11_eye_mesh_shape_l_eye.geometry} material={materials['l_eye.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.pm0088_00_11_eye_mesh_shape_r_eye.geometry} material={materials['r_eye.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.pm0088_00_11_left_teeth_mesh_shape_body_01.geometry} material={materials.body_01} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.pm0088_00_11_liquid_a_mesh_shape_body_00.geometry} material={materials.body_00} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.pm0088_00_11_liquid_b_mesh_shape_body_00.geometry} material={materials.body_00} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.pm0088_00_11_right_teeth_mesh_shape_body_01.geometry} material={materials.body_01} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/regular/88.glb')
