/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/multiForm/ArchaludonCharging.glb -o models/gltfjsx/multiForm/ArchaludonCharging.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ArchaludonCharging.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.015, 0.027, 0.355]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.pm1132_00_00_right_hand_mesh_shape_mesh.geometry} material={materials.body_b_01} />
        <mesh geometry={nodes.pm1132_00_00_right_hand_mesh_shape_mesh_1.geometry} material={materials.body_b_00} />
      </group>
      <group position={[0.015, 0.027, 0.355]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.pm1132_00_00_body_b_mesh_shape_mesh.geometry} material={materials.body_b_01} />
        <mesh geometry={nodes.pm1132_00_00_body_b_mesh_shape_mesh_1.geometry} material={materials.body_b_00} />
      </group>
      <group position={[0.015, 0.027, 0.355]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.pm1132_00_00_left_hand_mesh_shape_mesh.geometry} material={materials.body_b_01} />
        <mesh geometry={nodes.pm1132_00_00_left_hand_mesh_shape_mesh_1.geometry} material={materials.body_b_00} />
      </group>
      <group position={[0.015, 0.027, 0.355]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.pm1132_00_00_effect_a_mesh_shape_mesh.geometry} material={materials.eff_a_01} />
        <mesh geometry={nodes.pm1132_00_00_effect_a_mesh_shape_mesh_1.geometry} material={materials.eff_a_00} />
      </group>
      <group position={[0.008, 0.045, -1.011]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.pm1132_00_00_right_hand_mesh_shape_mesh001.geometry} material={materials.body_b_01} />
        <mesh geometry={nodes.pm1132_00_00_right_hand_mesh_shape_mesh001_1.geometry} material={materials.body_b_00} />
      </group>
      <group position={[0.008, 0.045, -1.011]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.pm1132_00_00_left_hand_mesh_shape_mesh001.geometry} material={materials.body_b_01} />
        <mesh geometry={nodes.pm1132_00_00_left_hand_mesh_shape_mesh001_1.geometry} material={materials.body_b_00} />
      </group>
    </group>
  )
}

useGLTF.preload('/ArchaludonCharging.glb')
