/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/multiForm/EnamorusTherian.glb -o models/gltfjsx/multiForm/EnamorusTherian.jsx 
Author: Forsaken AR Official (https://sketchfab.com/FNAF_AR_Official)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mobile-pokemon-home-905-enamorus-therian-for-37951243d06e447f915a529062c933f8
Title: Mobile - Pokemon HOME - 905 Enamorus Therian For
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/EnamorusTherian.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="enamorus_therian_with_animationfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Armature" scale={50}>
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_226" scale={50} />
                    <group name="Object_228" scale={50} />
                    <group name="Object_232" scale={50} />
                    <group name="Object_234" scale={50} />
                    <group name="Object_236" scale={50} />
                    <skinnedMesh name="Object_227" geometry={nodes.Object_227.geometry} material={materials['pm0905_12_00-BodyB']} skeleton={nodes.Object_227.skeleton} />
                    <skinnedMesh name="Object_229" geometry={nodes.Object_229.geometry} material={materials['pm0905_12_00-BodyA']} skeleton={nodes.Object_229.skeleton} />
                    <skinnedMesh name="Object_230" geometry={nodes.Object_230.geometry} material={materials['pm0905_12_00-REye']} skeleton={nodes.Object_230.skeleton} />
                    <skinnedMesh name="Object_231" geometry={nodes.Object_231.geometry} material={materials['pm0905_12_00-LEye']} skeleton={nodes.Object_231.skeleton} />
                    <skinnedMesh name="Object_233" geometry={nodes.Object_233.geometry} material={materials['pm0905_12_00-BodyA']} skeleton={nodes.Object_233.skeleton} />
                    <skinnedMesh name="Object_235" geometry={nodes.Object_235.geometry} material={materials['pm0905_12_00-BodyA']} skeleton={nodes.Object_235.skeleton} />
                    <skinnedMesh name="Object_237" geometry={nodes.Object_237.geometry} material={materials['pm0905_12_00-BodyB']} skeleton={nodes.Object_237.skeleton} />
                  </group>
                </group>
                <group name="pm0905_12_00_TailBSkin" scale={50} />
                <group name="pm0905_12_00_BodySkin" scale={50} />
                <group name="pm0905_12_00_LegSkin" scale={50} />
                <group name="pm0905_12_00_CloudSkin" scale={50} />
                <group name="pm0905_12_00_TailASkin" scale={50} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/EnamorusTherian.glb')
