/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/multiForm/RotomMow.glb -o models/gltfjsx/multiForm/RotomMow.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/RotomMow.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty" position={[-6.569, 2.917, -0.712]} rotation={[1.117, 0.049, -0.099]} />
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.124}>
          <primitive object={nodes.pm0479_16_00_prefab} />
          <group name="_004_pm0479_16_00_prefab" />
          <skinnedMesh name="_000_pm0479_16_00_prefab" geometry={nodes._000_pm0479_16_00_prefab.geometry} material={materials.pm0479_16_00_BodyRotom} skeleton={nodes._000_pm0479_16_00_prefab.skeleton} />
          <skinnedMesh name="_001_pm0479_16_00_prefab" geometry={nodes._001_pm0479_16_00_prefab.geometry} material={materials.pm0479_16_00_BodyRotom02} skeleton={nodes._001_pm0479_16_00_prefab.skeleton} />
          <skinnedMesh name="_002_pm0479_16_00_prefab" geometry={nodes._002_pm0479_16_00_prefab.geometry} material={materials.pm0479_16_00_BodyRotomVco} skeleton={nodes._002_pm0479_16_00_prefab.skeleton} />
          <skinnedMesh name="_003_pm0479_16_00_prefab" geometry={nodes._003_pm0479_16_00_prefab.geometry} material={materials.pm0479_16_00_BodyRotom01} skeleton={nodes._003_pm0479_16_00_prefab.skeleton} />
          <skinnedMesh name="_005_pm0479_16_00_prefab" geometry={nodes._005_pm0479_16_00_prefab.geometry} material={materials.pm0479_16_00_FireMask} skeleton={nodes._005_pm0479_16_00_prefab.skeleton} />
          <skinnedMesh name="_006_pm0479_16_00_prefab" geometry={nodes._006_pm0479_16_00_prefab.geometry} material={materials.pm0479_16_00_BodyHinoarashi00} skeleton={nodes._006_pm0479_16_00_prefab.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/RotomMow.glb')
