/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/megaShiny/384.glb -o models/gltfjsx/megaShiny/384.jsx 
Author: Yo Boy (https://sketchfab.com/jratanatharathorn)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shiny-mega-rayquaza-e3a1627f9f8b4a8898cd971956e5a1fe
Title: Shiny Mega Rayquaza
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/mega/384.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, -89.467, 51.467]} rotation={[-Math.PI, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.color_0} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.color_10988977} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.color_14789940} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.color_15277357} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.color_15308428} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.color_2829873} />
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/mega/384.glb')
