/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/hisuian/503.glb -o models/gltfjsx/hisuian/503.jsx 
Author: Squirmy Worm (https://sketchfab.com/squirmyworm064)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hisuian-samurott-0b8f7f1d75364eb3a5d1289812e8e395
Title: Hisuian Samurott
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/503.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.color_10238775} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.color_12773119} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.color_13565968} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.color_1388369} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.color_16448250} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.color_2383528} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.color_2829873} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.color_6141417} />
      </group>
    </group>
  )
}

useGLTF.preload('/503.glb')
