/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/hisuian/713.glb -o models/gltfjsx/hisuian/713.jsx 
Author: Forsaken AR Official (https://sketchfab.com/FNAF_AR_Official)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mobile-pokemon-home-713-avalugg-hisuian-18d9ab3e3b884a94ad9161f1363387b2
Title: Mobile - Pokemon HOME - 713 Avalugg Hisuian
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/regular/713.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="hisuian_avalugg_with_animationfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Armature" scale={50}>
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_138" scale={50} />
                    <skinnedMesh name="Object_139" geometry={nodes.Object_139.geometry} material={materials['pm0713_00_41-BodyB01']} skeleton={nodes.Object_139.skeleton} />
                    <skinnedMesh name="Object_140" geometry={nodes.Object_140.geometry} material={materials['pm0713_00_41-BodyA00']} skeleton={nodes.Object_140.skeleton} />
                    <skinnedMesh name="Object_141" geometry={nodes.Object_141.geometry} material={materials['pm0713_00_41-BodyB02']} skeleton={nodes.Object_141.skeleton} />
                    <skinnedMesh name="Object_142" geometry={nodes.Object_142.geometry} material={materials['pm0713_00_41-LEye']} skeleton={nodes.Object_142.skeleton} />
                    <skinnedMesh name="Object_143" geometry={nodes.Object_143.geometry} material={materials['pm0713_00_41-BodyB00']} skeleton={nodes.Object_143.skeleton} />
                    <skinnedMesh name="Object_144" geometry={nodes.Object_144.geometry} material={materials['pm0713_00_41-REye']} skeleton={nodes.Object_144.skeleton} />
                    <skinnedMesh name="Object_145" geometry={nodes.Object_145.geometry} material={materials['pm0713_00_41-BodyA01']} skeleton={nodes.Object_145.skeleton} />
                  </group>
                </group>
                <group name="pm0713_00_41_BodyASkin" scale={50} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/regular/713.glb')
