/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/galar/109.glb -o models/gltfjsx/galar/109.jsx 
Author: reactorous (https://sketchfab.com/reactorous)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/galarian-koffing-71592d32abce45a89abb6e8682a7b893
Title: Galarian Koffing
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/regular/109.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere001_Box001_0.geometry} material={materials.Box001} position={[22689.467, -8859.675, 16291.276]} rotation={[1.543, -0.068, -0.067]} scale={[-2213.861, 1601.139, 2201.604]} />
      <mesh geometry={nodes.Sphere002_Box001_0.geometry} material={materials.Box001} position={[12650.058, 8647.604, 14866.561]} rotation={[-0.166, -0.535, -2.806]} scale={[-863.984, 863.984, 863.984]} />
      <mesh geometry={nodes.Sphere003_Box001_0.geometry} material={materials.Box001} position={[18945.004, 10746.62, -6491.916]} rotation={[2.182, 0.475, 1.754]} scale={[-2669.827, 2669.827, 2669.827]} />
      <mesh geometry={nodes.Sphere004_Box001_0.geometry} material={materials.Box001} position={[-19708.07, 17.476, 10131.476]} rotation={[0.485, 0.082, 1.84]} scale={[-1672.66, 1672.66, 1672.659]} />
      <mesh geometry={nodes.Sphere005_Box001_0.geometry} material={materials.Box001} position={[-21750.012, 11674.236, -8037.612]} rotation={[0.654, -0.914, -3.029]} scale={[-3258.931, 3258.931, 3258.93]} />
      <mesh geometry={nodes.Sphere006_Box001_0.geometry} material={materials.Box001} position={[-10672.477, 8723.735, -4586.898]} rotation={[-2.042, -0.426, -2.896]} scale={[-863.984, 863.984, 863.984]} />
      <mesh geometry={nodes.Sphere007_Box001_0.geometry} material={materials.Box001} position={[-25657.422, -10197.849, 4122.068]} rotation={[-0.014, 0.009, 1.208]} scale={[-927.128, 670.53, 921.995]} />
      <mesh geometry={nodes.Sphere008_Box001_0.geometry} material={materials.Box001} position={[-4134.247, 888.399, -19665.715]} rotation={[2.793, 0.567, 1.53]} scale={[-1915.584, 1915.584, 1915.585]} />
      <mesh geometry={nodes.Sphere009_Box001_0.geometry} material={materials.Box001} position={[13124.322, -5484.376, -15492.198]} rotation={[-0.007, 0.009, 1.208]} scale={[-927.128, 670.53, 921.995]} />
      <mesh geometry={nodes.Sphere010_Box001_0.geometry} material={materials.Box001} position={[-17477.484, -3079.619, -11510.303]} rotation={[-1.442, 0.112, 1.759]} scale={[-1672.66, 1672.659, 1672.659]} />
      <mesh geometry={nodes.Sphere_Box001_0.geometry} material={materials.Box001} position={[20457.861, -860.736, 4212.065]} rotation={[-2.042, -0.426, -2.896]} scale={[-863.984, 863.984, 863.984]} />
      <mesh geometry={nodes.Box001_Group16296_0.geometry} material={materials.Group16296} position={[2090.335, -4886.19, 5504.316]} scale={229.971} />
      <mesh geometry={nodes.Group16296_Box001_0.geometry} material={materials.Box001} position={[2090.335, -4886.19, 5504.316]} scale={229.971} />
      <mesh geometry={nodes.Group20204_Body_Mat_0.geometry} material={materials.Body_Mat} position={[2090.335, -4886.19, 5504.316]} scale={229.971} />
      <mesh geometry={nodes.Group48858_Grey_Plastic_0.geometry} material={materials.Grey_Plastic} position={[2090.335, -4976.795, 6322.68]} scale={229.971} />
      <mesh geometry={nodes.Group48861_Group48861_0.geometry} material={materials.Group48861} position={[2090.335, -4886.19, 5504.316]} scale={229.971} />
      <mesh geometry={nodes.Group50461_Group48861_0.geometry} material={materials.Group48861} position={[2090.335, -4886.19, 5504.316]} scale={229.971} />
      <mesh geometry={nodes.hat_Grey_Plastic_0.geometry} material={materials.Grey_Plastic} position={[2090.335, -4886.19, 5504.316]} scale={229.971} />
      <mesh geometry={nodes.hat1_Grey_Plastic_0.geometry} material={materials.Grey_Plastic} position={[2090.335, -4886.19, 5504.316]} scale={229.971} />
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/regular/109.glb')
