/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/galar/263.glb -o models/gltfjsx/galar/263.jsx 
Author: Cozmoth (https://sketchfab.com/Cozmoth)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/galerian-zigzagoon-e1e0ff890e62474d9a5aadfcf750a4b8
Title: Galerian Zigzagoon
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/galar/263.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[348.319, 0.577, -19.623]} rotation={[0, -0.551, 0]} scale={0.125}>
          <mesh geometry={nodes.Cylinder001_Material_0.geometry} material={materials.Material} />
          <mesh geometry={nodes.Cylinder001_Material002_0.geometry} material={materials['Material.002']} />
        </group>
        <mesh geometry={nodes.Plane__0.geometry} material={materials.Plane__0} position={[700.239, 2.013, 0]} scale={[6.492, 4.212, 4.212]} />
        <mesh geometry={nodes.Cube007_Material001_0.geometry} material={materials['Material.001']} position={[348.319, 95.74, -19.623]} rotation={[0, -0.551, 0]} scale={0.43} />
        <mesh geometry={nodes.Cube008_Material002_0.geometry} material={materials['Material.002']} position={[348.319, 95.74, -19.623]} rotation={[0, -0.551, 0]} scale={0.43} />
        <mesh geometry={nodes.Cube009__0.geometry} material={materials.Plane__0} position={[383.381, 96.92, 5.332]} rotation={[-0.003, -0.548, 0.039]} scale={0.43} />
        <mesh geometry={nodes.Cube010_Material002_0.geometry} material={materials['Material.002']} position={[428.258, 98.041, 32.446]} rotation={[-0.003, -0.548, 0.039]} scale={0.46} />
        <mesh geometry={nodes.Cube011__0.geometry} material={materials.Plane__0} position={[455.916, 122.024, 47.206]} rotation={[-0.027, -0.529, 0.319]} scale={0.382} />
        <mesh geometry={nodes.Cube012_Material002_0.geometry} material={materials['Material.002']} position={[489.568, 144.433, 67.888]} rotation={[-0.027, -0.529, 0.319]} scale={0.382} />
        <mesh geometry={nodes.Cube013__0.geometry} material={materials.Plane__0} position={[238.042, 136.394, -87.394]} rotation={[0, -0.551, 0]} scale={[0.036, 0.123, 0.123]} />
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/galar/263.glb')
