/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/galar/79.glb -o models/gltfjsx/galar/79.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/79.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pm0079_00_31_body_mesh_shape_body_00.geometry} material={materials.body_00} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.pm0079_00_31_body_mesh_shape_body_01.geometry} material={materials.body_01} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.pm0079_00_31_body_mesh_shape_l_eye.geometry} material={materials.l_eye} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.pm0079_00_31_body_mesh_shape_r_eye.geometry} material={materials.r_eye} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/79.glb')
