/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/gmax/131.glb -o models/gltfjsx/gmax/131.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const { scene } = useGLTF('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/gmax/131.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <primitive object={nodes.pm0131_81_00} />
        <skinnedMesh geometry={nodes.pm0131_81_00_CrystalASkin.geometry} material={materials.BodyFEnvNon} skeleton={nodes.pm0131_81_00_CrystalASkin.skeleton} />
        <skinnedMesh geometry={nodes.pm0131_81_00_CrystalBSkin.geometry} material={materials.BodyFEnvNon} skeleton={nodes.pm0131_81_00_CrystalBSkin.skeleton} />
        <skinnedMesh geometry={nodes.pm0131_81_00_CrystalCSkin.geometry} material={materials.BodyFEnvNon} skeleton={nodes.pm0131_81_00_CrystalCSkin.skeleton} />
        <skinnedMesh geometry={nodes.pm0131_81_00_CrystalDSkin.geometry} material={materials.BodyFEnvNon} skeleton={nodes.pm0131_81_00_CrystalDSkin.skeleton} />
        <skinnedMesh geometry={nodes.pm0131_81_00_CrystalESkin.geometry} material={materials.BodyFEnvNon} skeleton={nodes.pm0131_81_00_CrystalESkin.skeleton} />
        <skinnedMesh geometry={nodes.pm0131_81_00_CrystalFSkin.geometry} material={materials.BodyFEnvNon} skeleton={nodes.pm0131_81_00_CrystalFSkin.skeleton} />
        <skinnedMesh geometry={nodes.pm0131_81_00_CrystalGSkin.geometry} material={materials.BodyFEnvNon} skeleton={nodes.pm0131_81_00_CrystalGSkin.skeleton} />
        <skinnedMesh geometry={nodes.pm0131_81_00_ScoreASkin.geometry} material={materials.BodyEEnvNon00} skeleton={nodes.pm0131_81_00_ScoreASkin.skeleton} />
        <skinnedMesh geometry={nodes.pm0131_81_00_ScoreBSkin.geometry} material={materials.BodyEEnvNon01} skeleton={nodes.pm0131_81_00_ScoreBSkin.skeleton} />
        <skinnedMesh geometry={nodes.pm0131_81_00_shineASkin.geometry} material={materials.BodyG} skeleton={nodes.pm0131_81_00_shineASkin.skeleton} />
        <skinnedMesh geometry={nodes.pm0131_81_00_shineBSkin.geometry} material={materials.BodyG} skeleton={nodes.pm0131_81_00_shineBSkin.skeleton} />
        <skinnedMesh geometry={nodes.pm0131_81_00_shineCSkin.geometry} material={materials.BodyG} skeleton={nodes.pm0131_81_00_shineCSkin.skeleton} />
        <skinnedMesh geometry={nodes.pm0131_81_00_BodySkin_2.geometry} material={materials.BodyB00} skeleton={nodes.pm0131_81_00_BodySkin_2.skeleton} />
        <skinnedMesh geometry={nodes.pm0131_81_00_BodySkin_3.geometry} material={materials.BodyAEnv} skeleton={nodes.pm0131_81_00_BodySkin_3.skeleton} />
        <skinnedMesh geometry={nodes.pm0131_81_00_BodySkin_4.geometry} material={materials.Eye} skeleton={nodes.pm0131_81_00_BodySkin_4.skeleton} />
        <skinnedMesh geometry={nodes.pm0131_81_00_BodySkin_5.geometry} material={materials.BodyC} skeleton={nodes.pm0131_81_00_BodySkin_5.skeleton} />
        <skinnedMesh geometry={nodes.pm0131_81_00_BodySkin_6.geometry} material={materials.BodyD} skeleton={nodes.pm0131_81_00_BodySkin_6.skeleton} />
        <skinnedMesh geometry={nodes.pm0131_81_00_BodySkin_7.geometry} material={materials.BodyBEnv} skeleton={nodes.pm0131_81_00_BodySkin_7.skeleton} />
        <skinnedMesh geometry={nodes.pm0131_81_00_BodySkin_8.geometry} material={materials.BodyB01} skeleton={nodes.pm0131_81_00_BodySkin_8.skeleton} />
        <skinnedMesh geometry={nodes.pm0131_81_00_BodySkin_9.geometry} material={materials.BodyCVco} skeleton={nodes.pm0131_81_00_BodySkin_9.skeleton} />
        <skinnedMesh geometry={nodes.pm0131_81_00_BodySkin_10.geometry} material={materials.BodyDVco} skeleton={nodes.pm0131_81_00_BodySkin_10.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('https://raw.githubusercontent.com/Sudhanshu-Ambastha/Pokemon-3D/main/models/glb/gmax/131.glb')
