/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/glb/gmax/9.glb -o models/gltfjsx/gmax/9.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const { scene } = useGLTF('/9.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.226}>
        <primitive object={nodes.pm0009_81_00} />
        <skinnedMesh geometry={nodes.pm0009_81_00_BodySkin_2.geometry} material={materials.LEye} skeleton={nodes.pm0009_81_00_BodySkin_2.skeleton} />
        <skinnedMesh geometry={nodes.pm0009_81_00_BodySkin_3.geometry} material={materials.BodyA01} skeleton={nodes.pm0009_81_00_BodySkin_3.skeleton} />
        <skinnedMesh geometry={nodes.pm0009_81_00_BodySkin_4.geometry} material={materials.REye} skeleton={nodes.pm0009_81_00_BodySkin_4.skeleton} />
        <skinnedMesh geometry={nodes.pm0009_81_00_BodySkin_5.geometry} material={materials.BodyA00} skeleton={nodes.pm0009_81_00_BodySkin_5.skeleton} />
        <skinnedMesh geometry={nodes.pm0009_81_00_CanonSkin_2.geometry} material={materials.BodyBEnv02} skeleton={nodes.pm0009_81_00_CanonSkin_2.skeleton} />
        <skinnedMesh geometry={nodes.pm0009_81_00_CanonSkin_3.geometry} material={materials.BodyBEnv03} skeleton={nodes.pm0009_81_00_CanonSkin_3.skeleton} />
        <skinnedMesh geometry={nodes.pm0009_81_00_ShellSkin_2.geometry} material={materials.BodyB01} skeleton={nodes.pm0009_81_00_ShellSkin_2.skeleton} />
        <skinnedMesh geometry={nodes.pm0009_81_00_ShellSkin_3.geometry} material={materials.BodyC00} skeleton={nodes.pm0009_81_00_ShellSkin_3.skeleton} />
        <skinnedMesh geometry={nodes.pm0009_81_00_ShellSkin_4.geometry} material={materials.BodyC01} skeleton={nodes.pm0009_81_00_ShellSkin_4.skeleton} />
        <skinnedMesh geometry={nodes.pm0009_81_00_ShellSkin_5.geometry} material={materials.BodyB00} skeleton={nodes.pm0009_81_00_ShellSkin_5.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/9.glb')
