name: Process GLB & JSX Files

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  process-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Create Logs Directory
        run: mkdir -p logs

      - name: Detect Missing JSX Files
        run: bash scripts/detect_missing.sh

      - name: Convert GLB Files to JSX
        run: bash scripts/convert.sh

      - name: Update JSX Files
        run: bash scripts/update_jsx.sh ${{ github.repository }} main

      - name: Handle Conversion Errors
        run: bash scripts/handle_errors.sh

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bash scripts/commit_push.sh
