name: Update JSX File Paths

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  update-jsx-paths:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get full history

      - name: Find Uncommitted JSX Files
        id: uncommitted-jsx
        run: |
          UNCOMMITTED_FILES=$(git ls-files --others --exclude-standard -- models/gltfjsx/*.jsx)
          echo "Uncommitted JSX files: $UNCOMMITTED_FILES"
          echo "UNCOMMITTED_FILES=$UNCOMMITTED_FILES" >> $GITHUB_ENV

      - name: Find and Update JSX Files
        id: update-jsx
        run: |
          GITHUB_BASE_URL="https://raw.githubusercontent.com/${{ github.repository }}/main"
          UPDATED_FILES=""

          # Find all JSX files in models/gltfjsx/
          for jsx_file in $(find models/gltfjsx -name "*.jsx"); do
            model_name=$(basename "$jsx_file" .jsx)
            glb_file=$(find models/glb -name "$model_name.glb" | head -n 1)  # Find matching GLB
            
            if [ -z "$glb_file" ]; then
              echo "❌ No matching GLB for $jsx_file, skipping..."
              continue
            fi

            github_glb_url="$GITHUB_BASE_URL/$glb_file"

            # Update useGLTF paths
            if grep -q 'useGLTF("' "$jsx_file"; then
              if ! grep -q "useGLTF(\"$github_glb_url\")" "$jsx_file"; then
                echo "🔄 Updating path in: $jsx_file"
                sed -i "s|useGLTF(\".*.glb\")|useGLTF(\"$github_glb_url\")|" "$jsx_file"
                sed -i "s|useGLTF.preload(\".*.glb\")|useGLTF.preload(\"$github_glb_url\")|" "$jsx_file"
                UPDATED_FILES+="$jsx_file\n"
              fi
            fi

            # Ensure default export
            if grep -q "export function Model" "$jsx_file"; then
              echo "🔄 Converting to default export: $jsx_file"
              sed -i 's/export function Model/export default function Model/' "$jsx_file"
              UPDATED_FILES+="$jsx_file\n"
            fi
          done

          echo -e "UPDATED_FILES<<EOF\n$UPDATED_FILES\nEOF" >> $GITHUB_ENV

      - name: Commit and Push Changes
        if: env.UPDATED_FILES != '' || env.UNCOMMITTED_FILES != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add models/gltfjsx/
          git status  # Debugging output

          if git diff --cached --exit-code; then
            echo "✅ No changes to commit"
            exit 0
          fi

          git commit -m "Updated JSX file paths and exports"
          git push origin main || (echo "⚠️ Main branch protected, creating new branch..." && \
            git checkout -b update-jsx-paths && git push origin update-jsx-paths)
