name: Update GLB Paths in JSX

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  update-glb-paths:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update GLB Paths in JSX
        id: update-paths
        run: |
          GITHUB_BASE_URL="https://raw.githubusercontent.com/${{ github.repository }}/main"
          UPDATED_FILES=""

          # Iterate through all JSX files in models/gltfjsx/
          for jsx_file in $(find models/gltfjsx -name "*.jsx"); do
            model_name=$(basename "$jsx_file" .jsx)

            # Find the correct GLB file
            glb_file=$(find models/glb -name "$model_name.glb" | head -n 1)

            if [ -z "$glb_file" ]; then
              echo "❌ No matching GLB found for $jsx_file, skipping..."
              continue
            fi

            github_glb_url="$GITHUB_BASE_URL/$glb_file"

            # Update useGLTF paths
            sed -i "s|useGLTF('/[^']*.glb')|useGLTF('$github_glb_url')|" "$jsx_file"
            sed -i "s|useGLTF.preload('/[^']*.glb')|useGLTF.preload('$github_glb_url')|" "$jsx_file"

            UPDATED_FILES+="$jsx_file\n"
          done

          echo -e "UPDATED_FILES<<EOF\n$UPDATED_FILES\nEOF" >> $GITHUB_ENV

      - name: Commit and Push Changes
        if: env.UPDATED_FILES != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add models/gltfjsx/
          git status  # Debugging output

          if git diff --cached --exit-code; then
            echo "✅ No changes to commit"
            exit 0
          fi

          git commit -m "Updated GLB paths in JSX files"
          git push origin main || (echo "⚠️ Main branch protected, creating new branch..." && \
            git checkout -b update-glb-paths && git push origin update-glb-paths)
